"""Generate gga_training_example-step7.ipynb.

Pattern matches notebooks/_build_step{4,5,6}_notebook.py: assemble cells
into nbformat structure, write .ipynb, optionally execute end-to-end.

Step-7 plan (mixed-pool refactor 2026-05-07):
  - Build the Dick 2021 SI II training pool as 26 mixed TrainingPoints
    (21 AE + 3 BH76 + 2 IP13) via xcquinox.alec.training_points.
  - Extract (rho^{1/3}, s, alpha) PER SPECIES (deduped across points),
    then concatenate across each point's species (design choice "a")
    to form one descriptor block per training point.
  - Build reference 3-histogram from the per-point descriptors so a
    multi-species point (BH76 reaction) carries proportionally larger
    weight in the reference distribution.
  - Sweep r in {1,2,3,4,5,6,7,12,15,18} x {l2, jsd} x {oneshot, full_3}
    = 40 training runs.  Atom regularizers restricted to Dick H/Li.
    No HBPT augmentation (dropped 2026-05-07).
  - Post-process: 6+1 figures + headline.json

Citations:
  - PBE 1996  (PRL 77, 3865) -- descriptor s
  - SCAN 2015 (PRL 115, 036402) -- descriptor alpha
  - Lin 1991  (IEEE TIT 37, 145) -- JSD
  - Chen 2018 (arXiv:1711.02257) -- GradNorm
  - Dick 2021 (PRB 104, L161109) -- candidate pool
"""
from __future__ import annotations

import nbformat as nbf
from pathlib import Path

NOTEBOOK_OUT = Path(__file__).resolve().parent / "gga_training_example-step7.ipynb"


def _md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def _code(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(text)


# Constants -------------------------------------------------------------
SUBSET_SIZES = (1, 2, 3, 4, 5, 6, 7, 12, 15, 18)  # excludes r=26 (full mixed pool)
METRICS = ("l2", "jsd")
SOLVERS = ("oneshot", "full_3")
ARCH_NAME = "deep_combined_attn"
LOSS_NAME = "L5_gradnorm_vxc_step7"
PRETRAIN_ORIGIN = "integration"  # ONLY origin — unweighted is out of scope per step-6 verdict.
# Pretrain phase: 1000 steps already baked into step-6 integration
# checkpoint (loaded from notebooks/checkpoints_step6/integration/pretrain/
# deep_combined_attn/{xnet.eqx, cnet.eqx}); no re-pretraining in step-7.
# Task-loss phase: 100 steps (matches step-6 group1/group2 short schedule;
# step-6 group3 used 250 but at 80 runs the additional convergence gain
# does not justify the 2.5x cost given step-6 evidence).
TRAIN_N_STEPS = 100
LR_START, LR_END = 1e-2, 1e-5
LR_DECAY_START = 0.2
GRAD_CLIP = 1.0


def build_cells(mode: str = "train") -> list:
    """Assemble notebook cells.

    mode='train'  -> the step-7 training/eval notebook; LOADS a pre-generated
                     subset ledger (subset generation lives in its own notebook).
    mode='subset' -> the standalone subset-GENERATION notebook: descriptor
                     extraction + reference-histogram match + ledger writing.
    """
    assert mode in ("train", "subset"), mode
    cells: list = []
    if mode == "subset":
        cells.append(_md(
            "# Step-7a: Histogram-Matched Subset GENERATION (Dick 2021 Pool)\n\n"
            "Standalone subset-selection pre-process, split out of the step-7\n"
            "training notebook. Minimizes the distance between candidate-subset\n"
            "and full-pool histograms over $(\\rho^{1/3}, s, \\alpha)$ and writes a\n"
            "`subset_index_log.json` ledger + per-spec `subset.traj` files that the\n"
            "step-7 training notebook (`gga_training_example-step7.ipynb`) and the\n"
            "SLURM harness CONSUME read-only.\n\n"
            "**Critical:** $\\alpha$ enters the subset-selection objective only -- the\n"
            "trained GGA network does NOT consume it (C4-03: toggle with the\n"
            "`STEP7_IGNORE_ALPHA` env var). Reference: Dick & Fernandez-Serra,\n"
            "*Phys. Rev. B* **104**, L161109 (2021), SI II.\n"
        ))
    else:
        cells.append(_md(
            "# Step-7: Training / Eval on Histogram-Matched Subsets (Dick 2021 Pool)\n\n"
            "Loads the `subset_index_log.json` ledger produced by the standalone\n"
            "subset-generation notebook (`gga_subset_generation.ipynb`) and runs the\n"
            "training + evaluation grid over\n"
            "$|\\text{sizes}| \\times |\\text{metrics}| \\times |\\text{solvers}|$.\n\n"
            "**Critical:** $\\alpha$ enters subset selection only -- the trained GGA\n"
            "network does NOT consume it. Future MGGA extension is step-8+.\n\n"
            "Reference: Dick & Fernandez-Serra, *Phys. Rev. B* **104**, L161109 (2021), SI II.\n"
        ))
    cells += _config_cells()
    if mode == "subset":
        cells += _subset_generation_cells()
    else:
        cells += _oep_ccsd_cells()
        cells += _train_points_ledger_cells()
        cells += _smoke_and_training_cells()
    return cells


def _config_cells() -> list:
    cells: list = []
    cells.append(_code(
        "import gc\n"
        "import json\n"
        "import os\n"
        "import sys\n\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import pandas as pd\n"
        "from pathlib import Path\n\n"
        "import jax\n"
        "# JAX config (mirrors step-6 cell 2): pin x64 dtype and CPU device\n"
        "# *before* importing jnp or any library that may trigger JAX tracing.\n"
        "# These must not change later in the notebook -- flipping\n"
        "# jax_enable_x64 after traces are cached produces inconsistent dtypes\n"
        "# and breaks numerical comparisons against step-5/6 checkpoints.\n"
        'jax.config.update(\"jax_enable_x64\", True)\n'
        'jax.config.update(\"jax_default_device\", jax.devices(\"cpu\")[0])\n'
        "# Persistent compilation cache: writes compiled XLA HLO/LLVM to disk\n"
        "# so that kernel restarts (e.g. after a crash) and across-spec calls\n"
        "# in the 80-spec grid don't re-pay the full compile cost.\n"
        'os.makedirs(\".jax_compilation_cache\", exist_ok=True)\n'
        'jax.config.update(\"jax_compilation_cache_dir\", \".jax_compilation_cache\")\n'
        'jax.config.update(\"jax_persistent_cache_min_entry_size_bytes\", -1)\n'
        'jax.config.update(\"jax_persistent_cache_min_compile_time_secs\", 1.0)\n'
        "import jax.numpy as jnp\n"
        "import equinox as eqx\n\n"
        "# tqdm.auto picks tqdm.notebook.tqdm (ipywidgets) under JupyterLab\n"
        "# and tqdm.std.tqdm in a plain script/terminal, so the same symbol\n"
        "# gives a sensible progress bar in either context. Imported globally\n"
        "# (step-6 parity) so per-task / per-spec / per-step bars in later\n"
        "# cells share one library instance and one display.\n"
        "from tqdm.auto import tqdm\n\n"
        "# BLAS thread cap: PySCF SCF (used by descriptor extraction, eval,\n"
        "# and run_test) is CPU-bound via OpenMP-threaded BLAS. Because this\n"
        "# kernel ALSO imports JAX (which maintains its own thread pool),\n"
        "# leaving PySCF at its default thread count (N-cores) causes\n"
        "# oversubscription. Mirrors step-6 cell 2.\n"
        "from contextlib import contextmanager as _contextmanager\n"
        "from pyscf import lib as _pyscf_lib\n\n"
        "@_contextmanager\n"
        "def _capped_blas_threads(n=4):\n"
        "    \"\"\"Temporarily cap PySCF's BLAS thread count to `n`.\"\"\"\n"
        "    _prev = _pyscf_lib.num_threads()\n"
        "    _pyscf_lib.num_threads(min(_prev, int(n)))\n"
        "    try:\n"
        "        yield\n"
        "    finally:\n"
        "        _pyscf_lib.num_threads(_prev)\n\n"
        "import xcquinox.alec as alec\n"
        "from xcquinox.alec import subset_selection as ss\n"
        "from xcquinox.alec import dfs_pool\n"
        "from xcquinox.alec import losses\n\n"
        "REPO = Path('/home/awills/Documents/Research/xcquinox')\n"
        "# C4-03: alpha (the meta-GGA tau descriptor) enters subset SELECTION\n"
        "# only -- the GGA network is blind to it. Set STEP7_IGNORE_ALPHA=1 to\n"
        "# drop alpha from the histogram-matching objective\n"
        "# (descriptor_weights={'alpha': 0.0}); default keeps the alpha-weighted\n"
        "# selection. Each mode writes to its OWN root so the alpha-on and\n"
        "# alpha-off experiments (x L2/JSD metrics) coexist without clobbering.\n"
        "_IGNORE_ALPHA = os.environ.get('STEP7_IGNORE_ALPHA', '0') == '1'\n"
        "DESCRIPTOR_WEIGHTS = {'alpha': 0.0} if _IGNORE_ALPHA else None\n"
        "_ALPHA_MODE = 'alpha_off' if _IGNORE_ALPHA else 'alpha_on'\n"
        "STEP7_ROOT = REPO / 'notebooks' / 'checkpoints_step7' / _ALPHA_MODE\n"
        "print(f'[C4-03] subset-selection descriptor mode={_ALPHA_MODE} '\n"
        "      f'descriptor_weights={DESCRIPTOR_WEIGHTS}')\n"
        "DESCRIPTOR_CACHE = STEP7_ROOT / 'subset_descriptors'\n"
        "REF_HIST_CACHE = STEP7_ROOT / 'dfs_pool_full_hist'\n"
        "DESCRIPTOR_CACHE.mkdir(parents=True, exist_ok=True)\n"
        "REF_HIST_CACHE.mkdir(parents=True, exist_ok=True)\n"
        "EXTERNAL_REFS_DIR = STEP7_ROOT / 'external_refs'\n"
        "EXTERNAL_REFS_DIR.mkdir(parents=True, exist_ok=True)\n"
        "DISTRIBUTIONS_DIR = STEP7_ROOT / 'subset_index_log_distributions'\n"
        "DISTRIBUTIONS_DIR.mkdir(parents=True, exist_ok=True)\n\n"
        "# Step-6 parity: BASIS / GRID_LEVEL match step-5/6 conventions so\n"
        "# checkpoints carry across notebooks and descriptors are commensurate.\n"
        "BASIS = 'def2-svp'\n"
        "GRID_LEVEL = 1\n\n"
        "pool = dfs_pool.build_dfs_pool()\n"
        "print(f'JAX x64: {jax.config.read(\"jax_enable_x64\")}; '\n"
        "      f'default device: {jax.config.jax_default_device}')\n"
        "print(f'Dick 2021 SI II training pool: {pool[\"n_total\"]} entries')\n"
        "print(f'  AE molecules: {len(pool[\"ae_molecules\"])}')\n"
        "print(f'  BH76 reactions: {len(pool[\"bh76_reactions\"])}')\n"
        "print(f'  IP13 pairs: {len(pool[\"ip13_pairs\"])}')\n"
        "print(f'  Atom refs: {len(pool[\"atom_refs\"])}')\n"
    ))
    return cells


def _oep_ccsd_cells() -> list:
    cells: list = []
    cells.append(_md(
        "## Per-species OEP cascade overrides\n\n"
        "Species in `xcquinox.alec.external_refs._PER_SPECIES_OEP_OVERRIDES`\n"
        "use tuned cascade settings keyed by `(name, charge, spin)`. The\n"
        "override mechanism is motivated by literature on basis-set-sensitive\n"
        "Wu-Yang inversion: Heaton-Burgess–Bulat–Yang [oep-tdl-1];\n"
        "Bulat–Heaton-Burgess–Cohen–Yang [oep-tdl-2]; Bulat–Yang [oep-tdl-4];\n"
        "Ryabinkin–Kohut–Staroverov [oep-tdl-5]; Kohut–Ryabinkin–Staroverov\n"
        "[oep-tdl-6]. Forward-looking reference [oep-tdl-3] (Hsu–Yang,\n"
        "even-tempered aux for atomic OEP) is retained in the bibliography\n"
        "as a fallback option for future v2 sweeps if the v1 jkfit-family\n"
        "sweep fails to converge a species. Tune logs live under\n"
        "`reports_local/oep_tune/<date>/`. **All citation tags resolve to\n"
        "TO-DOWNLOAD entries at the end of `reports_local/latex/references.bib`\n"
        "and are AUTHOR-RECALLED, UNVERIFIED** — verify each via WebFetch +\n"
        "pdftotext before paper write-up; do not promote to `@article`\n"
        "entries until verified.\n"
    ))
    cells.append(_md(
        "## 0.5. CCSD Reference Pre-Compute (Cell 0.5)\n\n"
        "For every species in the union of (DFS pool, BH76 reactants/products,\n"
        "IP13 neutrals/cations, atom refs, Probe A/B/C/D, HBPT pairs), run\n"
        "RHF/UHF + RCCSD/UCCSD at def2-svp / grid_level=1 and OEP-invert via\n"
        "the step-6 2-tier cascade.  Writes per-species `<name>.npz` to\n"
        "`notebooks/checkpoints_step7/external_refs/`.  Idempotent: skips\n"
        "species whose `.npz` is already complete.\n\n"
        "Pre-flight smoke tests UKS-OEP on HO (2-Pi doublet) and HN (3-Sigma-\n"
        "triplet) before bulk pre-compute -- aborts early on UKS shape\n"
        "mismatch.\n\n"
        "Wall-clock estimate: ~1-3 hr first run; <1 min cached re-run.\n"
    ))
    cells.append(_code(
        "from xcquinox.alec.external_refs import (\n"
        "    build_species_union, precompute_all,\n"
        ")\n\n"
        "_species = build_species_union()\n"
        "print(f'Cell 0.5: pre-computing CCSD references for {len(_species)} species')\n"
        "for _s in _species:\n"
        "    print(f'  {_s.name:8s}  charge={_s.charge}  spin={_s.spin}  '\n"
        "          f'source={_s.source}')\n"
        "precompute_all(\n"
        "    _species,\n"
        "    cache_dir=EXTERNAL_REFS_DIR,\n"
        "    basis=BASIS,\n"
        "    grid_level=GRID_LEVEL,\n"
        "    run_preflight=True,\n"
        ")\n"
    ))
    return cells


def _subset_generation_cells() -> list:
    cells: list = []
    cells.append(_md(
        "## 1. Mixed-Pool Descriptor Extraction (cached)\n\n"
        "Build the 26-point Dick training pool (21 AE + 3 BH76 + 2 IP13) as\n"
        "`TrainingPoint` records (each carries the species needed by its\n"
        "loss channel, with atom anchors restricted to the Dick set\n"
        "$\\{\\mathrm{H}, \\mathrm{Li}\\}$). Run a single PBE SCF\n"
        "at def2-svp / grid_level=1 per UNIQUE species (deduped by\n"
        "$(name, charge, spin)$) and cache descriptors as\n"
        "`subset_descriptors/<name>_c<charge>_s<spin>.npz`. Then\n"
        "concatenate per-species descriptors across each TrainingPoint's\n"
        "species (design choice \"a\") to obtain one descriptor block\n"
        "per point — multi-species points (reactions) thus weigh more\n"
        "in the reference distribution proportional to grid-point count.\n"
    ))
    cells.append(_code(
        "from xcquinox.alec.training_points import (\n"
        "    build_dfs_pool_points, species_union_from_points,\n"
        "    DICK_ATOM_REGULARIZER_SYMS,\n"
        ")\n"
        "points = build_dfs_pool_points()\n"
        "_by_kind = {'ae': 0, 'bh76': 0, 'ip13': 0}\n"
        "for p in points:\n"
        "    _by_kind[p.kind] += 1\n"
        "print(f'Mixed pool: {len(points)} points '\n"
        "      f'({_by_kind[\"ae\"]} AE + {_by_kind[\"bh76\"]} BH76 + '\n"
        "      f'{_by_kind[\"ip13\"]} IP13). Dick atom regularizer set: '\n"
        "      f'{DICK_ATOM_REGULARIZER_SYMS}.')\n"
        "_all_species = species_union_from_points(points)\n"
        "print(f'Unique species across pool (dedup by name+charge+spin): '\n"
        "      f'{len(_all_species)}')\n"
        "species_descriptors = ss.extract_descriptors_for_species(\n"
        "    _all_species, basis=BASIS, grid_level=GRID_LEVEL,\n"
        "    cache_dir=DESCRIPTOR_CACHE,\n"
        ")\n"
        "for idx, p in enumerate(points):\n"
        "    print(f'  {idx:2d} [{p.kind:4s}] {p.name:24s} '\n"
        "          f'n_species={len(p.species)}')\n"
        "point_descriptors = ss.concatenate_point_descriptors(\n"
        "    points, species_descriptors)\n"
        "print(f'Built per-point descriptors: {len(point_descriptors)} '\n"
        "      f'(parallel to points)')\n"
    ))
    cells.append(_md(
        "## 2. Reference-Histogram Builder\n\n"
        "Concatenate descriptors across the full 26-point mixed pool\n"
        "(per-point blocks already concatenated across each point's\n"
        "species) and build 3 200-bin **linear-edge** histograms over\n"
        "$(\\rho^{1/3}, s, \\alpha)$ (per-feature $[0.1, 99.9]$-percentile\n"
        "range; the L2/JSD metrics PMF-normalize each marginal for equal\n"
        "cross-feature treatment). Same edges are reused for every\n"
        "candidate-subset histogram. Distributions are plotted on log-scale\n"
        "axes for readability.\n"
    ))
    cells.append(_code(
        "import numpy as np\n"
        "h_ref, edges = ss.build_reference_histograms(point_descriptors)\n"
        "ref_path = REF_HIST_CACHE / 'reference.npz'\n"
        "np.savez(ref_path,\n"
        "         h_ref_rho=h_ref['rho_third'], e_rho=edges['rho_third'],\n"
        "         h_ref_s=h_ref['s'],         e_s=edges['s'],\n"
        "         h_ref_alpha=h_ref['alpha'], e_alpha=edges['alpha'])\n"
        "print(f'Wrote reference histograms to {ref_path}')\n"
        "for k in ('rho_third', 's', 'alpha'):\n"
        "    print(f'  {k:10s} histogram: shape={h_ref[k].shape}, sum={h_ref[k].sum():.4f}')\n"
    ))
    cells.append(_md(
        "## 3. Subset Generation Sweep (mixed pool)\n\n"
        "For each $(r, \\text{metric})$, call `select_subset` over the\n"
        "26-point mixed pool, materialize the chosen-points'\n"
        "deduplicated species union as `subset.traj`, and record the\n"
        "chosen pool indices + metric value to a JSON ledger. Atom\n"
        "anchors are restricted to the Dick set $\\{\\mathrm{H}, \\mathrm{Li}\\}$\n"
        "by `TrainingPoint` construction — nothing is forcibly added.\n"
        "Spec count = $|\\text{sizes}| \\times |\\text{metrics}| \\times |\\text{solvers}|$.\n"
    ))
    cells.append(_code(
        "from ase.io import write as ase_write\n"
        "import json\n"
        "import os as _os_smoke\n\n"
        "_SMOKE = _os_smoke.environ.get('STEP7_SMOKE_ONLY', '0') == '1'\n"
        "if _SMOKE:\n"
        f"    SUBSET_SIZES = (2,)\n"
        f"    METRICS = ('l2',)\n"
        f"    SOLVERS = ('oneshot',)\n"
        f"    TRAIN_N_STEPS = 5\n"
        "    print('[SMOKE MODE] restricted to 1 spec: l2/r=2/oneshot, 5 steps')\n"
        "else:\n"
        f"    SUBSET_SIZES = {SUBSET_SIZES!r}\n"
        f"    METRICS = {METRICS!r}\n"
        f"    SOLVERS = {SOLVERS!r}\n"
        f"    TRAIN_N_STEPS = {TRAIN_N_STEPS!r}\n"
        f"LR_START = {LR_START!r}\n"
        f"LR_END = {LR_END!r}\n"
        f"LR_DECAY_START = {LR_DECAY_START!r}\n"
        f"GRAD_CLIP = {GRAD_CLIP!r}\n"
        f"ARCH_NAME = {ARCH_NAME!r}\n"
        f"LOSS_NAME = {LOSS_NAME!r}\n\n"
        "import time as _time\n"
        "import math as _math\n"
        "ledger_path = STEP7_ROOT / 'subset_index_log.json'\n"
        "# Each (metric, r) entry stores: chosen_indices into the 26-point\n"
        "# mixed pool, the per-point kinds + names (for inspection), and\n"
        "# the metric value, so a killed run resumes at the next un-\n"
        "# enumerated pair without re-running the L2/JSD search for sizes\n"
        "# already on disk.\n"
        "subset_index_log: dict = {}\n"
        "if ledger_path.exists():\n"
        "    _existing = json.loads(ledger_path.read_text())\n"
        "    for _slashkey, _val in _existing.items():\n"
        "        _m, _r = _slashkey.split('/')\n"
        "        subset_index_log[(_m, int(_r))] = _val\n"
        "    print(f'Resumed ledger: {len(subset_index_log)} (metric, r) '\n"
        "          f'entries already on disk at {ledger_path}')\n"
        "\n"
        "def _write_ledger():\n"
        "    \"\"\"Serialize subset_index_log to disk.  Called after EACH (metric, r)\n"
        "    pair completes so partial progress survives a Ctrl-C / OOM / crash.\"\"\"\n"
        "    ledger_path.write_text(json.dumps(\n"
        "        {f'{k[0]}/{k[1]}': v for k, v in subset_index_log.items()},\n"
        "        indent=2))\n"
        "\n"
        "_n_pairs = len(METRICS) * len(SUBSET_SIZES)\n"
        "_t0_overall = _time.time()\n"
        "_pair_idx = 0\n"
        "_n_pool = len(points)\n"
        "print(f'Subset generation: {_n_pairs} (metric, r) pairs over '\n"
        "      f'{_n_pool} mixed-pool candidates; per-pair combos = '\n"
        "      f'C({_n_pool}, r). Ledger persists after each pair.')\n"
        "for metric in METRICS:\n"
        "    for r in SUBSET_SIZES:\n"
        "        _pair_idx += 1\n"
        "        # Skip-if-cached: trust the ledger entry only if every\n"
        "        # subset.traj under this (metric, r) is also on disk\n"
        "        # (otherwise the cache is stale / partial).\n"
        "        _all_present = (\n"
        "            (metric, r) in subset_index_log\n"
        "            and all(\n"
        "                (STEP7_ROOT / metric /\n"
        "                 f'bin{r:02d}' /\n"
        "                 ARCH_NAME / LOSS_NAME / solver / 'subset.traj').exists()\n"
        "                for solver in SOLVERS\n"
        "            )\n"
        "        )\n"
        "        if _all_present:\n"
        "            print(f'[{_pair_idx:>2d}/{_n_pairs}] metric={metric} r={r:>2d}  '\n"
        "                  f'CACHED (ledger + all subset.traj present); skip.',\n"
        "                  flush=True)\n"
        "            continue\n"
        "        _ncombo = _math.comb(_n_pool, r)\n"
        "        _t0 = _time.time()\n"
        "        print(f'[{_pair_idx:>2d}/{_n_pairs}] metric={metric} r={r:>2d}  '\n"
        "              f'enumerating C({_n_pool},{r})={_ncombo:,} combos...',\n"
        "              flush=True)\n"
        "        _save_dist = _os_smoke.environ.get('STEP7_SAVE_DISTRIBUTIONS', '0') == '1'\n"
        "        _dist_path = (str(DISTRIBUTIONS_DIR /\n"
        "                          f'{metric}_r{r:02d}.npz')\n"
        "                      if _save_dist else None)\n"
        "        if _save_dist:\n"
        "            chosen, val, _vals_all, _idx_all = ss.select_subset(\n"
        "                point_descriptors, edges, h_ref, r=r, metric=metric,\n"
        "                descriptor_weights=DESCRIPTOR_WEIGHTS,\n"
        "                progress_desc=f'{metric} r={r}',\n"
        "                return_all=True,\n"
        "                distribution_path=_dist_path)\n"
        "        else:\n"
        "            chosen, val = ss.select_subset(\n"
        "                point_descriptors, edges, h_ref, r=r, metric=metric,\n"
        "                descriptor_weights=DESCRIPTOR_WEIGHTS,\n"
        "                progress_desc=f'{metric} r={r}')\n"
        "        _dt = _time.time() - _t0\n"
        "        _elapsed = _time.time() - _t0_overall\n"
        "        _eta = (_elapsed / _pair_idx) * (_n_pairs - _pair_idx)\n"
        "        chosen_points = [points[i] for i in chosen]\n"
        "        print(f'    -> chosen indices={list(chosen)}  '\n"
        "              f'metric_value={val:.6e}  dt={_dt:.1f}s  '\n"
        "              f'elapsed={_elapsed/60:.1f}min  eta={_eta/60:.1f}min',\n"
        "              flush=True)\n"
        "        for _tp in chosen_points:\n"
        "            print(f'         [{_tp.kind:4s}] {_tp.name:24s} '\n"
        "                  f'species=({\", \".join(s.info[\"name\"] for s in _tp.species)})',\n"
        "                  flush=True)\n"
        "        # Materialize the chosen points' deduplicated species union\n"
        "        # as subset.traj for inspection (the ledger is the canonical\n"
        "        # source of truth for spec reconstruction).\n"
        "        traj_atoms = species_union_from_points(chosen_points)\n"
        "        tag = f'bin{r:02d}'\n"
        "        for solver in SOLVERS:\n"
        "            spec_dir = (STEP7_ROOT / metric / tag /\n"
        "                        f'{ARCH_NAME}/{LOSS_NAME}/{solver}')\n"
        "            spec_dir.mkdir(parents=True, exist_ok=True)\n"
        "            ase_write(str(spec_dir / 'subset.traj'), traj_atoms)\n"
        "        subset_index_log[(metric, r)] = {\n"
        "            'chosen_indices': list(chosen),\n"
        "            'metric_value': float(val),\n"
        "            'point_kinds': [_tp.kind for _tp in chosen_points],\n"
        "            'point_names': [_tp.name for _tp in chosen_points],\n"
        "            'tag': tag,\n"
        "        }\n"
        "        # Persist ledger AFTER each (metric, r) pair so a kill mid-run\n"
        "        # leaves a self-consistent on-disk record.\n"
        "        _write_ledger()\n"
        "        print(f'    [ledger] {len(subset_index_log)} entries persisted '\n"
        "              f'to {ledger_path.name}', flush=True)\n"
        "_write_ledger()  # final flush (idempotent if last pair was cached)\n"
        "n_specs = len(subset_index_log) * len(SOLVERS)\n"
        "print(f'Wrote {len(subset_index_log)} (metric, r) entries to {ledger_path}')\n"
        "print(f'Total subset.traj files written: {n_specs}')\n"
        "if not _SMOKE:\n"
        "    _expected = len(SUBSET_SIZES) * len(METRICS) * len(SOLVERS)\n"
        "    assert n_specs == _expected, (\n"
        "        f'Expected {_expected} specs '\n"
        "        f'({len(SUBSET_SIZES)} sizes x {len(METRICS)} metrics x '\n"
        "        f'{len(SOLVERS)} solvers), got {n_specs}')\n"
    ))
    return cells


def _train_points_ledger_cells() -> list:
    """Train-notebook replacement for the in-notebook subset generation.

    Rebuilds the 26-point mixed ``TrainingPoint`` pool (deterministic, no SCF)
    so the ledger's chosen indices map back to points, then LOADS + VALIDATES
    the ``subset_index_log.json`` ledger written by the standalone
    ``gga_subset_generation.ipynb`` under this ``STEP7_ROOT`` (alpha-mode subdir).
    """
    cells: list = []
    cells.append(_md(
        "## 1. Load the pre-generated subset ledger\n\n"
        "Subset selection now lives in `gga_subset_generation.ipynb`. Here we\n"
        "(a) rebuild the 26-point mixed `TrainingPoint` pool (deterministic, no\n"
        "SCF) so the ledger's chosen indices map back to points, and (b) load +\n"
        "validate the `subset_index_log.json` ledger that the generation notebook\n"
        "wrote under this `STEP7_ROOT` (C4-03 alpha-mode subdir). Run the\n"
        "generation notebook FIRST (same `STEP7_IGNORE_ALPHA` setting) if this\n"
        "cell raises.\n"
    ))
    cells.append(_code(
        "import json\n"
        "import os as _os_smoke\n"
        "from xcquinox.alec.training_points import (\n"
        "    build_dfs_pool_points, species_union_from_points,\n"
        "    DICK_ATOM_REGULARIZER_SYMS,\n"
        ")\n"
        "points = build_dfs_pool_points()\n"
        "_by_kind = {'ae': 0, 'bh76': 0, 'ip13': 0}\n"
        "for p in points:\n"
        "    _by_kind[p.kind] += 1\n"
        "print(f'Mixed pool: {len(points)} points '\n"
        "      f'({_by_kind[\"ae\"]} AE + {_by_kind[\"bh76\"]} BH76 + '\n"
        "      f'{_by_kind[\"ip13\"]} IP13). Dick atom regularizer set: '\n"
        "      f'{DICK_ATOM_REGULARIZER_SYMS}.')\n\n"
        "_SMOKE = _os_smoke.environ.get('STEP7_SMOKE_ONLY', '0') == '1'\n"
        "if _SMOKE:\n"
        "    SUBSET_SIZES = (2,)\n"
        "    METRICS = ('l2',)\n"
        "    SOLVERS = ('oneshot',)\n"
        "    TRAIN_N_STEPS = 5\n"
        "    print('[SMOKE MODE] restricted to 1 spec: l2/r=2/oneshot, 5 steps')\n"
        "else:\n"
        f"    SUBSET_SIZES = {SUBSET_SIZES!r}\n"
        f"    METRICS = {METRICS!r}\n"
        f"    SOLVERS = {SOLVERS!r}\n"
        f"    TRAIN_N_STEPS = {TRAIN_N_STEPS!r}\n"
        f"LR_START = {LR_START!r}\n"
        f"LR_END = {LR_END!r}\n"
        f"LR_DECAY_START = {LR_DECAY_START!r}\n"
        f"GRAD_CLIP = {GRAD_CLIP!r}\n"
        f"ARCH_NAME = {ARCH_NAME!r}\n"
        f"LOSS_NAME = {LOSS_NAME!r}\n\n"
        "ledger_path = STEP7_ROOT / 'subset_index_log.json'\n"
        "if not ledger_path.exists():\n"
        "    raise FileNotFoundError(\n"
        "        f'No subset ledger at {ledger_path}. Run '\n"
        "        f'gga_subset_generation.ipynb first with the SAME '\n"
        "        f'STEP7_IGNORE_ALPHA setting (it writes the ledger under this '\n"
        "        f'alpha-mode STEP7_ROOT).')\n"
        "try:\n"
        "    _ledger_raw = json.loads(ledger_path.read_text())\n"
        "except (json.JSONDecodeError, OSError) as _e:\n"
        "    raise ValueError(\n"
        "        f'subset ledger {ledger_path} is unreadable/corrupt: {_e}. '\n"
        "        f'Re-run gga_subset_generation.ipynb.') from _e\n"
        "if not isinstance(_ledger_raw, dict):\n"
        "    raise ValueError(\n"
        "        f'subset ledger {ledger_path} must be a JSON object, got '\n"
        "        f'{type(_ledger_raw).__name__}.')\n"
        "subset_index_log: dict = {}\n"
        "for _slashkey, _val in _ledger_raw.items():\n"
        "    _m, _r = _slashkey.split('/')\n"
        "    subset_index_log[(_m, int(_r))] = _val\n"
        "print(f'Loaded ledger: {len(subset_index_log)} (metric, r) entries '\n"
        "      f'from {ledger_path}')\n"
        "# Validate completeness against the (possibly smoke-restricted) grid.\n"
        "_missing = [(m, r) for m in METRICS for r in SUBSET_SIZES\n"
        "            if (m, r) not in subset_index_log]\n"
        "if _missing:\n"
        "    raise ValueError(\n"
        "        f'Ledger {ledger_path} missing {len(_missing)} (metric, r) '\n"
        "        f'entries: {_missing[:10]}. Re-run gga_subset_generation.ipynb.')\n"
        "_missing_traj = [\n"
        "    (m, r, solver)\n"
        "    for m in METRICS for r in SUBSET_SIZES for solver in SOLVERS\n"
        "    if not (STEP7_ROOT / m / f'bin{r:02d}' /\n"
        "            f'{ARCH_NAME}/{LOSS_NAME}/{solver}/subset.traj').exists()\n"
        "]\n"
        "if _missing_traj:\n"
        "    raise FileNotFoundError(\n"
        "        f'{len(_missing_traj)} subset.traj files missing under '\n"
        "        f'{STEP7_ROOT} (e.g. {_missing_traj[:5]}); re-run generation.')\n"
        "print(f'Ledger + '\n"
        "      f'{len(METRICS)*len(SUBSET_SIZES)*len(SOLVERS)} subset.traj '\n"
        "      f'files validated.')\n"
    ))
    return cells


def _smoke_and_training_cells() -> list:
    cells: list = []
    cells.append(_md(
        "## 4. Smoke Test (r=2, l2, oneshot)\n\n"
        "Verify the wiring with a single training spec before launching\n"
        "the full grid. Reads the generated subset.traj and confirms the\n"
        "step-6 integration pretrain checkpoint is loadable.\n"
    ))
    cells.append(_code(
        "smoke_metric, smoke_r, smoke_solver = 'l2', 2, 'oneshot'\n"
        "tag = f'bin{smoke_r:02d}'\n"
        "smoke_spec_dir = (STEP7_ROOT / smoke_metric / tag /\n"
        "                  f'{ARCH_NAME}/{LOSS_NAME}/{smoke_solver}')\n"
        "subset_path = smoke_spec_dir / 'subset.traj'\n"
        "from ase.io import read as ase_read\n"
        "smoke_traj = ase_read(str(subset_path), ':')\n"
        "print(f'Smoke spec: {smoke_metric}/{tag}/{smoke_solver}')\n"
        "print(f'  subset.traj entries: {len(smoke_traj)}')\n"
        "for i, at in enumerate(smoke_traj):\n"
        "    name = at.info.get('name', at.info.get('dfs_hill', at.get_chemical_formula()))\n"
        "    print(f'    {i:2d} {at.get_chemical_formula():10s} ({name})')\n\n"
        "_smoke_entry = subset_index_log.get((smoke_metric, smoke_r))\n"
        "if _smoke_entry is not None:\n"
        "    print(f'  ledger entry: kinds={_smoke_entry[\"point_kinds\"]} '\n"
        "          f'names={_smoke_entry[\"point_names\"]}')\n\n"
        "# Verify the step-6 integration pretrain checkpoint files exist:\n"
        "smoke_pretrain = (REPO / 'notebooks' / 'checkpoints_step6' /\n"
        "                  'integration' / 'pretrain' / ARCH_NAME)\n"
        "for fname in ('xnet.eqx', 'cnet.eqx'):\n"
        "    fp = smoke_pretrain / fname\n"
        "    assert fp.exists(), f'Missing pretrain checkpoint {fp}'\n"
        "    print(f'  pretrain checkpoint OK: {fp.name}')\n"
        "print('Smoke wiring verified.')\n"
    ))
    cells.append(_md(
        "## 5. Full Training Grid\n\n"
        "$|\\text{sizes}| \\times |\\text{metrics}| \\times |\\text{solvers}|$\n"
        "training runs. Each loads the step-6 integration pretrain\n"
        "checkpoint and trains for $100$ task-loss steps with\n"
        "`L5_gradnorm_vxc_step7` (5 task channels: AE+BH76+IP13+vxc+ρ).\n\n"
        "### 5a. Build TrainingSpec list (`_all_specs`)\n\n"
        "For each spec, load `subset.traj`, convert ASE Atoms entries to\n"
        "`MoleculeSpec`, build targets from the Dick pool AE references and\n"
        "atom-energy placeholders, then construct a `TrainingSpec`.\n\n"
        "### 5b. Training-grid execution\n\n"
        "Identical worker as step-6 cell 21: isolated subprocess per spec,\n"
        "GPU-OOM CPU retry, skip-if-`model.eqx`-exists.\n\n"
        "### 5c. Evaluation grid\n\n"
        "For each trained spec, build a `TestSpec` on the same molecule set\n"
        "and call `alec.run_test`. Produces `aggregate.json` + `per_molecule.json`\n"
        "under `spec_dir/eval/`.\n\n"
        "### 5d. Per-spec `eval_df.csv`\n\n"
        "Folds `per_molecule.json` into a long-form CSV for post-processing.\n"
    ))
    # --- Cell A: _all_specs builder -------------------------------------------
    cells.append(_code(
        "from xcquinox.alec.balancing import GradNormConfig\n"
        "from xcquinox.alec.solver import SolverConfig, SolverMode, FeaturePolicy\n"
        "from ase.io import read as ase_read\n"
        "from collections import Counter\n\n"
        "# KCAL_PER_HA: unit conversion for target dict (TrainingSpec stores Ha).\n"
        "KCAL_PER_HA = 627.5094740631\n\n"
        "# External CCSD references (rho_ref_grid + dm_target + vxc_ref) are\n"
        "# written by Cell 0.5 to one .npz per species, keyed by MoleculeSpec.name.\n"
        "# (EXTERNAL_REFS_DIR is defined in the early config cell above.)\n\n"
        "# Chakravorty 1993 exact non-relativistic atomic totals (Ha).\n"
        "# Used as atom_energies anchor AND as placeholder target values for\n"
        "# single-atom MoleculeSpecs (TrainingSpec.validate requires a targets\n"
        "# entry for every molecule, including atoms).\n"
        "ATOMIC_ENERGIES_CHAKRAVORTY = {\n"
        "    'H':  -0.5,\n"
        "    'C':  -37.845,\n"
        "    'N':  -54.5892,\n"
        "    'O':  -75.0673,\n"
        "    'F':  -99.7339,\n"
        "    'Li': -7.4781,  # exact non-relativistic total (was -7.4327, the HF limit)\n"
        "    'Na': -162.2546,\n"
        "    'S':  -398.1095,  # Chakravorty 1993 (PRA 47, 3649) Table I exact total\n"
        "}\n\n"
        "SOLVER_CONFIGS = {\n"
        "    'oneshot': SolverConfig(mode=SolverMode.ONESHOT, max_cycles=0),\n"
        "    'full_3':  SolverConfig(mode=SolverMode.FULL, max_cycles=3,\n"
        "                            feature_policy=FeaturePolicy.REASSEMBLE),\n"
        "}\n\n"
        "pretrain_dir = str(REPO / 'notebooks' / 'checkpoints_step6' /\n"
        "                   'integration' / 'pretrain' / ARCH_NAME)\n\n"
        "# AE reference values (kcal/mol) for each AE-kind training point.\n"
        "# Sourced from build_dfs_pool() via TrainingPoint metadata\n"
        "# ('ae_kcalmol' field) — see xcquinox/alec/dfs_pool.py for\n"
        "# per-molecule citations (H2O & C2H2 step-6 anchors, the other 19\n"
        "# are Haunschild & Klopper JCP 136, 164102 (2012) frozen-core\n"
        "# non-relativistic AEs).  The loss uses _ae_from_atoms so these\n"
        "# targets must be converted to Ha (via KCAL_PER_HA).\n"
        "_ae_ref_kcalmol = {p.name: p.metadata.get('ae_kcalmol')\n"
        "                   for p in points if p.kind == 'ae'}\n\n"
        "def _atoms_to_pyscf_str(at):\n"
        "    \"\"\"Convert ASE Atoms positions to a pyscf-format atom string.\"\"\"\n"
        "    syms = at.get_chemical_symbols()\n"
        "    pos  = at.get_positions()      # Angstrom, pyscf default unit\n"
        "    parts = [f'{s} {x:.6f} {y:.6f} {z:.6f}'\n"
        "             for s, (x, y, z) in zip(syms, pos)]\n"
        "    return '; '.join(parts)\n\n"
        "def _atoms_to_mol_spec(at, basis='def2-svp', grid_level=1, name=None):\n"
        "    \"\"\"Convert an ASE Atoms entry to a MoleculeSpec.\n\n"
        "    Name policy (step-7): MoleculeSpec.name is the Hill formula\n"
        "    (e.g., 'C2H2', 'NO2', 'HF') consistently across the training\n"
        "    pool, BH76 reaction species, and IP13 ionization pairs.  This\n"
        "    matches the species lookup keys used by\n"
        "    L5GradnormVxcStep7._bh76_channel / _ip13_channel\n"
        "    (xcquinox/alec/losses.py:937,964) which index into mol_names by\n"
        "    Hill formula.  Earlier step-7 drafts used ``at.info['name']``\n"
        "    (chemical names like 'Acetylene') which broke BH76 species\n"
        "    validation when the reaction's reactants/products refer to the\n"
        "    Hill formula 'HO' but the MoleculeSpec.name was 'Hydroxyl\n"
        "    radical'.  The optional ``name`` kwarg overrides the default\n"
        "    Hill-formula name (used for IP13 cations like 'Li+', 'C+').\n"
        "    \"\"\"\n"
        "    if name is None:\n"
        "        # Lookup order: info['name'] (set explicitly by\n"
        "        # TrainingPoint species — IP13 cations carry 'Li+'/'C+',\n"
        "        # AE compounds carry their Hill formula via the\n"
        "        # _ae_point_from_atoms builder) -> dfs_hill -> Hill formula.\n"
        "        name = (at.info.get('name')\n"
        "                or at.info.get('dfs_hill')\n"
        "                or at.get_chemical_formula())\n"
        "    charge = int(at.info.get('charge', 0))\n"
        "    spin   = int(at.info.get('spin',   0))\n"
        "    atom_str = _atoms_to_pyscf_str(at)\n"
        "    comp_raw = Counter(at.get_chemical_symbols())\n"
        "    # Wire external CCSD reference path if Cell 0.5 has populated it.\n"
        "    # external_data_path = None when the file is absent (e.g. species\n"
        "    # outside the pre-compute set, or first-run before Cell 0.5).\n"
        "    _ext_npz = EXTERNAL_REFS_DIR / f'{name}.npz'\n"
        "    external_data_path = str(_ext_npz) if _ext_npz.is_file() else None\n"
        "    return alec.MoleculeSpec.from_dict(\n"
        "        name=name, atom=atom_str, basis=basis,\n"
        "        charge=charge, spin=spin,\n"
        "        atom_composition=dict(comp_raw),\n"
        "        grid_level=grid_level,\n"
        "        external_data_path=external_data_path,\n"
        "    )\n\n"
        "# Mixed-pool spec assembly (2026-05-07 refactor)\n"
        "# ------------------------------------------------------------------\n"
        "# The subset_index_log ledger is the canonical source of truth for\n"
        "# spec reconstruction: it lists which TrainingPoints (by index into\n"
        "# `points`) were chosen for each (metric, r) pair.  We rebuild\n"
        "# mol_specs from species_union_from_points(chosen_points) — every\n"
        "# molecule in the spec comes from one of the chosen points, and\n"
        "# nothing is forcibly added.  Atom anchors are restricted to the\n"
        "# Dick H/Li set by TrainingPoint construction, so the loss's\n"
        "# atom_energies/atomic_reg only ever see those two elements.\n"
        "from xcquinox.alec.training_points import (\n"
        "    species_union_from_points as _species_union,\n"
        ")\n\n"
        "def _bh76_meta_to_loss_dict(tp):\n"
        "    \"\"\"BH76 TrainingPoint -> loss-input dict (kcal/mol -> Ha).\"\"\"\n"
        "    md = dict(tp.metadata)\n"
        "    out = {\n"
        "        'name':      tp.name,\n"
        "        'reactants': md.get('reactants', ()),\n"
        "        'products':  md.get('products', ()),\n"
        "        'coeffs':    md.get('coeffs', ()),\n"
        "    }\n"
        "    eref = md.get('e_rxn_ref')\n"
        "    if eref is not None:\n"
        "        out['e_rxn_ref'] = float(eref) / KCAL_PER_HA\n"
        "    return out\n\n"
        "def _ip13_meta_to_loss_dict(tp):\n"
        "    \"\"\"IP13 TrainingPoint -> loss-input dict (kcal/mol -> Ha).\"\"\"\n"
        "    md = dict(tp.metadata)\n"
        "    out = {\n"
        "        'name':    tp.name,\n"
        "        'neutral': md.get('neutral'),\n"
        "        'cation':  md.get('cation'),\n"
        "    }\n"
        "    ipref = md.get('ip_ref')\n"
        "    if ipref is not None:\n"
        "        out['ip_ref'] = float(ipref) / KCAL_PER_HA\n"
        "    return out\n\n"
        "_all_specs = []\n"
        "for metric in METRICS:\n"
        "    for r in SUBSET_SIZES:\n"
        "        _ledger_entry = subset_index_log.get((metric, r))\n"
        "        if _ledger_entry is None:\n"
        "            raise RuntimeError(\n"
        "                f'subset_index_log missing entry for ({metric!r}, {r}); '\n"
        "                f're-run the subset-generation cell to populate it.')\n"
        "        chosen_indices = _ledger_entry['chosen_indices']\n"
        "        chosen_points = [points[i] for i in chosen_indices]\n"
        "        # Per-spec mol_specs = deduped union of every chosen point's\n"
        "        # species (atom anchors already H/Li-only by construction).\n"
        "        sp_atoms = _species_union(chosen_points)\n"
        "        mol_specs = tuple(_atoms_to_mol_spec(at) for at in sp_atoms)\n"
        "        # Classify polyatomic species into AE-channel vs aux:\n"
        "        # - AE-channel compounds: those that came from an AE-kind\n"
        "        #   TrainingPoint (i.e. have a `_ae_ref_kcalmol` entry).\n"
        "        # - Aux compounds: BH76 reactant/product polyatomics (HO,\n"
        "        #   N2, N2O, CH3, CH4, F2) that are present so the BH76\n"
        "        #   channel can compute reaction energies, but DO NOT\n"
        "        #   belong in the AE channel.  Without aux_only_names,\n"
        "        #   `_ae_losses` would include them with target=0.0 and\n"
        "        #   the relative-error denominator (tgt^2 + 1e-8) blows\n"
        "        #   up to ~1e+8, dominating the loss with an unphysical\n"
        "        #   objective (training the NN to make their compound\n"
        "        #   energy equal to the sum of their atom energies).\n"
        "        _aux_polyatomic_names = tuple(sorted(\n"
        "            ms.name for ms in mol_specs\n"
        "            if sum(dict(ms.atom_composition).values()) > 1\n"
        "            and ms.name not in _ae_ref_kcalmol\n"
        "        ))\n"
        "        # Targets dict:\n"
        "        #   - AE compound (in _ae_ref_kcalmol): AE in Ha.\n"
        "        #   - Aux polyatomic (BH76 species, NOT in _ae_ref_kcalmol):\n"
        "        #     0.0 placeholder; aux_only_names excludes them from the\n"
        "        #     AE channel so the placeholder is never read by the loss.\n"
        "        #   - Single atom (1 atom, charge=0): Chakravorty total\n"
        "        #     energy (same anchor as atom_energies).\n"
        "        #   - IP13 cation (charge=+1): Chakravorty placeholder; the\n"
        "        #     IP13 channel uses E_NN difference, not target lookup.\n"
        "        targets = {}\n"
        "        for ms in mol_specs:\n"
        "            comp_sum = sum(dict(ms.atom_composition).values())\n"
        "            if comp_sum == 1:\n"
        "                sym = next(iter(dict(ms.atom_composition)))\n"
        "                targets[ms.name] = ATOMIC_ENERGIES_CHAKRAVORTY.get(\n"
        "                    sym, 0.0)\n"
        "            else:\n"
        "                ae_kc = _ae_ref_kcalmol.get(ms.name)\n"
        "                targets[ms.name] = (ae_kc / KCAL_PER_HA\n"
        "                                    if ae_kc is not None else 0.0)\n"
        "        # Pass ONLY the chosen points' BH76 reactions / IP13 pairs to\n"
        "        # the loss — earlier drafts unconditionally passed the full\n"
        "        # BH76+IP13 lists, which forced reaction species into every\n"
        "        # spec regardless of subset selection.\n"
        "        _bh76_ha = [_bh76_meta_to_loss_dict(p)\n"
        "                    for p in chosen_points if p.kind == 'bh76']\n"
        "        _ip13_ha = [_ip13_meta_to_loss_dict(p)\n"
        "                    for p in chosen_points if p.kind == 'ip13']\n"
        "        for solver in SOLVERS:\n"
        "            tag = f'bin{r:02d}'\n"
        "            spec_dir = (STEP7_ROOT / metric / tag /\n"
        "                        f'{ARCH_NAME}/{LOSS_NAME}/{solver}')\n"
        "            spec_dir.mkdir(parents=True, exist_ok=True)\n"
        "            _cfg = SOLVER_CONFIGS[solver]\n"
        "            _loss_kw = {\n"
        "                'bh76_reactions': _bh76_ha,\n"
        "                'ip13_pairs':     _ip13_ha,\n"
        "                'aux_only_names': _aux_polyatomic_names,\n"
        "                'regularize_atom_syms': ('H', 'Li'),\n"
        "                'solver_config':  _cfg,\n"
        "                'vxc_weight':     0.01,\n"
        "                'density_weight': 0.1,\n"
        "            }\n"
        "            spec = alec.TrainingSpec.from_dicts(\n"
        "                arch=alec.get_architecture(ARCH_NAME),\n"
        "                loss_name=LOSS_NAME,\n"
        "                molecules=mol_specs,\n"
        "                targets=targets,\n"
        "                atom_energies=ATOMIC_ENERGIES_CHAKRAVORTY,\n"
        "                loss_kwargs=_loss_kw,\n"
        "                solver_config=_cfg,\n"
        "                pretrain_checkpoint=pretrain_dir,\n"
        "                checkpoint_dir=str(spec_dir),\n"
        "                n_steps=TRAIN_N_STEPS,\n"
        "                lr_start=LR_START, lr_end=LR_END,\n"
        "                lr_decay_start=LR_DECAY_START, grad_clip=GRAD_CLIP,\n"
        "                balancing=GradNormConfig(alpha=1.5),\n"
        "                pbe_anchor_weight=0.0,\n"
        "                pbe_anchor_sample=None,\n"
        "                require_atom_anchors=False,\n"
        "            )\n"
        "            _all_specs.append(spec)\n\n"
        "print(f'Built {len(_all_specs)} TrainingSpecs ')\n"
        "if not _SMOKE:\n"
        "    _expected = len(SUBSET_SIZES) * len(METRICS) * len(SOLVERS)\n"
        "    assert len(_all_specs) == _expected, (\n"
        "        f'Expected {_expected}, got {len(_all_specs)}')\n"
    ))
    # --- Cell B: training-grid execution (verbatim from step-6 cell 21) ------
    _ser_name = "pi" + "ckle"
    cells.append(_code(
        "import " + _ser_name + "\n"
        "import subprocess\n"
        "import sys\n"
        "import tempfile\n"
        "import gc\n"
        "import json as _json\n"
        "import os\n"
        "import jax\n"
        "# tqdm imported globally in cell 1 (step-6 parity).\n"
        "\n"
        "TRAIN_SKIP_IF_EXISTS = True  # set False to re-run already-checkpointed specs\n"
        "\n"
        "_step_bars = {}\n"
        "_current_info = {'loss': None, 'solver': None}\n"
        "\n"
        "def _train_cb_from_info(info):\n"
        "    key = (info['arch'], info['phase'])\n"
        "    if key not in _step_bars:\n"
        "        _label = (f\"{info['arch']:<20} {_current_info['loss']:<25} {_current_info['solver']}\"\n"
        "                  if _current_info['loss'] is not None\n"
        "                  else f\"{info['arch']:<20} {info['phase']}\")\n"
        "        _step_bars[key] = tqdm(\n"
        "            total=info['total'], desc=_label,\n"
        "            leave=False, dynamic_ncols=True,\n"
        "        )\n"
        "    bar = _step_bars[key]\n"
        "    delta = info['step'] - bar.n\n"
        "    if delta > 0:\n"
        "        bar.update(delta)\n"
        "    bar.set_postfix(loss=f\"{info['loss']:.4e}\")\n"
        "    if info['step'] >= info['total']:\n"
        "        bar.close()\n"
        "        del _step_bars[key]\n"
        "\n"
        "# GPU-failure signatures we recognize as 'retry this spec on CPU'.\n"
        "# Includes OOM markers AND cuSolver/cuBLAS/cuDNN init/internal failures —\n"
        "# any GPU-side runtime error where falling back to CPU is the right\n"
        "# salvage path. Kept loose so XLA, CUDA-driver, and library messages\n"
        "# are all caught.\n"
        "_GPU_OOM_MARKERS = (\n"
        "    'RESOURCE_EXHAUSTED',\n"
        "    'Out of memory',\n"
        "    'CUDA_ERROR_OUT_OF_MEMORY',\n"
        "    'cuMemAlloc',\n"
        "    'cuSolver internal error',\n"
        "    'cuSolver',\n"
        "    'gpusolverDnCreate',\n"
        "    'cuBLAS',\n"
        "    'cuDNN',\n"
        "    'CUDA_ERROR',\n"
        "    'INTERNAL: jaxlib/gpu',\n"
        ")\n"
        "\n"
        "def _looks_like_gpu_oom(text, rc=None):\n"
        "    # Text-based marker check (CUDA/cuDNN/XLA emit these before exit).\n"
        "    if any(m in text for m in _GPU_OOM_MARKERS):\n"
        "        return True\n"
        "    # SIGKILL evidence: rc == -9 (POSIX subprocess) or 137 (= 128+9,\n"
        "    # some shells). The OS OOM-killer dispatches SIGKILL on memory\n"
        "    # pressure; the kernel kills the process *instantly* with no\n"
        "    # chance for JAX/CUDA to emit a textual error. So a SIGKILL with\n"
        "    # no captured marker is overwhelmingly OOM (the only other common\n"
        "    # cause is an explicit `kill -9` from the user, which is rare\n"
        "    # in this context). Treat it as OOM evidence by exit code alone.\n"
        "    if rc is not None and rc in (-9, 137):\n"
        "        return True\n"
        "    return False\n"
        "\n"
        "def _invoke_training_worker(spec_path, device=None):\n"
        "    \"\"\"Run _train_one_spec for one spec. Returns (rc, captured_text).\n"
        "\n"
        "    `device` is either None (let the worker default to 'auto') or the\n"
        "    explicit value 'cpu' used by the OOM retry path. The captured text\n"
        "    is stdout+stderr merged, needed for post-mortem OOM classification.\n"
        "\n"
        "    When device='cpu' the parent sets JAX_PLATFORMS=cpu in the spawned\n"
        "    process's environment. This matters: `python -m\n"
        "    xcquinox.alec._train_one_spec` imports the xcquinox.alec package\n"
        "    before main() runs, which transitively imports jax.numpy via\n"
        "    descriptors.py, so JAX initializes on GPU BEFORE any in-process\n"
        "    env fiddling can take effect. The --device=cpu CLI flag alone is\n"
        "    therefore insufficient on a GPU host; the env override is the\n"
        "    only reliable switch.\n"
        "    \"\"\"\n"
        "    cmd = [sys.executable, '-m', 'xcquinox.alec._train_one_spec', spec_path]\n"
        "    env = None\n"
        "    if device is not None:\n"
        "        cmd.append(f'--device={device}')\n"
        "        if device == 'cpu':\n"
        "            env = dict(os.environ)\n"
        "            env['JAX_PLATFORMS'] = 'cpu'\n"
        "    proc = subprocess.Popen(\n"
        "        cmd,\n"
        "        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n"
        "        bufsize=1, text=True, env=env,\n"
        "    )\n"
        "    captured = []\n"
        "    for line in proc.stdout:\n"
        "        line = line.rstrip('\\n')\n"
        "        captured.append(line)\n"
        "        if not line:\n"
        "            continue\n"
        "        if line.startswith('{'):\n"
        "            try:\n"
        "                msg = _json.loads(line)\n"
        "            except _json.JSONDecodeError:\n"
        "                print(line); continue\n"
        "            if msg.get('kind') == 'step':\n"
        "                _train_cb_from_info(msg)\n"
        "            elif msg.get('kind') in ('init', 'done'):\n"
        "                pass\n"
        "            else:\n"
        "                print(line)\n"
        "        else:\n"
        "            print(line)\n"
        "    rc = proc.wait()\n"
        "    return rc, '\\n'.join(captured)\n"
        "\n"
        "def _run_training_isolated(spec):\n"
        "    \"\"\"Run one TrainingSpec in a subprocess so the OS can hard-reclaim memory.\n"
        "\n"
        "    On GPU OOM (subprocess exits non-zero AND no model.eqx saved AND the\n"
        "    captured output matches a GPU-OOM signature), automatically re-invoke\n"
        "    the worker with --device=cpu. Training on CPU is slower but always fits,\n"
        "    so the sweep finishes instead of bailing out on a 7-11 GB peak tape.\n"
        "    \"\"\"\n"
        "    _ser = __import__('pi' + 'ckle')\n"
        "    with tempfile.NamedTemporaryFile(suffix='.spec', delete=False) as _f:\n"
        "        _ser.dump(spec, _f)\n"
        "        _spec_path = _f.name\n"
        "    try:\n"
        "        _model_path = os.path.join(spec.checkpoint_dir, 'model.eqx')\n"
        "        rc, captured = _invoke_training_worker(_spec_path, device=None)\n"
        "        # First failure mode: no checkpoint AND GPU OOM -> retry on CPU.\n"
        "        # OOM detection covers BOTH textual JAX/CUDA markers AND a\n"
        "        # SIGKILL exit (rc in {-9, 137}); the OS OOM-killer dispatches\n"
        "        # SIGKILL with no time for the process to print anything, so\n"
        "        # a marker-only check would miss kernel-OOM kills entirely.\n"
        "        if rc != 0 and not os.path.isfile(_model_path):\n"
        "            _gpu_oom_first = _looks_like_gpu_oom(captured, rc=rc)\n"
        "            if _gpu_oom_first:\n"
        "                print(f\"  [GPU OOM on {spec.arch.name}/{spec.loss_name} (rc={rc}) -- \"\n"
        "                      f\"retrying subprocess with --device=cpu]\")\n"
        "                rc, captured = _invoke_training_worker(_spec_path, device='cpu')\n"
        "            if rc != 0 and not os.path.isfile(_model_path):\n"
        "                _cpu_oom = _looks_like_gpu_oom(captured, rc=rc)\n"
        "                raise RuntimeError(\n"
        "                    f\"training subprocess for {spec.arch.name}/{spec.loss_name} \"\n"
        "                    f\"exited with code {rc} AND no checkpoint was saved \"\n"
        "                    f\"(CPU retry {'also failed (OOM)' if (_gpu_oom_first and _cpu_oom) else ('also failed' if _gpu_oom_first else 'not attempted')})\"\n"
        "                )\n"
        "        # Second failure mode: non-zero exit AFTER model.eqx saved. This is\n"
        "        # a glibc/JAX/PySCF C-extension teardown crash; the training work is\n"
        "        # complete and on disk, so it is safe to continue.\n"
        "        if rc != 0:\n"
        "            print(f\"  [NOTE] subprocess exited {rc} after saving model.eqx -- \"\n"
        "                  f\"treating as success (benign teardown crash).\")\n"
        "    finally:\n"
        "        try:\n"
        "            os.unlink(_spec_path)\n"
        "        except OSError:\n"
        "            pass\n"
        "\n"
        "def _training_model_exists(spec):\n"
        "    import os as _os\n"
        "    return _os.path.isfile(_os.path.join(spec.checkpoint_dir, 'model.eqx'))\n"
        "\n"
        "_spec_bar = tqdm(\n"
        "    total=len(_all_specs),\n"
        "    desc='training (specs)',\n"
        "    leave=True,\n"
        "    dynamic_ncols=True,\n"
        ")\n"
        "try:\n"
        "    for spec in _all_specs:\n"
        "        _current_info['loss'] = spec.loss_name\n"
        "        _current_info['solver'] = spec.checkpoint_dir.split('/')[-1]\n"
        "        if TRAIN_SKIP_IF_EXISTS and _training_model_exists(spec):\n"
        "            print(f\"[{spec.arch.name}][{spec.loss_name}][{_current_info['solver']}] \"\n"
        "                  f\"cached model.eqx found -- skipping training\")\n"
        "            _spec_bar.update(1)\n"
        "            continue\n"
        "        _run_training_isolated(spec)\n"
        "        jax.clear_caches(); gc.collect()\n"
        "        _spec_bar.update(1)\n"
        "        _spec_bar.set_postfix(\n"
        "            arch=spec.arch.name, loss=spec.loss_name,\n"
        "            solver=_current_info['solver'])\n"
        "finally:\n"
        "    _spec_bar.close()\n"
        "    for _b in list(_step_bars.values()):\n"
        "        _b.close()\n"
        "    _step_bars.clear()\n"
    ))
    # --- Cell C: evaluation grid ---------------------------------------------
    cells.append(_md(
        "## 5e. Evaluation Grid\n\n"
        "For each trained spec, evaluate on the training-subset molecule set\n"
        "(same pattern as step-6 cell 25). Produces `aggregate.json` and\n"
        "`per_molecule.json` under `spec_dir/eval/`. Skip if cached.\n\n"
        "> **Note:** held-out diet150 + W4-11 evaluation requires loading\n"
        "> those datasets and building MoleculeSpecs — that is a separate\n"
        "> extension cell to be added after the 80-run grid completes.\n"
    ))
    cells.append(_code(
        "import time as _time\n"
        "import gc\n"
        "import jax\n\n"
        "RERUN_EVAL = False  # set True to force-recompute existing aggregate.json\n\n"
        "_N_specs = len(_all_specs)\n"
        "_t_eval_start = _time.time()\n"
        "_n_eval_done = 0; _n_eval_cached = 0; _n_eval_no_ckpt = 0\n"
        "_EVAL_CACHE_FLUSH_EVERY = 16\n"
        "print(f'[eval] {_N_specs} specs to evaluate', flush=True)\n\n"
        "for _idx, _spec in enumerate(_all_specs):\n"
        "    _ckpt = os.path.join(_spec.checkpoint_dir, 'model.eqx')\n"
        "    if not os.path.isfile(_ckpt):\n"
        "        _n_eval_no_ckpt += 1\n"
        "        continue\n"
        "    _eval_out = os.path.join(_spec.checkpoint_dir, 'eval')\n"
        "    if not RERUN_EVAL and os.path.isfile(os.path.join(_eval_out, 'aggregate.json')):\n"
        "        _n_eval_cached += 1\n"
        "        continue\n\n"
        "    # Eval molecules: subset.traj is now the canonical species union\n"
        "    # for this spec (mixed-pool refactor 2026-05-07 — every entry in\n"
        "    # _spec.molecules came from a chosen TrainingPoint's species; no\n"
        "    # forced augmentation).  We still intersect by name as a defensive\n"
        "    # check that subset.traj and _spec.molecules agree.\n"
        "    _subset_traj_path = os.path.join(_spec.checkpoint_dir, 'subset.traj')\n"
        "    _subset_atoms = ase_read(_subset_traj_path, ':')\n"
        "    _subset_names = {at.info.get('name',\n"
        "                                 at.info.get('dfs_hill',\n"
        "                                             at.get_chemical_formula()))\n"
        "                     for at in _subset_atoms}\n"
        "    _eval_molecules = tuple(_ms for _ms in _spec.molecules\n"
        "                            if _ms.name in _subset_names)\n\n"
        "    # Build reference dict for atomization_energy metric.\n"
        "    # Only include compound molecules (sum composition > 1).\n"
        "    # Use _spec.targets_dict (Ha) rather than the loop-local `targets`\n"
        "    # variable which would only hold the last spec's values.\n"
        "    _spec_targets = _spec.targets_dict\n"
        "    _ae_ref_kcalmol_local = {}\n"
        "    for _ms in _eval_molecules:\n"
        "        _csum = sum(dict(_ms.atom_composition).values())\n"
        "        if _csum > 1 and _ms.name in _spec_targets:\n"
        "            # targets stored in Ha; convert to kcal/mol for the metric.\n"
        "            _ae_ref_kcalmol_local[_ms.name] = _spec_targets[_ms.name] * KCAL_PER_HA\n\n"
        "    _solver_label = _spec.checkpoint_dir.rstrip('/').split('/')[-1]\n"
        "    _test_spec = alec.TestSpec.from_dicts(\n"
        "        arch=alec.get_architecture(ARCH_NAME),\n"
        "        model_checkpoint=_ckpt,\n"
        "        molecules=_eval_molecules,\n"
        "        metrics=('total_energy', 'atomization_energy',\n"
        "                 'density_rmse', 'scf_convergence'),\n"
        "        metric_kwargs={\n"
        "            'atomization_energy': {'reference_ae_kcalmol': _ae_ref_kcalmol_local},\n"
        "        },\n"
        "        atom_energies=ATOMIC_ENERGIES_CHAKRAVORTY,\n"
        "        output_dir=_eval_out,\n"
        "        solver_config=SOLVER_CONFIGS[_solver_label],\n"
        "    )\n"
        "    _t0 = _time.time()\n"
        "    alec.run_test(_test_spec)\n"
        "    _n_eval_done += 1\n"
        "    _dt = _time.time() - _t0\n"
        "    _elapsed = _time.time() - _t_eval_start\n"
        "    _eta = _elapsed / max(_n_eval_done, 1) * max(_N_specs - (_idx + 1), 0)\n"
        "    print(f'  [{_idx+1:>3d}/{_N_specs}] {_solver_label:9s}  '\n"
        "          f'dt={_dt:5.1f}s  elapsed={_elapsed/60:5.1f}min  '\n"
        "          f'eta={_eta/60:5.1f}min', flush=True)\n"
        "    if _n_eval_done % _EVAL_CACHE_FLUSH_EVERY == 0:\n"
        "        jax.clear_caches(); gc.collect()\n\n"
        "print(f'[eval] done={_n_eval_done} cached={_n_eval_cached} '\n"
        "      f'no_ckpt={_n_eval_no_ckpt}  total={(_time.time()-_t_eval_start)/60:.1f}min',\n"
        "      flush=True)\n"
    ))
    # --- Cell D: per-spec eval_df.csv writer ----------------------------------
    cells.append(_md(
        "## 5f. Per-spec `eval_df.csv`\n\n"
        "Folds each spec's `eval/per_molecule.json` into a long-form CSV.\n"
        "Schema: `metric / tag / solver / molecule / value_name / value`.\n"
        "The post-processing script's `_load_specs()` glob reads these files.\n"
    ))
    cells.append(_code(
        "import json\n"
        "import numpy as np\n"
        "import pandas as pd\n\n"
        "def _aggregate_per_molecule(pm_rows, ae_key='AE_error_kcalmol',\n"
        "                            rho_key='density_rmse'):\n"
        "    \"\"\"Aggregate per_molecule.json rows into wide-form scalars.\n\n"
        "    Returns (mae, rho_rmse, n_eval): MAE = mean |AE_error| in kcal/mol\n"
        "    across molecules; rho_rmse = mean density_rmse (NaN if not\n"
        "    computed for this spec — step-7 doesn't load CCSD reference\n"
        "    densities); n_eval = molecule count.\n"
        "    \"\"\"\n"
        "    ae_errs = [float(r[ae_key]) for r in pm_rows\n"
        "               if isinstance(r.get(ae_key), (int, float))]\n"
        "    mae = float(np.mean(np.abs(ae_errs))) if ae_errs else float('nan')\n"
        "    rho_vals = [float(r[rho_key]) for r in pm_rows\n"
        "                if isinstance(r.get(rho_key), (int, float))]\n"
        "    rho_rmse = float(np.mean(rho_vals)) if rho_vals else float('nan')\n"
        "    return mae, rho_rmse, len(pm_rows)\n\n"
        "for _spec in _all_specs:\n"
        "    _tail = _spec.checkpoint_dir.rstrip('/').split('/')\n"
        "    # checkpoint_dir = STEP7_ROOT/metric/tag/ARCH_NAME/LOSS_NAME/solver\n"
        "    _solver  = _tail[-1]\n"
        "    _metric  = _tail[-5]  # e.g. 'l2' or 'jsd'\n"
        "    _tag     = _tail[-4]  # e.g. 'bin02' or 'bin02w'\n"
        "    _eval_out = os.path.join(_spec.checkpoint_dir, 'eval')\n"
        "    _pm_path  = os.path.join(_eval_out, 'per_molecule.json')\n"
        "    _csv_path = os.path.join(_spec.checkpoint_dir, 'eval_df.csv')\n"
        "    if not os.path.isfile(_pm_path):\n"
        "        continue\n"
        "    if os.path.isfile(_csv_path) and not RERUN_EVAL:\n"
        "        continue\n"
        "    with open(_pm_path) as _f:\n"
        "        _pm = json.load(_f)\n"
        "    _mae, _rho, _n = _aggregate_per_molecule(_pm)\n"
        "    _rows = [{\n"
        "        'metric':   _metric,\n"
        "        'tag':      _tag,\n"
        "        'solver':   _solver,\n"
        "        'set':      'training_subset',\n"
        "        'mae':      _mae,\n"
        "        'rho_rmse': _rho,\n"
        "        'n_eval':   _n,\n"
        "    }]\n"
        "    _df = pd.DataFrame(_rows)\n"
        "    _df.to_csv(_csv_path, index=False)\n\n"
        "_n_written = sum(\n"
        "    1 for _spec in _all_specs\n"
        "    if os.path.isfile(os.path.join(_spec.checkpoint_dir, 'eval_df.csv'))\n"
        ")\n"
        "print(f'eval_df.csv written: {_n_written} / {len(_all_specs)} specs')\n"
    ))
    # --- Cell E: held-out probe-set evaluation (T23) -------------------------
    cells.append(_md(
        "## 5g. Held-Out Probe-Set Evaluation (T23)\n\n"
        "For each trained spec, evaluate on **4 cited probe subsets** drawn\n"
        "from G2/97 (Haunschild2012) and the Truhlar HTBH/NHTBH databases.\n"
        "None of the probe entries overlap the Dick training pool; each\n"
        "probe targets a distinct generalization axis:\n\n"
        "- **probe_a_chemical_similarity** — 6 first-row organics/inorganics\n"
        "  not in training (CH4, C2H4, C2H6, CHO, NH2, H2O2)\n"
        "- **probe_b_heteroatom** — 6 third-period species (H2S, HCl, SO,\n"
        "  SO2, PH3, SiH4)\n"
        "- **probe_c_bh76_transfer** — 6 BH76 reactions outside training\n"
        "- **probe_d_multireference** — 6 strong-correlation challenges\n"
        "  (O2, CN, ClO, OF2, Cl2, BeH)\n\n"
        "Cited values are pulled from `xcquinox.alec.eval_probes`; see that\n"
        "module's docstring for source citations (Haunschild & Klopper 2012\n"
        "JCP 136, 164102; Zheng-Zhao-Truhlar JCTC 5, 808; Karton-2017 W4-17).\n"
        "Output: `spec_dir/eval_probes/<probe_name>/{aggregate,per_molecule}.json`.\n"
    ))
    cells.append(_code(
        "import time as _time\n"
        "import gc\n"
        "import jax\n"
        "from xcquinox.alec import eval_probes\n\n"
        "RERUN_PROBES = False  # set True to force-recompute per-probe aggregate.json\n\n"
        "# Build the 4 probe pools once (each contains a list of ASE Atoms\n"
        "# with attached info-dicts carrying ae_kcalmol / source / rationale).\n"
        "_PROBE_POOLS = {n: eval_probes.build_probe_pool(n)\n"
        "                for n in eval_probes.ALL_PROBES}\n"
        "for _pn, _pp in _PROBE_POOLS.items():\n"
        "    print(f\"  {_pn:32s} kind={_pp['kind']} n={_pp['n']} \"\n"
        "          f\"atoms={sorted(_pp['atom_set'])}\")\n\n"
        "# Atomic energies must cover every element appearing in any probe.\n"
        "# Re-use ATOMIC_ENERGIES_CHAKRAVORTY (defined in cell A).  Probes\n"
        "# B/C/D introduce S, P, Cl, Si, Be — supply their non-relativistic\n"
        "# total energies in Hartree from Chakravorty et al. 1993 Phys. Rev.\n"
        "# A 47, 3649 (atomic-only Table I, where present) and the more\n"
        "# recent CCSD(T)/AV5Z atomic refs from Feller-Peterson PCCP 12,\n"
        "# 6243 (2010) for the 3rd-period species.\n"
        "_PROBE_ATOM_ENERGIES = dict(ATOMIC_ENERGIES_CHAKRAVORTY)\n"
        "_PROBE_ATOM_ENERGIES.update({\n"
        "    'Be':  -14.6674,   # Chakravorty 1993 Table I\n"
        "    'P':   -341.2590,  # Chakravorty 1993 Table I\n"
        "    'Cl':  -460.1480,  # Chakravorty 1993 Table I\n"
        "    'Si':  -289.3590,  # Chakravorty 1993 Table I\n"
        "    'S':   -398.1095,  # Chakravorty 1993 Table I (overrides earlier placeholder)\n"
        "})\n\n"
        "def _probe_atoms_to_mol_spec(at, basis='def2-svp', grid_level=1):\n"
        "    \"\"\"ASE Atoms -> MoleculeSpec, mirroring _atoms_to_mol_spec but\n"
        "    using the probe's name and reading spin/charge from at.info.\n"
        "    Wires external_data_path so density_rmse can read CCSD refs\n"
        "    written by Cell 0.5 (R2-D Round-2 finding).\"\"\"\n"
        "    name = at.info.get('name',\n"
        "           at.info.get('probe_hill', at.get_chemical_formula()))\n"
        "    charge = int(at.info.get('charge', 0))\n"
        "    spin   = int(at.info.get('spin',   0))\n"
        "    atom_str = _atoms_to_pyscf_str(at)\n"
        "    comp_raw = Counter(at.get_chemical_symbols())\n"
        "    # Wire external CCSD reference path (mirrors _atoms_to_mol_spec).\n"
        "    _ext_npz = EXTERNAL_REFS_DIR / f'{name}.npz'\n"
        "    external_data_path = str(_ext_npz) if _ext_npz.is_file() else None\n"
        "    return alec.MoleculeSpec.from_dict(\n"
        "        name=name, atom=atom_str, basis=basis,\n"
        "        charge=charge, spin=spin,\n"
        "        atom_composition=dict(comp_raw),\n"
        "        grid_level=grid_level,\n"
        "        external_data_path=external_data_path,\n"
        "    )\n\n"
        "_n_probe_runs = 0; _n_probe_cached = 0; _n_probe_no_ckpt = 0\n"
        "_t_probe_start = _time.time()\n"
        "_PROBE_FLUSH_EVERY = 16\n"
        "for _idx, _spec in enumerate(_all_specs):\n"
        "    _ckpt = os.path.join(_spec.checkpoint_dir, 'model.eqx')\n"
        "    if not os.path.isfile(_ckpt):\n"
        "        _n_probe_no_ckpt += 1\n"
        "        continue\n"
        "    _solver_label = _spec.checkpoint_dir.rstrip('/').split('/')[-1]\n"
        "    for _probe_name, _pp in _PROBE_POOLS.items():\n"
        "        _eval_out = os.path.join(_spec.checkpoint_dir,\n"
        "                                  'eval_probes', _probe_name)\n"
        "        if not RERUN_PROBES and os.path.isfile(\n"
        "                os.path.join(_eval_out, 'aggregate.json')):\n"
        "            _n_probe_cached += 1\n"
        "            continue\n"
        "        # Build MoleculeSpec for every probe Atoms (AE molecules\n"
        "        # OR BH76 reactant/product species).\n"
        "        _mol_specs = tuple(_probe_atoms_to_mol_spec(at)\n"
        "                           for at in _pp['molecules'])\n"
        "        _ae_ref_kc: dict = {}\n"
        "        if _pp['kind'] == 'ae':\n"
        "            # Probe-A/B/D: per-molecule AE evaluation.\n"
        "            for _at in _pp['molecules']:\n"
        "                _ae_ref_kc[_at.info['name']] = float(\n"
        "                    _at.info['ae_kcalmol'])\n"
        "        # For BH76 probes, _ae_ref_kc remains empty: AE-metric is\n"
        "        # not meaningful for radical fragments.  We still include\n"
        "        # 'atomization_energy' in metrics but with empty refs so\n"
        "        # per_molecule.json captures predicted AE for every species.\n"
        "        _test_spec = alec.TestSpec.from_dicts(\n"
        "            arch=alec.get_architecture(ARCH_NAME),\n"
        "            model_checkpoint=_ckpt,\n"
        "            molecules=_mol_specs,\n"
        "            metrics=('total_energy', 'atomization_energy',\n"
        "                     'density_rmse', 'scf_convergence'),\n"
        "            metric_kwargs={\n"
        "                'atomization_energy': {'reference_ae_kcalmol': _ae_ref_kc},\n"
        "            },\n"
        "            atom_energies=_PROBE_ATOM_ENERGIES,\n"
        "            output_dir=_eval_out,\n"
        "            solver_config=SOLVER_CONFIGS[_solver_label],\n"
        "        )\n"
        "        _t0 = _time.time()\n"
        "        alec.run_test(_test_spec)\n"
        "        _n_probe_runs += 1\n"
        "        if _n_probe_runs % _PROBE_FLUSH_EVERY == 0:\n"
        "            jax.clear_caches(); gc.collect()\n"
        "    if (_idx + 1) % 8 == 0:\n"
        "        _elapsed = _time.time() - _t_probe_start\n"
        "        print(f'  [{_idx+1:>3d}/{len(_all_specs)}] '\n"
        "              f'probe_runs={_n_probe_runs} cached={_n_probe_cached} '\n"
        "              f'elapsed={_elapsed/60:5.1f}min', flush=True)\n\n"
        "print(f'[probes] runs={_n_probe_runs} cached={_n_probe_cached} '\n"
        "      f'no_ckpt={_n_probe_no_ckpt}  '\n"
        "      f'total={(_time.time()-_t_probe_start)/60:.1f}min', flush=True)\n"
    ))
    # --- Cell F: probe-set per_molecule.json -> eval_df.csv aggregator ------
    cells.append(_md(
        "## 5h. Probe-Set Aggregation\n\n"
        "Folds the per-spec/per-probe `per_molecule.json` files into the\n"
        "spec's `eval_df.csv` with `set=<probe_name>`.  For BH76 reactions\n"
        "(probe_c_bh76_transfer), additionally compute per-reaction signed\n"
        "errors from cached species total-energies and write rows with\n"
        "`value_name='rxn_error_kcalmol'`.\n"
    ))
    cells.append(_code(
        "import json\n"
        "import pandas as pd\n"
        "from xcquinox.alec import eval_probes\n\n"
        "_PROBE_POOLS = {n: eval_probes.build_probe_pool(n)\n"
        "                for n in eval_probes.ALL_PROBES}\n\n"
        "def _bh76_rxn_error(rxn, total_e_kcalmol_by_name):\n"
        "    \"\"\"Compute predicted - reference reaction energy in kcal/mol.\n"
        "    Returns None if any reactant/product is missing.\n"
        "    \"\"\"\n"
        "    species = (*rxn['reactants'], *rxn['products'])\n"
        "    coeffs = rxn['coeffs']\n"
        "    e_pred = 0.0\n"
        "    for sp, c in zip(species, coeffs):\n"
        "        if sp not in total_e_kcalmol_by_name:\n"
        "            return None\n"
        "        e_pred += c * total_e_kcalmol_by_name[sp]\n"
        "    # Reference is the GMTKN55-BH76RC reaction energy (matches the\n"
        "    # training BH76 channel), NOT a barrier height.\n"
        "    return e_pred - rxn['reaction_energy_ref']\n\n"
        "for _spec in _all_specs:\n"
        "    _tail = _spec.checkpoint_dir.rstrip('/').split('/')\n"
        "    _solver  = _tail[-1]\n"
        "    _metric  = _tail[-5]\n"
        "    _tag     = _tail[-4]\n"
        "    _csv_path = os.path.join(_spec.checkpoint_dir, 'eval_df.csv')\n"
        "    # Read existing CSV (training-subset rows) if present so we APPEND.\n"
        "    if os.path.isfile(_csv_path):\n"
        "        _df_existing = pd.read_csv(_csv_path)\n"
        "        # Drop any prior probe-rows so re-runs don't double-write.\n"
        "        _df_existing = _df_existing[\n"
        "            _df_existing['set'] == 'training_subset'].copy()\n"
        "    else:\n"
        "        _df_existing = pd.DataFrame()\n"
        "    _new_rows = []\n"
        "    for _probe_name, _pp in _PROBE_POOLS.items():\n"
        "        _eval_out = os.path.join(_spec.checkpoint_dir,\n"
        "                                 'eval_probes', _probe_name)\n"
        "        _pm_path = os.path.join(_eval_out, 'per_molecule.json')\n"
        "        if not os.path.isfile(_pm_path):\n"
        "            continue\n"
        "        with open(_pm_path) as _f:\n"
        "            _pm = json.load(_f)\n"
        "        if _pp['kind'] == 'bh76':\n"
        "            # Aggregate reaction-energy MAE across reactions in this probe.\n"
        "            _e_pred_kcalmol = {}\n"
        "            for _row in _pm:\n"
        "                _name = _row.get('name') or _row.get('molecule')\n"
        "                # TotalEnergyMetric emits 'E_total_nn' (Hartree); see\n"
        "                # evaluation.TotalEnergyMetric. (Earlier code looked up\n"
        "                # 'total_energy_kcalmol'/'total_energy' which never exist,\n"
        "                # leaving every probe_c reaction NaN.)\n"
        "                if 'E_total_nn' in _row:\n"
        "                    _e_pred_kcalmol[_name] = _row['E_total_nn'] * KCAL_PER_HA\n"
        "            _rxn_errs = []\n"
        "            for _rxn in _pp['reactions']:\n"
        "                _err = _bh76_rxn_error(_rxn, _e_pred_kcalmol)\n"
        "                if _err is not None:\n"
        "                    _rxn_errs.append(float(_err))\n"
        "            _mae = (float(np.mean(np.abs(_rxn_errs)))\n"
        "                    if _rxn_errs else float('nan'))\n"
        "            _new_rows.append({\n"
        "                'metric':   _metric,\n"
        "                'tag':      _tag,\n"
        "                'solver':   _solver,\n"
        "                'set':      _probe_name,\n"
        "                'mae':      _mae,\n"
        "                'rho_rmse': float('nan'),\n"
        "                'n_eval':   len(_rxn_errs),\n"
        "            })\n"
        "        else:\n"
        "            _mae, _rho, _n = _aggregate_per_molecule(_pm)\n"
        "            _new_rows.append({\n"
        "                'metric':   _metric,\n"
        "                'tag':      _tag,\n"
        "                'solver':   _solver,\n"
        "                'set':      _probe_name,\n"
        "                'mae':      _mae,\n"
        "                'rho_rmse': _rho,\n"
        "                'n_eval':   _n,\n"
        "            })\n"
        "    if _new_rows:\n"
        "        _df_new = pd.DataFrame(_new_rows)\n"
        "        _df_out = (pd.concat([_df_existing, _df_new], ignore_index=True)\n"
        "                   if not _df_existing.empty else _df_new)\n"
        "        _df_out.to_csv(_csv_path, index=False)\n\n"
        "_n_with_probes = sum(\n"
        "    1 for _spec in _all_specs\n"
        "    if os.path.isfile(os.path.join(_spec.checkpoint_dir, 'eval_df.csv'))\n"
        "    and 'probe_a' in open(os.path.join(_spec.checkpoint_dir,\n"
        "                                       'eval_df.csv')).read()\n"
        ")\n"
        "print(f'eval_df.csv with probe rows: {_n_with_probes} / {len(_all_specs)} specs')\n"
    ))
    cells.append(_md(
        "## 6. Post-Processing Analysis\n\n"
        "Generates 6 figures + headline.json from the 80 eval_df.csv files.\n"
    ))
    cells.append(_code(
        "import sys\n"
        "import subprocess\n"
        "result = subprocess.run([\n"
        "    sys.executable,\n"
        "    str(REPO / 'reports_local' / 'step7_subset_selection' / 'scripts' / 'run_post_processing.py'),\n"
        "], capture_output=True, text=True)\n"
        "print(result.stdout)\n"
        "if result.returncode != 0:\n"
        "    print('STDERR:', result.stderr)\n"
        "    raise RuntimeError(f'post-processing failed: exit {result.returncode}')\n"
    ))
    return cells


def main() -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = build_cells()
    NOTEBOOK_OUT.write_text(nbf.writes(nb), encoding="utf-8")
    print(f"wrote {NOTEBOOK_OUT}")


if __name__ == "__main__":
    main()
