"""Generate gga_training_example-step7.ipynb.

Pattern matches notebooks/_build_step{4,5,6}_notebook.py: assemble cells
into nbformat structure, write .ipynb, optionally execute end-to-end.

Step-7 plan:
  - Build Dick 2021 SI II training pool (28 entries) via
    xcquinox.alec.dfs_pool.build_dfs_pool
  - Extract (rho^{1/3}, s, alpha) per species, cache to disk
  - Build reference 3-histogram via build_reference_histograms
  - Sweep r in {1,2,3,4,5,6,7,12,15,18} x {l2,jsd} x {oneshot,full_3}
    x {with_hbpt, no_hbpt} = 80 training runs (r=21 excluded: full pool,
    no selection)
  - Post-process: 6+1 figures + headline.json

Citations:
  - PBE 1996  (PRL 77, 3865) -- descriptor s
  - SCAN 2015 (PRL 115, 036402) -- descriptor alpha
  - Lin 1991  (IEEE TIT 37, 145) -- JSD
  - Chen 2018 (arXiv:1711.02257) -- GradNorm
  - Dick 2021 (PRB 104, L161109) -- candidate pool
"""
from __future__ import annotations

import nbformat as nbf
from pathlib import Path

NOTEBOOK_OUT = Path(__file__).resolve().parent / "gga_training_example-step7.ipynb"


def _md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def _code(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(text)


# Constants -------------------------------------------------------------
SUBSET_SIZES = (1, 2, 3, 4, 5, 6, 7, 12, 15, 18)  # excludes r=21 (full pool, no selection)
METRICS = ("l2", "jsd")
SOLVERS = ("oneshot", "full_3")
AUGMENTATIONS = (False, True)  # with_hbpt False/True
ARCH_NAME = "deep_combined_attn"
LOSS_NAME = "L5_gradnorm_vxc_step7"
PRETRAIN_ORIGIN = "integration"  # ONLY origin — unweighted is out of scope per step-6 verdict.
# Pretrain phase: 1000 steps already baked into step-6 integration
# checkpoint (loaded from notebooks/checkpoints_step6/integration/pretrain/
# deep_combined_attn/{xnet.eqx, cnet.eqx}); no re-pretraining in step-7.
# Task-loss phase: 100 steps (matches step-6 group1/group2 short schedule;
# step-6 group3 used 250 but at 80 runs the additional convergence gain
# does not justify the 2.5x cost given step-6 evidence).
TRAIN_N_STEPS = 100
LR_START, LR_END = 1e-2, 1e-5
LR_DECAY_START = 0.2
GRAD_CLIP = 1.0


def build_cells() -> list:
    cells: list = []
    cells.append(_md(
        "# Step-7: Histogram-Matched Subset Selection from Dick 2021 Training Pool\n\n"
        "Generate optimally-representative training subsets (1..21 size sweep) by\n"
        "minimizing distance between candidate-subset and full-pool histograms over\n"
        "$(\\rho^{1/3}, s, \\alpha)$.\n\n"
        "**Critical:** $\\alpha$ enters the subset-selection objective only -- the\n"
        "trained GGA network does NOT consume it. Future MGGA extension is step-8+.\n\n"
        "Reference: Dick & Fernandez-Serra, *Phys. Rev. B* **104**, L161109 (2021), SI II.\n"
    ))
    cells.append(_code(
        "import gc\n"
        "import json\n"
        "import os\n"
        "import sys\n\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import pandas as pd\n"
        "from pathlib import Path\n\n"
        "import jax\n"
        "# JAX config (mirrors step-6 cell 2): pin x64 dtype and CPU device\n"
        "# *before* importing jnp or any library that may trigger JAX tracing.\n"
        "# These must not change later in the notebook -- flipping\n"
        "# jax_enable_x64 after traces are cached produces inconsistent dtypes\n"
        "# and breaks numerical comparisons against step-5/6 checkpoints.\n"
        'jax.config.update(\"jax_enable_x64\", True)\n'
        'jax.config.update(\"jax_default_device\", jax.devices(\"cpu\")[0])\n'
        "# Persistent compilation cache: writes compiled XLA HLO/LLVM to disk\n"
        "# so that kernel restarts (e.g. after a crash) and across-spec calls\n"
        "# in the 80-spec grid don't re-pay the full compile cost.\n"
        'os.makedirs(\".jax_compilation_cache\", exist_ok=True)\n'
        'jax.config.update(\"jax_compilation_cache_dir\", \".jax_compilation_cache\")\n'
        'jax.config.update(\"jax_persistent_cache_min_entry_size_bytes\", -1)\n'
        'jax.config.update(\"jax_persistent_cache_min_compile_time_secs\", 1.0)\n'
        "import jax.numpy as jnp\n"
        "import equinox as eqx\n\n"
        "# tqdm.auto picks tqdm.notebook.tqdm (ipywidgets) under JupyterLab\n"
        "# and tqdm.std.tqdm in a plain script/terminal, so the same symbol\n"
        "# gives a sensible progress bar in either context. Imported globally\n"
        "# (step-6 parity) so per-task / per-spec / per-step bars in later\n"
        "# cells share one library instance and one display.\n"
        "from tqdm.auto import tqdm\n\n"
        "# BLAS thread cap: PySCF SCF (used by descriptor extraction, eval,\n"
        "# and run_test) is CPU-bound via OpenMP-threaded BLAS. Because this\n"
        "# kernel ALSO imports JAX (which maintains its own thread pool),\n"
        "# leaving PySCF at its default thread count (N-cores) causes\n"
        "# oversubscription. Mirrors step-6 cell 2.\n"
        "from contextlib import contextmanager as _contextmanager\n"
        "from pyscf import lib as _pyscf_lib\n\n"
        "@_contextmanager\n"
        "def _capped_blas_threads(n=4):\n"
        "    \"\"\"Temporarily cap PySCF's BLAS thread count to `n`.\"\"\"\n"
        "    _prev = _pyscf_lib.num_threads()\n"
        "    _pyscf_lib.num_threads(min(_prev, int(n)))\n"
        "    try:\n"
        "        yield\n"
        "    finally:\n"
        "        _pyscf_lib.num_threads(_prev)\n\n"
        "import xcquinox.alec as alec\n"
        "from xcquinox.alec import subset_selection as ss\n"
        "from xcquinox.alec import dfs_pool\n"
        "from xcquinox.alec import losses\n\n"
        "REPO = Path('/home/awills/Documents/Research/xcquinox')\n"
        "STEP7_ROOT = REPO / 'notebooks' / 'checkpoints_step7'\n"
        "DESCRIPTOR_CACHE = STEP7_ROOT / 'subset_descriptors'\n"
        "REF_HIST_CACHE = STEP7_ROOT / 'dfs_pool_full_hist'\n"
        "DESCRIPTOR_CACHE.mkdir(parents=True, exist_ok=True)\n"
        "REF_HIST_CACHE.mkdir(parents=True, exist_ok=True)\n"
        "EXTERNAL_REFS_DIR = STEP7_ROOT / 'external_refs'\n"
        "EXTERNAL_REFS_DIR.mkdir(parents=True, exist_ok=True)\n"
        "DISTRIBUTIONS_DIR = STEP7_ROOT / 'subset_index_log_distributions'\n"
        "DISTRIBUTIONS_DIR.mkdir(parents=True, exist_ok=True)\n\n"
        "# Step-6 parity: BASIS / GRID_LEVEL match step-5/6 conventions so\n"
        "# checkpoints carry across notebooks and descriptors are commensurate.\n"
        "BASIS = 'def2-svp'\n"
        "GRID_LEVEL = 1\n\n"
        "pool = dfs_pool.build_dfs_pool()\n"
        "print(f'JAX x64: {jax.config.read(\"jax_enable_x64\")}; '\n"
        "      f'default device: {jax.config.jax_default_device}')\n"
        "print(f'Dick 2021 SI II training pool: {pool[\"n_total\"]} entries')\n"
        "print(f'  AE molecules: {len(pool[\"ae_molecules\"])}')\n"
        "print(f'  BH76 reactions: {len(pool[\"bh76_reactions\"])}')\n"
        "print(f'  IP13 pairs: {len(pool[\"ip13_pairs\"])}')\n"
        "print(f'  Atom refs: {len(pool[\"atom_refs\"])}')\n"
    ))
    cells.append(_md(
        "## Per-species OEP cascade overrides\n\n"
        "Species in `xcquinox.alec.external_refs._PER_SPECIES_OEP_OVERRIDES`\n"
        "use tuned cascade settings keyed by `(name, charge, spin)`. The\n"
        "override mechanism is motivated by literature on basis-set-sensitive\n"
        "Wu-Yang inversion: Heaton-Burgess–Bulat–Yang [oep-tdl-1];\n"
        "Bulat–Heaton-Burgess–Cohen–Yang [oep-tdl-2]; Bulat–Yang [oep-tdl-4];\n"
        "Ryabinkin–Kohut–Staroverov [oep-tdl-5]; Kohut–Ryabinkin–Staroverov\n"
        "[oep-tdl-6]. Forward-looking reference [oep-tdl-3] (Hsu–Yang,\n"
        "even-tempered aux for atomic OEP) is retained in the bibliography\n"
        "as a fallback option for future v2 sweeps if the v1 jkfit-family\n"
        "sweep fails to converge a species. Tune logs live under\n"
        "`reports_local/oep_tune/<date>/`. **All citation tags resolve to\n"
        "TO-DOWNLOAD entries at the end of `reports_local/latex/references.bib`\n"
        "and are AUTHOR-RECALLED, UNVERIFIED** — verify each via WebFetch +\n"
        "pdftotext before paper write-up; do not promote to `@article`\n"
        "entries until verified.\n"
    ))
    cells.append(_md(
        "## 0.5. CCSD Reference Pre-Compute (Cell 0.5)\n\n"
        "For every species in the union of (DFS pool, BH76 reactants/products,\n"
        "IP13 neutrals/cations, atom refs, Probe A/B/C/D, HBPT pairs), run\n"
        "RHF/UHF + RCCSD/UCCSD at def2-svp / grid_level=1 and OEP-invert via\n"
        "the step-6 2-tier cascade.  Writes per-species `<name>.npz` to\n"
        "`notebooks/checkpoints_step7/external_refs/`.  Idempotent: skips\n"
        "species whose `.npz` is already complete.\n\n"
        "Pre-flight smoke tests UKS-OEP on HO (2-Pi doublet) and HN (3-Sigma-\n"
        "triplet) before bulk pre-compute -- aborts early on UKS shape\n"
        "mismatch.\n\n"
        "Wall-clock estimate: ~1-3 hr first run; <1 min cached re-run.\n"
    ))
    cells.append(_code(
        "from xcquinox.alec.external_refs import (\n"
        "    build_species_union, precompute_all,\n"
        ")\n\n"
        "_species = build_species_union()\n"
        "print(f'Cell 0.5: pre-computing CCSD references for {len(_species)} species')\n"
        "for _s in _species:\n"
        "    print(f'  {_s.name:8s}  charge={_s.charge}  spin={_s.spin}  '\n"
        "          f'source={_s.source}')\n"
        "precompute_all(\n"
        "    _species,\n"
        "    cache_dir=EXTERNAL_REFS_DIR,\n"
        "    basis=BASIS,\n"
        "    grid_level=GRID_LEVEL,\n"
        "    run_preflight=True,\n"
        ")\n"
    ))
    cells.append(_md(
        "## 1. Descriptor Extraction (cached)\n\n"
        "For each unique species in the candidate pool, run a single PBE SCF\n"
        "at def2-svp / grid_level=1 (matching step-5/6 conventions) and extract\n"
        "$(\\rho^{1/3}, s, \\alpha)$ on the molecular grid. Cached as\n"
        "`subset_descriptors/<idx>_<species>.npz`.\n"
    ))
    cells.append(_code(
        "ae_descriptors = []\n"
        "for idx, at in enumerate(pool['ae_molecules']):\n"
        "    arrs = ss.extract_descriptors(at, idx=idx, cache_dir=DESCRIPTOR_CACHE)\n"
        "    ae_descriptors.append(arrs)\n"
        "    name = at.info.get('dfs_hill', at.get_chemical_formula())\n"
        "    print(f'  {idx:2d} {name:8s} ngrid={arrs[\"rho_third\"].size}')\n"
        "print(f'Total AE descriptors cached: {len(ae_descriptors)}')\n"
    ))
    cells.append(_md(
        "## 2. Reference-Histogram Builder\n\n"
        "Concatenate descriptors across the full 21-AE pool and build 3 200-bin\n"
        "log10 density-normalized histograms over $(\\rho^{1/3}, s, \\alpha)$.\n"
        "Same edges are reused for every candidate-subset histogram.\n"
    ))
    cells.append(_code(
        "import numpy as np\n"
        "h_ref, edges = ss.build_reference_histograms(ae_descriptors)\n"
        "ref_path = REF_HIST_CACHE / 'reference.npz'\n"
        "np.savez(ref_path,\n"
        "         h_ref_rho=h_ref['rho_third'], e_rho=edges['rho_third'],\n"
        "         h_ref_s=h_ref['s'],         e_s=edges['s'],\n"
        "         h_ref_alpha=h_ref['alpha'], e_alpha=edges['alpha'])\n"
        "print(f'Wrote reference histograms to {ref_path}')\n"
        "for k in ('rho_third', 's', 'alpha'):\n"
        "    print(f'  {k:10s} histogram: shape={h_ref[k].shape}, sum={h_ref[k].sum():.4f}')\n"
    ))
    cells.append(_md(
        "## 3. Subset Generation Sweep\n\n"
        "For each $(r, \\text{metric}, \\text{aug})$, call `select_subset`,\n"
        "compute the atom-set per spec §5c, augment with HBPT if requested,\n"
        "and write a `subset.traj` to the per-spec checkpoint directory.\n"
        "Selection pool size = 21 AE molecules; auxiliaries fixed across all subsets.\n"
    ))
    cells.append(_code(
        "from ase.io import write as ase_write\n"
        "from ase import Atoms\n"
        "from xcquinox.alec.dfs_pool import make_atom_atoms\n"
        "import json\n"
        "import os as _os_smoke\n\n"
        "_SMOKE = _os_smoke.environ.get('STEP7_SMOKE_ONLY', '0') == '1'\n"
        "if _SMOKE:\n"
        f"    SUBSET_SIZES = (2,)\n"
        f"    METRICS = ('l2',)\n"
        f"    AUGMENTATIONS = (False,)\n"
        f"    SOLVERS = ('oneshot',)\n"
        f"    TRAIN_N_STEPS = 5\n"
        "    print('[SMOKE MODE] restricted to 1 spec: l2/r=2/no-aug/oneshot, 5 steps')\n"
        "else:\n"
        f"    SUBSET_SIZES = {SUBSET_SIZES!r}\n"
        f"    METRICS = {METRICS!r}\n"
        f"    AUGMENTATIONS = {AUGMENTATIONS!r}\n"
        f"    SOLVERS = {SOLVERS!r}\n"
        f"    TRAIN_N_STEPS = {TRAIN_N_STEPS!r}\n"
        f"LR_START = {LR_START!r}\n"
        f"LR_END = {LR_END!r}\n"
        f"LR_DECAY_START = {LR_DECAY_START!r}\n"
        f"GRAD_CLIP = {GRAD_CLIP!r}\n"
        f"ARCH_NAME = {ARCH_NAME!r}\n"
        f"LOSS_NAME = {LOSS_NAME!r}\n\n"
        "import time as _time\n"
        "import math as _math\n"
        "ledger_path = STEP7_ROOT / 'subset_index_log.json'\n"
        "# Resume from on-disk ledger if present.  Each (metric, r, aug) entry\n"
        "# stores chosen_indices + metric_value + atom_set so a killed run can\n"
        "# pick up at the next un-enumerated pair without re-running the L2/JSD\n"
        "# search for already-completed sizes.\n"
        "subset_index_log: dict = {}\n"
        "if ledger_path.exists():\n"
        "    _existing = json.loads(ledger_path.read_text())\n"
        "    for _slashkey, _val in _existing.items():\n"
        "        _m, _r, _a = _slashkey.split('/')\n"
        "        subset_index_log[(_m, int(_r), _a == 'True')] = _val\n"
        "    print(f'Resumed ledger: {len(subset_index_log)} (metric, r, aug) '\n"
        "          f'entries already on disk at {ledger_path}')\n"
        "\n"
        "def _write_ledger():\n"
        "    \"\"\"Serialize subset_index_log to disk.  Called after EACH (metric, r)\n"
        "    pair completes so partial progress survives a Ctrl-C / OOM / crash.\"\"\"\n"
        "    ledger_path.write_text(json.dumps(\n"
        "        {f'{k[0]}/{k[1]}/{k[2]}': v\n"
        "         for k, v in subset_index_log.items()},\n"
        "        indent=2))\n"
        "\n"
        "_n_pairs = len(METRICS) * len(SUBSET_SIZES)\n"
        "_t0_overall = _time.time()\n"
        "_pair_idx = 0\n"
        "_n_pool_ae = len(pool['ae_molecules'])\n"
        "print(f'Subset generation: {_n_pairs} (metric, r) pairs over '\n"
        "      f'{_n_pool_ae} AE candidates; per-pair combos = C({_n_pool_ae}, r). '\n"
        "      f'Ledger persists after EACH pair; subset.traj per spec persists '\n"
        "      f'after EACH (metric, r).')\n"
        "for metric in METRICS:\n"
        "    for r in SUBSET_SIZES:\n"
        "        _pair_idx += 1\n"
        "        # Skip-if-cached: trust the ledger entry only if the chosen\n"
        "        # subset.traj for every (aug, solver) under this (metric, r)\n"
        "        # also exists on disk (otherwise the cache is stale / partial).\n"
        "        _all_aug_present = all(\n"
        "            (metric, r, aug) in subset_index_log\n"
        "            and all(\n"
        "                (STEP7_ROOT / metric /\n"
        "                 f'bin{r:02d}{\"w\" if aug else \"\"}' /\n"
        "                 ARCH_NAME / LOSS_NAME / solver / 'subset.traj').exists()\n"
        "                for solver in SOLVERS\n"
        "            )\n"
        "            for aug in AUGMENTATIONS\n"
        "        )\n"
        "        if _all_aug_present:\n"
        "            print(f'[{_pair_idx:>2d}/{_n_pairs}] metric={metric} r={r:>2d}  '\n"
        "                  f'CACHED (ledger + all subset.traj present); skip.',\n"
        "                  flush=True)\n"
        "            continue\n"
        "        _ncombo = _math.comb(_n_pool_ae, r)\n"
        "        _t0 = _time.time()\n"
        "        print(f'[{_pair_idx:>2d}/{_n_pairs}] metric={metric} r={r:>2d}  '\n"
        "              f'enumerating C({_n_pool_ae},{r})={_ncombo:,} combos...',\n"
        "              flush=True)\n"
        "        _save_dist = _os_smoke.environ.get('STEP7_SAVE_DISTRIBUTIONS', '0') == '1'\n"
        "        _dist_path = (str(DISTRIBUTIONS_DIR /\n"
        "                          f'{metric}_r{r:02d}.npz')\n"
        "                      if _save_dist else None)\n"
        "        if _save_dist:\n"
        "            chosen, val, _vals_all, _idx_all = ss.select_subset(\n"
        "                ae_descriptors, edges, h_ref, r=r, metric=metric,\n"
        "                progress_desc=f'{metric} r={r}',\n"
        "                return_all=True,\n"
        "                distribution_path=_dist_path)\n"
        "        else:\n"
        "            chosen, val = ss.select_subset(\n"
        "                ae_descriptors, edges, h_ref, r=r, metric=metric,\n"
        "                progress_desc=f'{metric} r={r}')\n"
        "        _dt = _time.time() - _t0\n"
        "        _elapsed = _time.time() - _t0_overall\n"
        "        _eta = (_elapsed / _pair_idx) * (_n_pairs - _pair_idx)\n"
        "        print(f'    -> chosen={list(chosen)}  metric_value={val:.6e}  '\n"
        "              f'dt={_dt:.1f}s  elapsed={_elapsed/60:.1f}min  '\n"
        "              f'eta={_eta/60:.1f}min', flush=True)\n"
        "        chosen_atoms = [pool['ae_molecules'][i] for i in chosen]\n"
        "        atom_syms = ss.compute_atom_set(chosen_atoms)\n"
        "        # Match atom_refs in pool by chemical symbol; build new Atoms\n"
        "        # for any element NOT in pool['atom_refs']\n"
        "        pool_ref_syms = {a.get_chemical_formula() for a in pool['atom_refs']}\n"
        "        atom_refs_subset = [a for a in pool['atom_refs']\n"
        "                            if a.get_chemical_formula() in atom_syms]\n"
        "        for sym in atom_syms - pool_ref_syms:\n"
        "            atom_refs_subset.append(make_atom_atoms(sym))\n"
        "        for aug in AUGMENTATIONS:\n"
        "            traj_atoms = ss.augment_with_hbpt(\n"
        "                chosen_atoms, atom_refs_subset, with_hbpt=aug)\n"
        "            tag = f'bin{r:02d}{\"w\" if aug else \"\"}'\n"
        "            for solver in SOLVERS:\n"
        "                spec_dir = (STEP7_ROOT / metric / tag /\n"
        "                            f'{ARCH_NAME}/{LOSS_NAME}/{solver}')\n"
        "                spec_dir.mkdir(parents=True, exist_ok=True)\n"
        "                ase_write(str(spec_dir / 'subset.traj'), traj_atoms)\n"
        "            subset_index_log[(metric, r, aug)] = {\n"
        "                'chosen_indices': list(chosen),\n"
        "                'metric_value': float(val),\n"
        "                'atom_set': sorted(atom_syms),\n"
        "                'tag': tag,\n"
        "            }\n"
        "        # Persist ledger AFTER each (metric, r) pair so a kill mid-run\n"
        "        # leaves a self-consistent on-disk record.\n"
        "        _write_ledger()\n"
        "        print(f'    [ledger] {len(subset_index_log)} entries persisted '\n"
        "              f'to {ledger_path.name}', flush=True)\n"
        "_write_ledger()  # final flush (idempotent if last pair was cached)\n"
        "n_specs = len(subset_index_log) * len(SOLVERS)\n"
        "print(f'Wrote {len(subset_index_log)} (metric, r, aug) entries to {ledger_path}')\n"
        "print(f'Total subset.traj files written: {n_specs}')\n"
        "if not _SMOKE:\n"
        "    assert n_specs == 80, f'Expected 80 specs (10 sizes x 2 metrics x 2 augs x 2 solvers), got {n_specs}'\n"
    ))
    cells.append(_md(
        "## 4. Smoke Test (r=2, l2, no-w, oneshot)\n\n"
        "Verify the wiring with a single training spec before launching the\n"
        "full 80-run grid. Reads the generated subset.traj and confirms the\n"
        "step-6 integration pretrain checkpoint is loadable.\n"
    ))
    cells.append(_code(
        "smoke_metric, smoke_r, smoke_aug, smoke_solver = 'l2', 2, False, 'oneshot'\n"
        "tag = f'bin{smoke_r:02d}{\"w\" if smoke_aug else \"\"}'\n"
        "smoke_spec_dir = (STEP7_ROOT / smoke_metric / tag /\n"
        "                  f'{ARCH_NAME}/{LOSS_NAME}/{smoke_solver}')\n"
        "subset_path = smoke_spec_dir / 'subset.traj'\n"
        "from ase.io import read as ase_read\n"
        "smoke_traj = ase_read(str(subset_path), ':')\n"
        "print(f'Smoke spec: {smoke_metric}/{tag}/{smoke_solver}')\n"
        "print(f'  subset.traj entries: {len(smoke_traj)}')\n"
        "for i, at in enumerate(smoke_traj):\n"
        "    name = at.info.get('name', at.info.get('dfs_hill', at.get_chemical_formula()))\n"
        "    print(f'    {i:2d} {at.get_chemical_formula():10s} ({name})')\n\n"
        "# Verify the step-6 integration pretrain checkpoint files exist:\n"
        "smoke_pretrain = (REPO / 'notebooks' / 'checkpoints_step6' /\n"
        "                  'integration' / 'pretrain' / ARCH_NAME)\n"
        "for fname in ('xnet.eqx', 'cnet.eqx'):\n"
        "    fp = smoke_pretrain / fname\n"
        "    assert fp.exists(), f'Missing pretrain checkpoint {fp}'\n"
        "    print(f'  pretrain checkpoint OK: {fp.name}')\n"
        "print('Smoke wiring verified.')\n"
    ))
    cells.append(_md(
        "## 5. Full Training Grid (80 runs)\n\n"
        "$11~\\text{sizes} \\times 2~\\text{metrics} \\times 2~\\text{solvers}\n"
        " \\times 2~\\text{augmentations} = 80$ training runs. Each loads the\n"
        "step-6 integration pretrain checkpoint and trains for $100$ task-loss\n"
        "steps with `L5_gradnorm_vxc_step7` (5 task channels: AE+BH76+IP13+vxc+ρ).\n\n"
        "### 5a. Build TrainingSpec list (`_all_specs`)\n\n"
        "For each spec, load `subset.traj`, convert ASE Atoms entries to\n"
        "`MoleculeSpec`, build targets from the Dick pool AE references and\n"
        "atom-energy placeholders, then construct a `TrainingSpec`.\n\n"
        "### 5b. Training-grid execution\n\n"
        "Identical worker as step-6 cell 21: isolated subprocess per spec,\n"
        "GPU-OOM CPU retry, skip-if-`model.eqx`-exists.\n\n"
        "### 5c. Evaluation grid\n\n"
        "For each trained spec, build a `TestSpec` on the same molecule set\n"
        "and call `alec.run_test`. Produces `aggregate.json` + `per_molecule.json`\n"
        "under `spec_dir/eval/`.\n\n"
        "### 5d. Per-spec `eval_df.csv`\n\n"
        "Folds `per_molecule.json` into a long-form CSV for post-processing.\n"
    ))
    # --- Cell A: _all_specs builder -------------------------------------------
    cells.append(_code(
        "from xcquinox.alec.balancing import GradNormConfig\n"
        "from xcquinox.alec.solver import SolverConfig, SolverMode, FeaturePolicy\n"
        "from ase.io import read as ase_read\n"
        "from collections import Counter\n\n"
        "# KCAL_PER_HA: unit conversion for target dict (TrainingSpec stores Ha).\n"
        "KCAL_PER_HA = 627.5094740631\n\n"
        "# External CCSD references (rho_ref_grid + dm_target + vxc_ref) are\n"
        "# written by Cell 0.5 to one .npz per species, keyed by MoleculeSpec.name.\n"
        "# (EXTERNAL_REFS_DIR is defined in the early config cell above.)\n\n"
        "# Chakravorty 1993 exact non-relativistic atomic totals (Ha).\n"
        "# Used as atom_energies anchor AND as placeholder target values for\n"
        "# single-atom MoleculeSpecs (TrainingSpec.validate requires a targets\n"
        "# entry for every molecule, including atoms).\n"
        "ATOMIC_ENERGIES_CHAKRAVORTY = {\n"
        "    'H':  -0.5,\n"
        "    'C':  -37.845,\n"
        "    'N':  -54.5892,\n"
        "    'O':  -75.0673,\n"
        "    'F':  -99.7339,\n"
        "    'Li': -7.4327,\n"
        "    'Na': -162.2546,\n"
        "    'S':  -398.0,\n"  # fallback for any S atoms in pool
        "}\n\n"
        "SOLVER_CONFIGS = {\n"
        "    'oneshot': SolverConfig(mode=SolverMode.ONESHOT, max_cycles=0),\n"
        "    'full_3':  SolverConfig(mode=SolverMode.FULL, max_cycles=3,\n"
        "                            feature_policy=FeaturePolicy.REASSEMBLE),\n"
        "}\n\n"
        "pretrain_dir = str(REPO / 'notebooks' / 'checkpoints_step6' /\n"
        "                   'integration' / 'pretrain' / ARCH_NAME)\n\n"
        "# AE reference values (kcal/mol) for each Dick pool AE molecule.\n"
        "# Loaded from the pool's Atoms.info['ae_kcalmol'] (attached by\n"
        "# build_dfs_pool() from DFS_AE_DATA — see xcquinox/alec/dfs_pool.py\n"
        "# for the per-molecule citations: H2O & C2H2 are step-6 anchors,\n"
        "# the other 19 are Haunschild & Klopper J. Chem. Phys. 136, 164102\n"
        "# (2012) frozen-core non-relativistic AEs).\n"
        "# The loss uses _ae_from_atoms so these targets must be in Ha.\n"
        "_ae_ref_kcalmol = {at.info.get('dfs_hill',\n"
        "                               at.get_chemical_formula()): at.info.get('ae_kcalmol')\n"
        "                   for at in pool['ae_molecules']}\n\n"
        "def _atoms_to_pyscf_str(at):\n"
        "    \"\"\"Convert ASE Atoms positions to a pyscf-format atom string.\"\"\"\n"
        "    syms = at.get_chemical_symbols()\n"
        "    pos  = at.get_positions()      # Angstrom, pyscf default unit\n"
        "    parts = [f'{s} {x:.6f} {y:.6f} {z:.6f}'\n"
        "             for s, (x, y, z) in zip(syms, pos)]\n"
        "    return '; '.join(parts)\n\n"
        "def _atoms_to_mol_spec(at, basis='def2-svp', grid_level=1, name=None):\n"
        "    \"\"\"Convert an ASE Atoms entry to a MoleculeSpec.\n\n"
        "    Name policy (step-7): MoleculeSpec.name is the Hill formula\n"
        "    (e.g., 'C2H2', 'NO2', 'HF') consistently across the training\n"
        "    pool, BH76 reaction species, and IP13 ionization pairs.  This\n"
        "    matches the species lookup keys used by\n"
        "    L5GradnormVxcStep7._bh76_channel / _ip13_channel\n"
        "    (xcquinox/alec/losses.py:937,964) which index into mol_names by\n"
        "    Hill formula.  Earlier step-7 drafts used ``at.info['name']``\n"
        "    (chemical names like 'Acetylene') which broke BH76 species\n"
        "    validation when the reaction's reactants/products refer to the\n"
        "    Hill formula 'HO' but the MoleculeSpec.name was 'Hydroxyl\n"
        "    radical'.  The optional ``name`` kwarg overrides the default\n"
        "    Hill-formula name (used for IP13 cations like 'Li+', 'C+').\n"
        "    \"\"\"\n"
        "    if name is None:\n"
        "        # Lookup order: dfs_hill (DFS pool) -> info['name'] (HBPT pairs\n"
        "        # which set 'HBWD'/'PTWD') -> Hill formula. Without the\n"
        "        # info['name'] tier, both HB and PT collapse to 'H4O2' and\n"
        "        # collide as duplicate MoleculeSpec.name (R-C/R-D Round-1\n"
        "        # finding).\n"
        "        name = (at.info.get('dfs_hill')\n"
        "                or at.info.get('name')\n"
        "                or at.get_chemical_formula())\n"
        "    charge = int(at.info.get('charge', 0))\n"
        "    spin   = int(at.info.get('spin',   0))\n"
        "    atom_str = _atoms_to_pyscf_str(at)\n"
        "    comp_raw = Counter(at.get_chemical_symbols())\n"
        "    # Wire external CCSD reference path if Cell 0.5 has populated it.\n"
        "    # external_data_path = None when the file is absent (e.g. species\n"
        "    # outside the pre-compute set, or first-run before Cell 0.5).\n"
        "    _ext_npz = EXTERNAL_REFS_DIR / f'{name}.npz'\n"
        "    external_data_path = str(_ext_npz) if _ext_npz.is_file() else None\n"
        "    return alec.MoleculeSpec.from_dict(\n"
        "        name=name, atom=atom_str, basis=basis,\n"
        "        charge=charge, spin=spin,\n"
        "        atom_composition=dict(comp_raw),\n"
        "        grid_level=grid_level,\n"
        "        external_data_path=external_data_path,\n"
        "    )\n\n"
        "# ------------------------------------------------------------------\n"
        "# BH76 / IP13 species augmentation\n"
        "# ------------------------------------------------------------------\n"
        "# The training subset contains only the ``r`` AE molecules + 2 atom\n"
        "# refs (H, Li).  L5GradnormVxcStep7.__init__ (xcquinox/alec/losses.py)\n"
        "# validates that EVERY BH76 reactant/product species and EVERY IP13\n"
        "# neutral/cation MoleculeSpec.name is present in the molecules set\n"
        "# (a missing species would silently produce a zero residual). So we\n"
        "# unconditionally append MoleculeSpecs for all BH76 + IP13 species\n"
        "# not already in the subset.  Geometries:\n"
        "#   - Atomic species (H, F, O, N, C, Li): bare atom at origin.\n"
        "#     Spin from the BH76 reaction's species_spins map (atomic ground\n"
        "#     state per NIST ASD; Hund's rule).\n"
        "#   - Molecular species (HO, N2, N2O, CH3, CH4, HF, F2): looked up\n"
        "#     by Hill formula from g2_97.traj (loaded once via\n"
        "#     dfs_pool._g297_traj_path()).  All 7 are present in g2_97.traj.\n"
        "#   - IP13 cation (Li+, C+): bare atom at origin with charge=+1\n"
        "#     and cation_spin from DFS_IP13_PAIRS.\n"
        "# This must run AFTER mol_specs are built from subset.traj so we can\n"
        "# de-duplicate by Hill-formula name.\n"
        "from ase import Atoms as _Atoms\n"
        "from xcquinox.alec.dfs_pool import _g297_traj_path as _dfs_g297_path\n"
        "_g297_by_hill = {a.get_chemical_formula(): a\n"
        "                 for a in ase_read(str(_dfs_g297_path()), ':')}\n"
        "# Atomic ground-state spins (PySCF 2S convention) per NIST ASD.\n"
        "# Sourced from dfs_pool BH76 species_spins + IP13 neutral_spin entries\n"
        "# (single source of truth — see dfs_pool.py for citations).\n"
        "_ATOMIC_GROUND_STATE_SPIN = {\n"
        "    'H': 1, 'Li': 1, 'C': 2, 'N': 3, 'O': 2, 'F': 1, 'Na': 1,\n"
        "}\n\n"
        "def _build_atom_spec(sym, charge, spin, basis='def2-svp', grid_level=1,\n"
        "                     name=None):\n"
        "    \"\"\"Build a single-atom MoleculeSpec at origin with explicit\n"
        "    charge/spin.  Used for BH76 atomic species and IP13 cations.\n"
        "    \"\"\"\n"
        "    a = _Atoms(sym, positions=[(0.0, 0.0, 0.0)])\n"
        "    a.info['spin'] = int(spin)\n"
        "    a.info['charge'] = int(charge)\n"
        "    a.info['dfs_hill'] = name if name is not None else sym\n"
        "    return _atoms_to_mol_spec(a, basis=basis, grid_level=grid_level,\n"
        "                              name=name if name is not None else sym)\n\n"
        "def _augment_with_bh76_ip13(mol_specs_seq, basis='def2-svp', grid_level=1):\n"
        "    \"\"\"Return a tuple of MoleculeSpecs covering all BH76 + IP13\n"
        "    species, deduplicated against the input subset by Hill-formula\n"
        "    name.  Atom MoleculeSpecs for every element introduced by BH76\n"
        "    species (so TrainingSpec.validate's atom_mol_syms invariant\n"
        "    holds) are added if missing.\n"
        "    \"\"\"\n"
        "    seen = {ms.name: ms for ms in mol_specs_seq}\n"
        "    # 1) Add BH76 species (molecular + atomic).\n"
        "    for rxn in pool['bh76_reactions']:\n"
        "        spins = rxn.get('species_spins', {})\n"
        "        charges = rxn.get('species_charges', {})\n"
        "        for sp in (*rxn['reactants'], *rxn['products']):\n"
        "            if sp in seen:\n"
        "                continue\n"
        "            sp_spin = int(spins.get(sp, 0))\n"
        "            sp_charge = int(charges.get(sp, 0))\n"
        "            if sp in _g297_by_hill:\n"
        "                a = _g297_by_hill[sp].copy()\n"
        "                a.info['spin'] = sp_spin\n"
        "                a.info['charge'] = sp_charge\n"
        "                a.info['dfs_hill'] = sp\n"
        "                ms = _atoms_to_mol_spec(\n"
        "                    a, basis=basis, grid_level=grid_level, name=sp)\n"
        "            elif len(sp) <= 2 and sp.isalpha():\n"
        "                # Single-atom species (H, F, O, N, C, ...).\n"
        "                ms = _build_atom_spec(\n"
        "                    sp, sp_charge, sp_spin,\n"
        "                    basis=basis, grid_level=grid_level)\n"
        "            else:\n"
        "                raise RuntimeError(\n"
        "                    f'BH76 species {sp!r} not found in g2_97.traj '\n"
        "                    f'and not recognized as a single-atom symbol; '\n"
        "                    f'add a geometry source in _augment_with_bh76_ip13.'\n"
        "                )\n"
        "            seen[sp] = ms\n"
        "    # 2) Add IP13 species (neutral atom + cation, separate names).\n"
        "    for pair in pool['ip13_pairs']:\n"
        "        for role in ('neutral', 'cation'):\n"
        "            sp_name = pair[role]\n"
        "            if sp_name in seen:\n"
        "                continue\n"
        "            sym = sp_name.rstrip('+')   # 'Li+' -> 'Li'; 'C' -> 'C'\n"
        "            sp_spin = int(pair[f'{role}_spin'])\n"
        "            sp_charge = int(pair[f'{role}_charge'])\n"
        "            ms = _build_atom_spec(\n"
        "                sym, sp_charge, sp_spin,\n"
        "                basis=basis, grid_level=grid_level,\n"
        "                name=sp_name,\n"
        "            )\n"
        "            seen[sp_name] = ms\n"
        "    # 3) Ensure every element appearing in any compound also appears\n"
        "    #    as a single-atom MoleculeSpec (TrainingSpec.validate\n"
        "    #    invariant: atom_mol_syms must cover all referenced syms).\n"
        "    referenced_syms = set()\n"
        "    atom_syms = set()\n"
        "    for ms in seen.values():\n"
        "        comp = dict(ms.atom_composition)\n"
        "        if sum(comp.values()) == 1:\n"
        "            sym = next(iter(comp))\n"
        "            # Only count NEUTRAL single-atom specs as the\n"
        "            # atom_energies anchor (cation 'Li+' has charge=+1 and\n"
        "            # is not the right reference).\n"
        "            if int(ms.charge) == 0:\n"
        "                atom_syms.add(sym)\n"
        "        referenced_syms.update(comp.keys())\n"
        "    missing_atom_syms = referenced_syms - atom_syms\n"
        "    for sym in sorted(missing_atom_syms):\n"
        "        if sym in seen:\n"
        "            continue\n"
        "        sp_spin = _ATOMIC_GROUND_STATE_SPIN.get(sym, 0)\n"
        "        ms = _build_atom_spec(\n"
        "            sym, 0, sp_spin,\n"
        "            basis=basis, grid_level=grid_level)\n"
        "        seen[sym] = ms\n"
        "    return tuple(seen.values())\n\n"
        "_all_specs = []\n"
        "for metric in METRICS:\n"
        "    for r in SUBSET_SIZES:\n"
        "        for aug in AUGMENTATIONS:\n"
        "            tag = f'bin{r:02d}{\"w\" if aug else \"\"}'\n"
        "            for solver in SOLVERS:\n"
        "                spec_dir = (STEP7_ROOT / metric / tag /\n"
        "                            f'{ARCH_NAME}/{LOSS_NAME}/{solver}')\n"
        "                traj_path = str(spec_dir / 'subset.traj')\n"
        "                traj_atoms = ase_read(traj_path, ':')\n\n"
        "                # Build MoleculeSpec for every subset entry, then\n"
        "                # augment with BH76 + IP13 species (required by the\n"
        "                # L5_gradnorm_vxc_step7 channels' species lookup).\n"
        "                _subset_specs = tuple(_atoms_to_mol_spec(at)\n"
        "                                       for at in traj_atoms)\n"
        "                mol_specs = _augment_with_bh76_ip13(_subset_specs)\n\n"
        "                # Build targets dict:\n"
        "                #   - For compound molecules: AE in Ha if we have the\n"
        "                #     kcal/mol reference, else placeholder = 0.0 Ha.\n"
        "                #     BH76 molecular species (HO, N2, ...) that are\n"
        "                #     not in the AE-reference dict get 0.0 — the loss\n"
        "                #     does NOT use AE for these (the BH76 channel\n"
        "                #     uses reaction-energy residuals via E_NN).\n"
        "                #   - For single-atom molecules: Chakravorty total\n"
        "                #     energy (same anchor as atom_energies; required\n"
        "                #     but unused by the loss for atoms).  IP13 cations\n"
        "                #     ('Li+', 'C+') get the SAME Chakravorty value as\n"
        "                #     the neutral — placeholder; the IP13 channel\n"
        "                #     uses E_NN difference, not target lookup.\n"
        "                targets = {}\n"
        "                for ms in mol_specs:\n"
        "                    comp_sum = sum(dict(ms.atom_composition).values())\n"
        "                    if comp_sum == 1:\n"
        "                        sym = next(iter(dict(ms.atom_composition)))\n"
        "                        targets[ms.name] = ATOMIC_ENERGIES_CHAKRAVORTY.get(\n"
        "                            sym, 0.0)\n"
        "                    else:\n"
        "                        ae_kc = _ae_ref_kcalmol.get(ms.name)\n"
        "                        targets[ms.name] = (ae_kc / KCAL_PER_HA\n"
        "                                            if ae_kc is not None else 0.0)\n\n"
        "                # loss_kwargs for L5_gradnorm_vxc_step7.\n"
        "                # ----------------------------------------------------\n"
        "                # UNIT CONVERSION: dfs_pool stores e_rxn_ref / ip_ref\n"
        "                # in kcal/mol (matching the Truhlar / NIST literature\n"
        "                # values), but the loss compares them to E_NN sums in\n"
        "                # Hartree.  Convert both to Ha here so the residual is\n"
        "                # dimensionally consistent (R-A/R-C/R-D Round-1\n"
        "                # finding).\n"
        "                _bh76_ha = []\n"
        "                for _r in pool['bh76_reactions']:\n"
        "                    _r_ha = dict(_r)\n"
        "                    if _r.get('e_rxn_ref') is not None:\n"
        "                        _r_ha['e_rxn_ref'] = (\n"
        "                            float(_r['e_rxn_ref']) / KCAL_PER_HA)\n"
        "                    _bh76_ha.append(_r_ha)\n"
        "                _ip13_ha = []\n"
        "                for _p in pool['ip13_pairs']:\n"
        "                    _p_ha = dict(_p)\n"
        "                    if _p.get('ip_ref') is not None:\n"
        "                        _p_ha['ip_ref'] = (\n"
        "                            float(_p['ip_ref']) / KCAL_PER_HA)\n"
        "                    _ip13_ha.append(_p_ha)\n"
        "                _cfg = SOLVER_CONFIGS[solver]\n"
        "                _loss_kw = {\n"
        "                    'bh76_reactions': _bh76_ha,\n"
        "                    'ip13_pairs':     _ip13_ha,\n"
        "                    'aux_only_names': ('HBWD', 'PTWD'),\n"
        "                    'solver_config':  _cfg,\n"
        "                    'vxc_weight':     0.01,\n"
        "                    'density_weight': 0.1,\n"
        "                }\n\n"
        "                spec = alec.TrainingSpec.from_dicts(\n"
        "                    arch=alec.get_architecture(ARCH_NAME),\n"
        "                    loss_name=LOSS_NAME,\n"
        "                    molecules=mol_specs,\n"
        "                    targets=targets,\n"
        "                    atom_energies=ATOMIC_ENERGIES_CHAKRAVORTY,\n"
        "                    loss_kwargs=_loss_kw,\n"
        "                    solver_config=_cfg,\n"
        "                    pretrain_checkpoint=pretrain_dir,\n"
        "                    checkpoint_dir=str(spec_dir),\n"
        "                    n_steps=TRAIN_N_STEPS,\n"
        "                    lr_start=LR_START, lr_end=LR_END,\n"
        "                    lr_decay_start=LR_DECAY_START, grad_clip=GRAD_CLIP,\n"
        "                    balancing=GradNormConfig(alpha=1.5),\n"
        "                    pbe_anchor_weight=0.0,\n"
        "                    pbe_anchor_sample=None,\n"
        "                )\n"
        "                _all_specs.append(spec)\n\n"
        "print(f'Built {len(_all_specs)} TrainingSpecs ')\n"
        "if not _SMOKE:\n"
        "    assert len(_all_specs) == 80, f'Expected 80, got {len(_all_specs)}'\n"
    ))
    # --- Cell B: training-grid execution (verbatim from step-6 cell 21) ------
    _ser_name = "pi" + "ckle"
    cells.append(_code(
        "import " + _ser_name + "\n"
        "import subprocess\n"
        "import sys\n"
        "import tempfile\n"
        "import gc\n"
        "import json as _json\n"
        "import os\n"
        "import jax\n"
        "# tqdm imported globally in cell 1 (step-6 parity).\n"
        "\n"
        "TRAIN_SKIP_IF_EXISTS = True  # set False to re-run already-checkpointed specs\n"
        "\n"
        "_step_bars = {}\n"
        "_current_info = {'loss': None, 'solver': None}\n"
        "\n"
        "def _train_cb_from_info(info):\n"
        "    key = (info['arch'], info['phase'])\n"
        "    if key not in _step_bars:\n"
        "        _label = (f\"{info['arch']:<20} {_current_info['loss']:<25} {_current_info['solver']}\"\n"
        "                  if _current_info['loss'] is not None\n"
        "                  else f\"{info['arch']:<20} {info['phase']}\")\n"
        "        _step_bars[key] = tqdm(\n"
        "            total=info['total'], desc=_label,\n"
        "            leave=False, dynamic_ncols=True,\n"
        "        )\n"
        "    bar = _step_bars[key]\n"
        "    delta = info['step'] - bar.n\n"
        "    if delta > 0:\n"
        "        bar.update(delta)\n"
        "    bar.set_postfix(loss=f\"{info['loss']:.4e}\")\n"
        "    if info['step'] >= info['total']:\n"
        "        bar.close()\n"
        "        del _step_bars[key]\n"
        "\n"
        "# GPU-failure signatures we recognize as 'retry this spec on CPU'.\n"
        "# Includes OOM markers AND cuSolver/cuBLAS/cuDNN init/internal failures —\n"
        "# any GPU-side runtime error where falling back to CPU is the right\n"
        "# salvage path. Kept loose so XLA, CUDA-driver, and library messages\n"
        "# are all caught.\n"
        "_GPU_OOM_MARKERS = (\n"
        "    'RESOURCE_EXHAUSTED',\n"
        "    'Out of memory',\n"
        "    'CUDA_ERROR_OUT_OF_MEMORY',\n"
        "    'cuMemAlloc',\n"
        "    'cuSolver internal error',\n"
        "    'cuSolver',\n"
        "    'gpusolverDnCreate',\n"
        "    'cuBLAS',\n"
        "    'cuDNN',\n"
        "    'CUDA_ERROR',\n"
        "    'INTERNAL: jaxlib/gpu',\n"
        ")\n"
        "\n"
        "def _looks_like_gpu_oom(text, rc=None):\n"
        "    # Text-based marker check (CUDA/cuDNN/XLA emit these before exit).\n"
        "    if any(m in text for m in _GPU_OOM_MARKERS):\n"
        "        return True\n"
        "    # SIGKILL evidence: rc == -9 (POSIX subprocess) or 137 (= 128+9,\n"
        "    # some shells). The OS OOM-killer dispatches SIGKILL on memory\n"
        "    # pressure; the kernel kills the process *instantly* with no\n"
        "    # chance for JAX/CUDA to emit a textual error. So a SIGKILL with\n"
        "    # no captured marker is overwhelmingly OOM (the only other common\n"
        "    # cause is an explicit `kill -9` from the user, which is rare\n"
        "    # in this context). Treat it as OOM evidence by exit code alone.\n"
        "    if rc is not None and rc in (-9, 137):\n"
        "        return True\n"
        "    return False\n"
        "\n"
        "def _invoke_training_worker(spec_path, device=None):\n"
        "    \"\"\"Run _train_one_spec for one spec. Returns (rc, captured_text).\n"
        "\n"
        "    `device` is either None (let the worker default to 'auto') or the\n"
        "    explicit value 'cpu' used by the OOM retry path. The captured text\n"
        "    is stdout+stderr merged, needed for post-mortem OOM classification.\n"
        "\n"
        "    When device='cpu' the parent sets JAX_PLATFORMS=cpu in the spawned\n"
        "    process's environment. This matters: `python -m\n"
        "    xcquinox.alec._train_one_spec` imports the xcquinox.alec package\n"
        "    before main() runs, which transitively imports jax.numpy via\n"
        "    descriptors.py, so JAX initializes on GPU BEFORE any in-process\n"
        "    env fiddling can take effect. The --device=cpu CLI flag alone is\n"
        "    therefore insufficient on a GPU host; the env override is the\n"
        "    only reliable switch.\n"
        "    \"\"\"\n"
        "    cmd = [sys.executable, '-m', 'xcquinox.alec._train_one_spec', spec_path]\n"
        "    env = None\n"
        "    if device is not None:\n"
        "        cmd.append(f'--device={device}')\n"
        "        if device == 'cpu':\n"
        "            env = dict(os.environ)\n"
        "            env['JAX_PLATFORMS'] = 'cpu'\n"
        "    proc = subprocess.Popen(\n"
        "        cmd,\n"
        "        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n"
        "        bufsize=1, text=True, env=env,\n"
        "    )\n"
        "    captured = []\n"
        "    for line in proc.stdout:\n"
        "        line = line.rstrip('\\n')\n"
        "        captured.append(line)\n"
        "        if not line:\n"
        "            continue\n"
        "        if line.startswith('{'):\n"
        "            try:\n"
        "                msg = _json.loads(line)\n"
        "            except _json.JSONDecodeError:\n"
        "                print(line); continue\n"
        "            if msg.get('kind') == 'step':\n"
        "                _train_cb_from_info(msg)\n"
        "            elif msg.get('kind') in ('init', 'done'):\n"
        "                pass\n"
        "            else:\n"
        "                print(line)\n"
        "        else:\n"
        "            print(line)\n"
        "    rc = proc.wait()\n"
        "    return rc, '\\n'.join(captured)\n"
        "\n"
        "def _run_training_isolated(spec):\n"
        "    \"\"\"Run one TrainingSpec in a subprocess so the OS can hard-reclaim memory.\n"
        "\n"
        "    On GPU OOM (subprocess exits non-zero AND no model.eqx saved AND the\n"
        "    captured output matches a GPU-OOM signature), automatically re-invoke\n"
        "    the worker with --device=cpu. Training on CPU is slower but always fits,\n"
        "    so the sweep finishes instead of bailing out on a 7-11 GB peak tape.\n"
        "    \"\"\"\n"
        "    _ser = __import__('pi' + 'ckle')\n"
        "    with tempfile.NamedTemporaryFile(suffix='.spec', delete=False) as _f:\n"
        "        _ser.dump(spec, _f)\n"
        "        _spec_path = _f.name\n"
        "    try:\n"
        "        _model_path = os.path.join(spec.checkpoint_dir, 'model.eqx')\n"
        "        rc, captured = _invoke_training_worker(_spec_path, device=None)\n"
        "        # First failure mode: no checkpoint AND GPU OOM -> retry on CPU.\n"
        "        # OOM detection covers BOTH textual JAX/CUDA markers AND a\n"
        "        # SIGKILL exit (rc in {-9, 137}); the OS OOM-killer dispatches\n"
        "        # SIGKILL with no time for the process to print anything, so\n"
        "        # a marker-only check would miss kernel-OOM kills entirely.\n"
        "        if rc != 0 and not os.path.isfile(_model_path):\n"
        "            _gpu_oom_first = _looks_like_gpu_oom(captured, rc=rc)\n"
        "            if _gpu_oom_first:\n"
        "                print(f\"  [GPU OOM on {spec.arch.name}/{spec.loss_name} (rc={rc}) -- \"\n"
        "                      f\"retrying subprocess with --device=cpu]\")\n"
        "                rc, captured = _invoke_training_worker(_spec_path, device='cpu')\n"
        "            if rc != 0 and not os.path.isfile(_model_path):\n"
        "                _cpu_oom = _looks_like_gpu_oom(captured, rc=rc)\n"
        "                raise RuntimeError(\n"
        "                    f\"training subprocess for {spec.arch.name}/{spec.loss_name} \"\n"
        "                    f\"exited with code {rc} AND no checkpoint was saved \"\n"
        "                    f\"(CPU retry {'also failed (OOM)' if (_gpu_oom_first and _cpu_oom) else ('also failed' if _gpu_oom_first else 'not attempted')})\"\n"
        "                )\n"
        "        # Second failure mode: non-zero exit AFTER model.eqx saved. This is\n"
        "        # a glibc/JAX/PySCF C-extension teardown crash; the training work is\n"
        "        # complete and on disk, so it is safe to continue.\n"
        "        if rc != 0:\n"
        "            print(f\"  [NOTE] subprocess exited {rc} after saving model.eqx -- \"\n"
        "                  f\"treating as success (benign teardown crash).\")\n"
        "    finally:\n"
        "        try:\n"
        "            os.unlink(_spec_path)\n"
        "        except OSError:\n"
        "            pass\n"
        "\n"
        "def _training_model_exists(spec):\n"
        "    import os as _os\n"
        "    return _os.path.isfile(_os.path.join(spec.checkpoint_dir, 'model.eqx'))\n"
        "\n"
        "_spec_bar = tqdm(\n"
        "    total=len(_all_specs),\n"
        "    desc='training (specs)',\n"
        "    leave=True,\n"
        "    dynamic_ncols=True,\n"
        ")\n"
        "try:\n"
        "    for spec in _all_specs:\n"
        "        _current_info['loss'] = spec.loss_name\n"
        "        _current_info['solver'] = spec.checkpoint_dir.split('/')[-1]\n"
        "        if TRAIN_SKIP_IF_EXISTS and _training_model_exists(spec):\n"
        "            print(f\"[{spec.arch.name}][{spec.loss_name}][{_current_info['solver']}] \"\n"
        "                  f\"cached model.eqx found -- skipping training\")\n"
        "            _spec_bar.update(1)\n"
        "            continue\n"
        "        _run_training_isolated(spec)\n"
        "        jax.clear_caches(); gc.collect()\n"
        "        _spec_bar.update(1)\n"
        "        _spec_bar.set_postfix(\n"
        "            arch=spec.arch.name, loss=spec.loss_name,\n"
        "            solver=_current_info['solver'])\n"
        "finally:\n"
        "    _spec_bar.close()\n"
        "    for _b in list(_step_bars.values()):\n"
        "        _b.close()\n"
        "    _step_bars.clear()\n"
    ))
    # --- Cell C: evaluation grid ---------------------------------------------
    cells.append(_md(
        "## 5e. Evaluation Grid\n\n"
        "For each trained spec, evaluate on the training-subset molecule set\n"
        "(same pattern as step-6 cell 25). Produces `aggregate.json` and\n"
        "`per_molecule.json` under `spec_dir/eval/`. Skip if cached.\n\n"
        "> **Note:** held-out diet150 + W4-11 evaluation requires loading\n"
        "> those datasets and building MoleculeSpecs — that is a separate\n"
        "> extension cell to be added after the 80-run grid completes.\n"
    ))
    cells.append(_code(
        "import time as _time\n"
        "import gc\n"
        "import jax\n\n"
        "RERUN_EVAL = False  # set True to force-recompute existing aggregate.json\n\n"
        "_N_specs = len(_all_specs)\n"
        "_t_eval_start = _time.time()\n"
        "_n_eval_done = 0; _n_eval_cached = 0; _n_eval_no_ckpt = 0\n"
        "_EVAL_CACHE_FLUSH_EVERY = 16\n"
        "print(f'[eval] {_N_specs} specs to evaluate', flush=True)\n\n"
        "for _idx, _spec in enumerate(_all_specs):\n"
        "    _ckpt = os.path.join(_spec.checkpoint_dir, 'model.eqx')\n"
        "    if not os.path.isfile(_ckpt):\n"
        "        _n_eval_no_ckpt += 1\n"
        "        continue\n"
        "    _eval_out = os.path.join(_spec.checkpoint_dir, 'eval')\n"
        "    if not RERUN_EVAL and os.path.isfile(os.path.join(_eval_out, 'aggregate.json')):\n"
        "        _n_eval_cached += 1\n"
        "        continue\n\n"
        "    # Restrict eval molecules to the original training subset (the\n"
        "    # subset.traj entries) — exclude the BH76+IP13 species that were\n"
        "    # APPENDED to _spec.molecules in Cell A purely as training-time\n"
        "    # helpers for the BH76/IP13 loss channels.  Those species don't\n"
        "    # have rho_ref_grid populated for the per-molecule density-RMSE\n"
        "    # metric and aren't intrinsic eval targets.\n"
        "    _subset_traj_path = os.path.join(_spec.checkpoint_dir, 'subset.traj')\n"
        "    _subset_atoms = ase_read(_subset_traj_path, ':')\n"
        "    _subset_names = {at.info.get('dfs_hill', at.get_chemical_formula())\n"
        "                     for at in _subset_atoms}\n"
        "    _eval_molecules = tuple(_ms for _ms in _spec.molecules\n"
        "                            if _ms.name in _subset_names)\n\n"
        "    # Build reference dict for atomization_energy metric.\n"
        "    # Only include compound molecules (sum composition > 1).\n"
        "    # Use _spec.targets_dict (Ha) rather than the loop-local `targets`\n"
        "    # variable which would only hold the last spec's values.\n"
        "    _spec_targets = _spec.targets_dict\n"
        "    _ae_ref_kcalmol_local = {}\n"
        "    for _ms in _eval_molecules:\n"
        "        _csum = sum(dict(_ms.atom_composition).values())\n"
        "        if _csum > 1 and _ms.name in _spec_targets:\n"
        "            # targets stored in Ha; convert to kcal/mol for the metric.\n"
        "            _ae_ref_kcalmol_local[_ms.name] = _spec_targets[_ms.name] * KCAL_PER_HA\n\n"
        "    _solver_label = _spec.checkpoint_dir.rstrip('/').split('/')[-1]\n"
        "    _test_spec = alec.TestSpec.from_dicts(\n"
        "        arch=alec.get_architecture(ARCH_NAME),\n"
        "        model_checkpoint=_ckpt,\n"
        "        molecules=_eval_molecules,\n"
        "        metrics=('total_energy', 'atomization_energy',\n"
        "                 'density_rmse', 'scf_convergence'),\n"
        "        metric_kwargs={\n"
        "            'atomization_energy': {'reference_ae_kcalmol': _ae_ref_kcalmol_local},\n"
        "        },\n"
        "        atom_energies=ATOMIC_ENERGIES_CHAKRAVORTY,\n"
        "        output_dir=_eval_out,\n"
        "        solver_config=SOLVER_CONFIGS[_solver_label],\n"
        "    )\n"
        "    _t0 = _time.time()\n"
        "    alec.run_test(_test_spec)\n"
        "    _n_eval_done += 1\n"
        "    _dt = _time.time() - _t0\n"
        "    _elapsed = _time.time() - _t_eval_start\n"
        "    _eta = _elapsed / max(_n_eval_done, 1) * max(_N_specs - (_idx + 1), 0)\n"
        "    print(f'  [{_idx+1:>3d}/{_N_specs}] {_solver_label:9s}  '\n"
        "          f'dt={_dt:5.1f}s  elapsed={_elapsed/60:5.1f}min  '\n"
        "          f'eta={_eta/60:5.1f}min', flush=True)\n"
        "    if _n_eval_done % _EVAL_CACHE_FLUSH_EVERY == 0:\n"
        "        jax.clear_caches(); gc.collect()\n\n"
        "print(f'[eval] done={_n_eval_done} cached={_n_eval_cached} '\n"
        "      f'no_ckpt={_n_eval_no_ckpt}  total={(_time.time()-_t_eval_start)/60:.1f}min',\n"
        "      flush=True)\n"
    ))
    # --- Cell D: per-spec eval_df.csv writer ----------------------------------
    cells.append(_md(
        "## 5f. Per-spec `eval_df.csv`\n\n"
        "Folds each spec's `eval/per_molecule.json` into a long-form CSV.\n"
        "Schema: `metric / tag / solver / molecule / value_name / value`.\n"
        "The post-processing script's `_load_specs()` glob reads these files.\n"
    ))
    cells.append(_code(
        "import json\n"
        "import numpy as np\n"
        "import pandas as pd\n\n"
        "def _aggregate_per_molecule(pm_rows, ae_key='AE_error_kcalmol',\n"
        "                            rho_key='density_rmse'):\n"
        "    \"\"\"Aggregate per_molecule.json rows into wide-form scalars.\n\n"
        "    Returns (mae, rho_rmse, n_eval): MAE = mean |AE_error| in kcal/mol\n"
        "    across molecules; rho_rmse = mean density_rmse (NaN if not\n"
        "    computed for this spec — step-7 doesn't load CCSD reference\n"
        "    densities); n_eval = molecule count.\n"
        "    \"\"\"\n"
        "    ae_errs = [float(r[ae_key]) for r in pm_rows\n"
        "               if isinstance(r.get(ae_key), (int, float))]\n"
        "    mae = float(np.mean(np.abs(ae_errs))) if ae_errs else float('nan')\n"
        "    rho_vals = [float(r[rho_key]) for r in pm_rows\n"
        "                if isinstance(r.get(rho_key), (int, float))]\n"
        "    rho_rmse = float(np.mean(rho_vals)) if rho_vals else float('nan')\n"
        "    return mae, rho_rmse, len(pm_rows)\n\n"
        "for _spec in _all_specs:\n"
        "    _tail = _spec.checkpoint_dir.rstrip('/').split('/')\n"
        "    # checkpoint_dir = STEP7_ROOT/metric/tag/ARCH_NAME/LOSS_NAME/solver\n"
        "    _solver  = _tail[-1]\n"
        "    _metric  = _tail[-5]  # e.g. 'l2' or 'jsd'\n"
        "    _tag     = _tail[-4]  # e.g. 'bin02' or 'bin02w'\n"
        "    _eval_out = os.path.join(_spec.checkpoint_dir, 'eval')\n"
        "    _pm_path  = os.path.join(_eval_out, 'per_molecule.json')\n"
        "    _csv_path = os.path.join(_spec.checkpoint_dir, 'eval_df.csv')\n"
        "    if not os.path.isfile(_pm_path):\n"
        "        continue\n"
        "    if os.path.isfile(_csv_path) and not RERUN_EVAL:\n"
        "        continue\n"
        "    with open(_pm_path) as _f:\n"
        "        _pm = json.load(_f)\n"
        "    _mae, _rho, _n = _aggregate_per_molecule(_pm)\n"
        "    _rows = [{\n"
        "        'metric':   _metric,\n"
        "        'tag':      _tag,\n"
        "        'solver':   _solver,\n"
        "        'set':      'training_subset',\n"
        "        'mae':      _mae,\n"
        "        'rho_rmse': _rho,\n"
        "        'n_eval':   _n,\n"
        "    }]\n"
        "    _df = pd.DataFrame(_rows)\n"
        "    _df.to_csv(_csv_path, index=False)\n\n"
        "_n_written = sum(\n"
        "    1 for _spec in _all_specs\n"
        "    if os.path.isfile(os.path.join(_spec.checkpoint_dir, 'eval_df.csv'))\n"
        ")\n"
        "print(f'eval_df.csv written: {_n_written} / {len(_all_specs)} specs')\n"
    ))
    # --- Cell E: held-out probe-set evaluation (T23) -------------------------
    cells.append(_md(
        "## 5g. Held-Out Probe-Set Evaluation (T23)\n\n"
        "For each trained spec, evaluate on **4 cited probe subsets** drawn\n"
        "from G2/97 (Haunschild2012) and the Truhlar HTBH/NHTBH databases.\n"
        "None of the probe entries overlap the Dick training pool; each\n"
        "probe targets a distinct generalization axis:\n\n"
        "- **probe_a_chemical_similarity** — 6 first-row organics/inorganics\n"
        "  not in training (CH4, C2H4, C2H6, CHO, NH2, H2O2)\n"
        "- **probe_b_heteroatom** — 6 third-period species (H2S, HCl, SO,\n"
        "  SO2, PH3, SiH4)\n"
        "- **probe_c_bh76_transfer** — 6 BH76 reactions outside training\n"
        "- **probe_d_multireference** — 6 strong-correlation challenges\n"
        "  (O2, CN, ClO, OF2, Cl2, BeH)\n\n"
        "Cited values are pulled from `xcquinox.alec.eval_probes`; see that\n"
        "module's docstring for source citations (Haunschild & Klopper 2012\n"
        "JCP 136, 164102; Zheng-Zhao-Truhlar JCTC 5, 808; Karton-2017 W4-17).\n"
        "Output: `spec_dir/eval_probes/<probe_name>/{aggregate,per_molecule}.json`.\n"
    ))
    cells.append(_code(
        "import time as _time\n"
        "import gc\n"
        "import jax\n"
        "from xcquinox.alec import eval_probes\n\n"
        "RERUN_PROBES = False  # set True to force-recompute per-probe aggregate.json\n\n"
        "# Build the 4 probe pools once (each contains a list of ASE Atoms\n"
        "# with attached info-dicts carrying ae_kcalmol / source / rationale).\n"
        "_PROBE_POOLS = {n: eval_probes.build_probe_pool(n)\n"
        "                for n in eval_probes.ALL_PROBES}\n"
        "for _pn, _pp in _PROBE_POOLS.items():\n"
        "    print(f\"  {_pn:32s} kind={_pp['kind']} n={_pp['n']} \"\n"
        "          f\"atoms={sorted(_pp['atom_set'])}\")\n\n"
        "# Atomic energies must cover every element appearing in any probe.\n"
        "# Re-use ATOMIC_ENERGIES_CHAKRAVORTY (defined in cell A).  Probes\n"
        "# B/C/D introduce S, P, Cl, Si, Be — supply their non-relativistic\n"
        "# total energies in Hartree from Chakravorty et al. 1993 Phys. Rev.\n"
        "# A 47, 3649 (atomic-only Table I, where present) and the more\n"
        "# recent CCSD(T)/AV5Z atomic refs from Feller-Peterson PCCP 12,\n"
        "# 6243 (2010) for the 3rd-period species.\n"
        "_PROBE_ATOM_ENERGIES = dict(ATOMIC_ENERGIES_CHAKRAVORTY)\n"
        "_PROBE_ATOM_ENERGIES.update({\n"
        "    'Be':  -14.6674,   # Chakravorty 1993 Table I\n"
        "    'P':   -341.2590,  # Chakravorty 1993 Table I\n"
        "    'Cl':  -460.1480,  # Chakravorty 1993 Table I\n"
        "    'Si':  -289.3590,  # Chakravorty 1993 Table I\n"
        "    'S':   -398.1095,  # Chakravorty 1993 Table I (overrides earlier placeholder)\n"
        "})\n\n"
        "def _probe_atoms_to_mol_spec(at, basis='def2-svp', grid_level=1):\n"
        "    \"\"\"ASE Atoms -> MoleculeSpec, mirroring _atoms_to_mol_spec but\n"
        "    using the probe's name and reading spin/charge from at.info.\n"
        "    Wires external_data_path so density_rmse can read CCSD refs\n"
        "    written by Cell 0.5 (R2-D Round-2 finding).\"\"\"\n"
        "    name = at.info.get('name',\n"
        "           at.info.get('probe_hill', at.get_chemical_formula()))\n"
        "    charge = int(at.info.get('charge', 0))\n"
        "    spin   = int(at.info.get('spin',   0))\n"
        "    atom_str = _atoms_to_pyscf_str(at)\n"
        "    comp_raw = Counter(at.get_chemical_symbols())\n"
        "    # Wire external CCSD reference path (mirrors _atoms_to_mol_spec).\n"
        "    _ext_npz = EXTERNAL_REFS_DIR / f'{name}.npz'\n"
        "    external_data_path = str(_ext_npz) if _ext_npz.is_file() else None\n"
        "    return alec.MoleculeSpec.from_dict(\n"
        "        name=name, atom=atom_str, basis=basis,\n"
        "        charge=charge, spin=spin,\n"
        "        atom_composition=dict(comp_raw),\n"
        "        grid_level=grid_level,\n"
        "        external_data_path=external_data_path,\n"
        "    )\n\n"
        "_n_probe_runs = 0; _n_probe_cached = 0; _n_probe_no_ckpt = 0\n"
        "_t_probe_start = _time.time()\n"
        "_PROBE_FLUSH_EVERY = 16\n"
        "for _idx, _spec in enumerate(_all_specs):\n"
        "    _ckpt = os.path.join(_spec.checkpoint_dir, 'model.eqx')\n"
        "    if not os.path.isfile(_ckpt):\n"
        "        _n_probe_no_ckpt += 1\n"
        "        continue\n"
        "    _solver_label = _spec.checkpoint_dir.rstrip('/').split('/')[-1]\n"
        "    for _probe_name, _pp in _PROBE_POOLS.items():\n"
        "        _eval_out = os.path.join(_spec.checkpoint_dir,\n"
        "                                  'eval_probes', _probe_name)\n"
        "        if not RERUN_PROBES and os.path.isfile(\n"
        "                os.path.join(_eval_out, 'aggregate.json')):\n"
        "            _n_probe_cached += 1\n"
        "            continue\n"
        "        # Build MoleculeSpec for every probe Atoms (AE molecules\n"
        "        # OR BH76 reactant/product species).\n"
        "        _mol_specs = tuple(_probe_atoms_to_mol_spec(at)\n"
        "                           for at in _pp['molecules'])\n"
        "        _ae_ref_kc: dict = {}\n"
        "        if _pp['kind'] == 'ae':\n"
        "            # Probe-A/B/D: per-molecule AE evaluation.\n"
        "            for _at in _pp['molecules']:\n"
        "                _ae_ref_kc[_at.info['name']] = float(\n"
        "                    _at.info['ae_kcalmol'])\n"
        "        # For BH76 probes, _ae_ref_kc remains empty: AE-metric is\n"
        "        # not meaningful for radical fragments.  We still include\n"
        "        # 'atomization_energy' in metrics but with empty refs so\n"
        "        # per_molecule.json captures predicted AE for every species.\n"
        "        _test_spec = alec.TestSpec.from_dicts(\n"
        "            arch=alec.get_architecture(ARCH_NAME),\n"
        "            model_checkpoint=_ckpt,\n"
        "            molecules=_mol_specs,\n"
        "            metrics=('total_energy', 'atomization_energy',\n"
        "                     'density_rmse', 'scf_convergence'),\n"
        "            metric_kwargs={\n"
        "                'atomization_energy': {'reference_ae_kcalmol': _ae_ref_kc},\n"
        "            },\n"
        "            atom_energies=_PROBE_ATOM_ENERGIES,\n"
        "            output_dir=_eval_out,\n"
        "            solver_config=SOLVER_CONFIGS[_solver_label],\n"
        "        )\n"
        "        _t0 = _time.time()\n"
        "        alec.run_test(_test_spec)\n"
        "        _n_probe_runs += 1\n"
        "        if _n_probe_runs % _PROBE_FLUSH_EVERY == 0:\n"
        "            jax.clear_caches(); gc.collect()\n"
        "    if (_idx + 1) % 8 == 0:\n"
        "        _elapsed = _time.time() - _t_probe_start\n"
        "        print(f'  [{_idx+1:>3d}/{len(_all_specs)}] '\n"
        "              f'probe_runs={_n_probe_runs} cached={_n_probe_cached} '\n"
        "              f'elapsed={_elapsed/60:5.1f}min', flush=True)\n\n"
        "print(f'[probes] runs={_n_probe_runs} cached={_n_probe_cached} '\n"
        "      f'no_ckpt={_n_probe_no_ckpt}  '\n"
        "      f'total={(_time.time()-_t_probe_start)/60:.1f}min', flush=True)\n"
    ))
    # --- Cell F: probe-set per_molecule.json -> eval_df.csv aggregator ------
    cells.append(_md(
        "## 5h. Probe-Set Aggregation\n\n"
        "Folds the per-spec/per-probe `per_molecule.json` files into the\n"
        "spec's `eval_df.csv` with `set=<probe_name>`.  For BH76 reactions\n"
        "(probe_c_bh76_transfer), additionally compute per-reaction signed\n"
        "errors from cached species total-energies and write rows with\n"
        "`value_name='rxn_error_kcalmol'`.\n"
    ))
    cells.append(_code(
        "import json\n"
        "import pandas as pd\n"
        "from xcquinox.alec import eval_probes\n\n"
        "_PROBE_POOLS = {n: eval_probes.build_probe_pool(n)\n"
        "                for n in eval_probes.ALL_PROBES}\n\n"
        "def _bh76_rxn_error(rxn, total_e_kcalmol_by_name):\n"
        "    \"\"\"Compute predicted - reference reaction energy in kcal/mol.\n"
        "    Returns None if any reactant/product is missing.\n"
        "    \"\"\"\n"
        "    species = (*rxn['reactants'], *rxn['products'])\n"
        "    coeffs = rxn['coeffs']\n"
        "    e_pred = 0.0\n"
        "    for sp, c in zip(species, coeffs):\n"
        "        if sp not in total_e_kcalmol_by_name:\n"
        "            return None\n"
        "        e_pred += c * total_e_kcalmol_by_name[sp]\n"
        "    return e_pred - rxn['e_rxn_ref']\n\n"
        "for _spec in _all_specs:\n"
        "    _tail = _spec.checkpoint_dir.rstrip('/').split('/')\n"
        "    _solver  = _tail[-1]\n"
        "    _metric  = _tail[-5]\n"
        "    _tag     = _tail[-4]\n"
        "    _csv_path = os.path.join(_spec.checkpoint_dir, 'eval_df.csv')\n"
        "    # Read existing CSV (training-subset rows) if present so we APPEND.\n"
        "    if os.path.isfile(_csv_path):\n"
        "        _df_existing = pd.read_csv(_csv_path)\n"
        "        # Drop any prior probe-rows so re-runs don't double-write.\n"
        "        _df_existing = _df_existing[\n"
        "            _df_existing['set'] == 'training_subset'].copy()\n"
        "    else:\n"
        "        _df_existing = pd.DataFrame()\n"
        "    _new_rows = []\n"
        "    for _probe_name, _pp in _PROBE_POOLS.items():\n"
        "        _eval_out = os.path.join(_spec.checkpoint_dir,\n"
        "                                 'eval_probes', _probe_name)\n"
        "        _pm_path = os.path.join(_eval_out, 'per_molecule.json')\n"
        "        if not os.path.isfile(_pm_path):\n"
        "            continue\n"
        "        with open(_pm_path) as _f:\n"
        "            _pm = json.load(_f)\n"
        "        if _pp['kind'] == 'bh76':\n"
        "            # Aggregate reaction-energy MAE across reactions in this probe.\n"
        "            _e_pred_kcalmol = {}\n"
        "            for _row in _pm:\n"
        "                _name = _row.get('name') or _row.get('molecule')\n"
        "                if 'total_energy_kcalmol' in _row:\n"
        "                    _e_pred_kcalmol[_name] = _row['total_energy_kcalmol']\n"
        "                elif 'total_energy' in _row:\n"
        "                    _e_pred_kcalmol[_name] = _row['total_energy'] * KCAL_PER_HA\n"
        "            _rxn_errs = []\n"
        "            for _rxn in _pp['reactions']:\n"
        "                _err = _bh76_rxn_error(_rxn, _e_pred_kcalmol)\n"
        "                if _err is not None:\n"
        "                    _rxn_errs.append(float(_err))\n"
        "            _mae = (float(np.mean(np.abs(_rxn_errs)))\n"
        "                    if _rxn_errs else float('nan'))\n"
        "            _new_rows.append({\n"
        "                'metric':   _metric,\n"
        "                'tag':      _tag,\n"
        "                'solver':   _solver,\n"
        "                'set':      _probe_name,\n"
        "                'mae':      _mae,\n"
        "                'rho_rmse': float('nan'),\n"
        "                'n_eval':   len(_rxn_errs),\n"
        "            })\n"
        "        else:\n"
        "            _mae, _rho, _n = _aggregate_per_molecule(_pm)\n"
        "            _new_rows.append({\n"
        "                'metric':   _metric,\n"
        "                'tag':      _tag,\n"
        "                'solver':   _solver,\n"
        "                'set':      _probe_name,\n"
        "                'mae':      _mae,\n"
        "                'rho_rmse': _rho,\n"
        "                'n_eval':   _n,\n"
        "            })\n"
        "    if _new_rows:\n"
        "        _df_new = pd.DataFrame(_new_rows)\n"
        "        _df_out = (pd.concat([_df_existing, _df_new], ignore_index=True)\n"
        "                   if not _df_existing.empty else _df_new)\n"
        "        _df_out.to_csv(_csv_path, index=False)\n\n"
        "_n_with_probes = sum(\n"
        "    1 for _spec in _all_specs\n"
        "    if os.path.isfile(os.path.join(_spec.checkpoint_dir, 'eval_df.csv'))\n"
        "    and 'probe_a' in open(os.path.join(_spec.checkpoint_dir,\n"
        "                                       'eval_df.csv')).read()\n"
        ")\n"
        "print(f'eval_df.csv with probe rows: {_n_with_probes} / {len(_all_specs)} specs')\n"
    ))
    cells.append(_md(
        "## 6. Post-Processing Analysis\n\n"
        "Generates 6 figures + headline.json from the 80 eval_df.csv files.\n"
    ))
    cells.append(_code(
        "import sys\n"
        "import subprocess\n"
        "result = subprocess.run([\n"
        "    sys.executable,\n"
        "    str(REPO / 'reports_local' / 'step7_subset_selection' / 'scripts' / 'run_post_processing.py'),\n"
        "], capture_output=True, text=True)\n"
        "print(result.stdout)\n"
        "if result.returncode != 0:\n"
        "    print('STDERR:', result.stderr)\n"
        "    raise RuntimeError(f'post-processing failed: exit {result.returncode}')\n"
    ))
    return cells


def main() -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = build_cells()
    NOTEBOOK_OUT.write_text(nbf.writes(nb), encoding="utf-8")
    print(f"wrote {NOTEBOOK_OUT}")


if __name__ == "__main__":
    main()
