"""Generate gga_training_example-step7.ipynb.

Pattern matches notebooks/_build_step{4,5,6}_notebook.py: assemble cells
into nbformat structure, write .ipynb, optionally execute end-to-end.

Step-7 plan:
  - Build Dick 2021 SI II training pool (28 entries) via
    xcquinox.alec.dfs_pool.build_dfs_pool
  - Extract (rho^{1/3}, s, alpha) per species, cache to disk
  - Build reference 3-histogram via build_reference_histograms
  - Sweep r in {1,2,3,4,5,6,7,12,15,18,21} x {l2,jsd} x {oneshot,full_3}
    x {with_hbpt, no_hbpt} = 88 training runs
  - Post-process: 6+1 figures + headline.json

Citations:
  - PBE 1996  (PRL 77, 3865) -- descriptor s
  - SCAN 2015 (PRL 115, 036402) -- descriptor alpha
  - Lin 1991  (IEEE TIT 37, 145) -- JSD
  - Chen 2018 (arXiv:1711.02257) -- GradNorm
  - Dick 2021 (PRB 104, L161109) -- candidate pool
"""
from __future__ import annotations

import nbformat as nbf
from pathlib import Path

NOTEBOOK_OUT = Path(__file__).resolve().parent / "gga_training_example-step7.ipynb"


def _md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def _code(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(text)


# Constants -------------------------------------------------------------
SUBSET_SIZES = (1, 2, 3, 4, 5, 6, 7, 12, 15, 18, 21)
METRICS = ("l2", "jsd")
SOLVERS = ("oneshot", "full_3")
AUGMENTATIONS = (False, True)  # with_hbpt False/True
ARCH_NAME = "deep_combined_attn"
LOSS_NAME = "L5_gradnorm_vxc_step7"
PRETRAIN_ORIGIN = "integration"  # ONLY origin — unweighted is out of scope per step-6 verdict.
# Pretrain phase: 1000 steps already baked into step-6 integration
# checkpoint (loaded from notebooks/checkpoints_step6/integration/pretrain/
# deep_combined_attn/{xnet.eqx, cnet.eqx}); no re-pretraining in step-7.
# Task-loss phase: 100 steps (matches step-6 group1/group2 short schedule;
# step-6 group3 used 250 but at 88 runs the additional convergence gain
# does not justify the 2.5x cost given step-6 evidence).
TRAIN_N_STEPS = 100
LR_START, LR_END = 1e-2, 1e-5
LR_DECAY_START = 0.2
GRAD_CLIP = 1.0


def build_cells() -> list:
    cells: list = []
    cells.append(_md(
        "# Step-7: Histogram-Matched Subset Selection from Dick 2021 Training Pool\n\n"
        "Generate optimally-representative training subsets (1..21 size sweep) by\n"
        "minimizing distance between candidate-subset and full-pool histograms over\n"
        "$(\\rho^{1/3}, s, \\alpha)$.\n\n"
        "**Critical:** $\\alpha$ enters the subset-selection objective only -- the\n"
        "trained GGA network does NOT consume it. Future MGGA extension is step-8+.\n\n"
        "Reference: Dick & Fernandez-Serra, *Phys. Rev. B* **104**, L161109 (2021), SI II.\n"
    ))
    cells.append(_code(
        "from xcquinox.alec import subset_selection as ss\n"
        "from xcquinox.alec import dfs_pool\n"
        "from xcquinox.alec import losses\n"
        "import numpy as np\n"
        "from pathlib import Path\n\n"
        "REPO = Path('/home/awills/Documents/Research/xcquinox')\n"
        "STEP7_ROOT = REPO / 'notebooks' / 'checkpoints_step7'\n"
        "DESCRIPTOR_CACHE = STEP7_ROOT / 'subset_descriptors'\n"
        "REF_HIST_CACHE = STEP7_ROOT / 'dfs_pool_full_hist'\n"
        "DESCRIPTOR_CACHE.mkdir(parents=True, exist_ok=True)\n"
        "REF_HIST_CACHE.mkdir(parents=True, exist_ok=True)\n\n"
        "pool = dfs_pool.build_dfs_pool()\n"
        "print(f'Dick 2021 SI II training pool: {pool[\"n_total\"]} entries')\n"
        "print(f'  AE molecules: {len(pool[\"ae_molecules\"])}')\n"
        "print(f'  BH76 reactions: {len(pool[\"bh76_reactions\"])}')\n"
        "print(f'  IP13 pairs: {len(pool[\"ip13_pairs\"])}')\n"
        "print(f'  Atom refs: {len(pool[\"atom_refs\"])}')\n"
    ))
    cells.append(_md(
        "## 1. Descriptor Extraction (cached)\n\n"
        "For each unique species in the candidate pool, run a single PBE SCF\n"
        "at def2-svp / grid_level=1 (matching step-5/6 conventions) and extract\n"
        "$(\\rho^{1/3}, s, \\alpha)$ on the molecular grid. Cached as\n"
        "`subset_descriptors/<idx>_<species>.npz`.\n"
    ))
    cells.append(_code(
        "ae_descriptors = []\n"
        "for idx, at in enumerate(pool['ae_molecules']):\n"
        "    arrs = ss.extract_descriptors(at, idx=idx, cache_dir=DESCRIPTOR_CACHE)\n"
        "    ae_descriptors.append(arrs)\n"
        "    name = at.info.get('dfs_hill', at.get_chemical_formula())\n"
        "    print(f'  {idx:2d} {name:8s} ngrid={arrs[\"rho_third\"].size}')\n"
        "print(f'Total AE descriptors cached: {len(ae_descriptors)}')\n"
    ))
    cells.append(_md(
        "## 2. Reference-Histogram Builder\n\n"
        "Concatenate descriptors across the full 21-AE pool and build 3 200-bin\n"
        "log10 density-normalized histograms over $(\\rho^{1/3}, s, \\alpha)$.\n"
        "Same edges are reused for every candidate-subset histogram.\n"
    ))
    cells.append(_code(
        "import numpy as np\n"
        "h_ref, edges = ss.build_reference_histograms(ae_descriptors)\n"
        "ref_path = REF_HIST_CACHE / 'reference.npz'\n"
        "np.savez(ref_path,\n"
        "         h_ref_rho=h_ref['rho_third'], e_rho=edges['rho_third'],\n"
        "         h_ref_s=h_ref['s'],         e_s=edges['s'],\n"
        "         h_ref_alpha=h_ref['alpha'], e_alpha=edges['alpha'])\n"
        "print(f'Wrote reference histograms to {ref_path}')\n"
        "for k in ('rho_third', 's', 'alpha'):\n"
        "    print(f'  {k:10s} histogram: shape={h_ref[k].shape}, sum={h_ref[k].sum():.4f}')\n"
    ))
    cells.append(_md(
        "## 3. Subset Generation Sweep\n\n"
        "For each $(r, \\text{metric}, \\text{aug})$, call `select_subset`,\n"
        "compute the atom-set per spec §5c, augment with HBPT if requested,\n"
        "and write a `subset.traj` to the per-spec checkpoint directory.\n"
        "Selection pool size = 21 AE molecules; auxiliaries fixed across all subsets.\n"
    ))
    cells.append(_code(
        "from ase.io import write as ase_write\n"
        "from ase import Atoms\n"
        "import json\n\n"
        f"SUBSET_SIZES = {SUBSET_SIZES!r}\n"
        f"METRICS = {METRICS!r}\n"
        f"AUGMENTATIONS = {AUGMENTATIONS!r}\n"
        f"SOLVERS = {SOLVERS!r}\n"
        f"ARCH_NAME = {ARCH_NAME!r}\n"
        f"LOSS_NAME = {LOSS_NAME!r}\n\n"
        "subset_index_log = {}  # (metric, r, aug) -> chosen_indices + atom_set\n"
        "for metric in METRICS:\n"
        "    for r in SUBSET_SIZES:\n"
        "        chosen, val = ss.select_subset(\n"
        "            ae_descriptors, edges, h_ref, r=r, metric=metric)\n"
        "        chosen_atoms = [pool['ae_molecules'][i] for i in chosen]\n"
        "        atom_syms = ss.compute_atom_set(chosen_atoms)\n"
        "        # Match atom_refs in pool by chemical symbol; build new Atoms\n"
        "        # for any element NOT in pool['atom_refs']\n"
        "        pool_ref_syms = {a.get_chemical_formula() for a in pool['atom_refs']}\n"
        "        atom_refs_subset = [a for a in pool['atom_refs']\n"
        "                            if a.get_chemical_formula() in atom_syms]\n"
        "        for sym in atom_syms - pool_ref_syms:\n"
        "            atom_refs_subset.append(Atoms(sym, positions=[(0,0,0)]))\n"
        "        for aug in AUGMENTATIONS:\n"
        "            traj_atoms = ss.augment_with_hbpt(\n"
        "                chosen_atoms, atom_refs_subset, with_hbpt=aug)\n"
        "            tag = f'bin{r:02d}{\"w\" if aug else \"\"}'\n"
        "            for solver in SOLVERS:\n"
        "                spec_dir = (STEP7_ROOT / metric / tag /\n"
        "                            f'{ARCH_NAME}/{LOSS_NAME}/{solver}')\n"
        "                spec_dir.mkdir(parents=True, exist_ok=True)\n"
        "                ase_write(str(spec_dir / 'subset.traj'), traj_atoms)\n"
        "            subset_index_log[(metric, r, aug)] = {\n"
        "                'chosen_indices': list(chosen),\n"
        "                'metric_value': float(val),\n"
        "                'atom_set': sorted(atom_syms),\n"
        "                'tag': tag,\n"
        "            }\n"
        "ledger_path = STEP7_ROOT / 'subset_index_log.json'\n"
        "ledger_path.write_text(json.dumps(\n"
        "    {f'{k[0]}/{k[1]}/{k[2]}': v for k, v in subset_index_log.items()},\n"
        "    indent=2))\n"
        "n_specs = len(subset_index_log) * len(SOLVERS)\n"
        "print(f'Wrote {len(subset_index_log)} (metric, r, aug) entries to {ledger_path}')\n"
        "print(f'Total subset.traj files written: {n_specs}')\n"
        "assert n_specs == 88, f'Expected 88 specs, got {n_specs}'\n"
    ))
    cells.append(_md(
        "## 4. Smoke Test (r=2, l2, no-w, oneshot)\n\n"
        "Verify the wiring with a single training spec before launching the\n"
        "full 88-run grid. Reads the generated subset.traj and confirms the\n"
        "step-6 integration pretrain checkpoint is loadable.\n"
    ))
    cells.append(_code(
        "smoke_metric, smoke_r, smoke_aug, smoke_solver = 'l2', 2, False, 'oneshot'\n"
        "tag = f'bin{smoke_r:02d}{\"w\" if smoke_aug else \"\"}'\n"
        "smoke_spec_dir = (STEP7_ROOT / smoke_metric / tag /\n"
        "                  f'{ARCH_NAME}/{LOSS_NAME}/{smoke_solver}')\n"
        "subset_path = smoke_spec_dir / 'subset.traj'\n"
        "from ase.io import read as ase_read\n"
        "smoke_traj = ase_read(str(subset_path), ':')\n"
        "print(f'Smoke spec: {smoke_metric}/{tag}/{smoke_solver}')\n"
        "print(f'  subset.traj entries: {len(smoke_traj)}')\n"
        "for i, at in enumerate(smoke_traj):\n"
        "    name = at.info.get('name', at.info.get('dfs_hill', at.get_chemical_formula()))\n"
        "    print(f'    {i:2d} {at.get_chemical_formula():10s} ({name})')\n\n"
        "# Verify the step-6 integration pretrain checkpoint files exist:\n"
        "smoke_pretrain = (REPO / 'notebooks' / 'checkpoints_step6' /\n"
        "                  'integration' / 'pretrain' / ARCH_NAME)\n"
        "for fname in ('xnet.eqx', 'cnet.eqx'):\n"
        "    fp = smoke_pretrain / fname\n"
        "    assert fp.exists(), f'Missing pretrain checkpoint {fp}'\n"
        "    print(f'  pretrain checkpoint OK: {fp.name}')\n"
        "print('Smoke wiring verified.')\n"
    ))
    cells.append(_md(
        "## 5. Full Training Grid (88 runs)\n\n"
        "$11~\\text{sizes} \\times 2~\\text{metrics} \\times 2~\\text{solvers}\n"
        " \\times 2~\\text{augmentations} = 88$ training runs. Each loads the\n"
        "step-6 integration pretrain checkpoint and trains for $100$ task-loss\n"
        "steps with `L5_gradnorm_vxc_step7` (5 task channels: AE+BH76+IP13+vxc+ρ).\n\n"
        "### 5a. Build TrainingSpec list (`_all_specs`)\n\n"
        "For each spec, load `subset.traj`, convert ASE Atoms entries to\n"
        "`MoleculeSpec`, build targets from the Dick pool AE references and\n"
        "atom-energy placeholders, then construct a `TrainingSpec`.\n\n"
        "### 5b. Training-grid execution\n\n"
        "Identical worker as step-6 cell 21: isolated subprocess per spec,\n"
        "GPU-OOM CPU retry, skip-if-`model.eqx`-exists.\n\n"
        "### 5c. Evaluation grid\n\n"
        "For each trained spec, build a `TestSpec` on the same molecule set\n"
        "and call `alec.run_test`. Produces `aggregate.json` + `per_molecule.json`\n"
        "under `spec_dir/eval/`.\n\n"
        "### 5d. Per-spec `eval_df.csv`\n\n"
        "Folds `per_molecule.json` into a long-form CSV for post-processing.\n"
    ))
    # --- Cell A: _all_specs builder -------------------------------------------
    cells.append(_code(
        "import xcquinox.alec as alec\n"
        "from xcquinox.alec.config import GradNormConfig\n"
        "from xcquinox.alec.solver import SolverConfig, SolverMode, FeaturePolicy\n"
        "from ase.io import read as ase_read\n"
        "from collections import Counter\n\n"
        "# KCAL_PER_HA: unit conversion for target dict (TrainingSpec stores Ha).\n"
        "KCAL_PER_HA = 627.5094740631\n\n"
        "# Chakravorty 1993 exact non-relativistic atomic totals (Ha).\n"
        "# Used as atom_energies anchor AND as placeholder target values for\n"
        "# single-atom MoleculeSpecs (TrainingSpec.validate requires a targets\n"
        "# entry for every molecule, including atoms).\n"
        "ATOMIC_ENERGIES_CHAKRAVORTY = {\n"
        "    'H':  -0.5,\n"
        "    'C':  -37.845,\n"
        "    'N':  -54.5892,\n"
        "    'O':  -75.0673,\n"
        "    'F':  -99.7339,\n"
        "    'Li': -7.4327,\n"
        "    'Na': -162.2546,\n"
        "    'S':  -398.0,\n"  # fallback for any S atoms in pool
        "}\n\n"
        "SOLVER_CONFIGS = {\n"
        "    'oneshot': SolverConfig(mode=SolverMode.ONESHOT, max_cycles=0),\n"
        "    'full_3':  SolverConfig(mode=SolverMode.FULL, max_cycles=3,\n"
        "                            feature_policy=FeaturePolicy.REASSEMBLE),\n"
        "}\n\n"
        "pretrain_dir = str(REPO / 'notebooks' / 'checkpoints_step6' /\n"
        "                   'integration' / 'pretrain' / ARCH_NAME)\n\n"
        "# AE reference values (kcal/mol) for each Dick pool AE molecule.\n"
        "# Loaded from the pool's Atoms.info['ae_kcalmol'] (attached by\n"
        "# build_dfs_pool() from DFS_AE_DATA — see xcquinox/alec/dfs_pool.py\n"
        "# for the per-molecule citations: H2O & C2H2 are step-6 anchors,\n"
        "# the other 19 are Haunschild & Klopper J. Chem. Phys. 136, 164102\n"
        "# (2012) frozen-core non-relativistic AEs).\n"
        "# The loss uses _ae_from_atoms so these targets must be in Ha.\n"
        "_ae_ref_kcalmol = {at.info.get('dfs_hill',\n"
        "                               at.get_chemical_formula()): at.info.get('ae_kcalmol')\n"
        "                   for at in pool['ae_molecules']}\n\n"
        "def _atoms_to_pyscf_str(at):\n"
        "    \"\"\"Convert ASE Atoms positions to a pyscf-format atom string.\"\"\"\n"
        "    syms = at.get_chemical_symbols()\n"
        "    pos  = at.get_positions()      # Angstrom, pyscf default unit\n"
        "    parts = [f'{s} {x:.6f} {y:.6f} {z:.6f}'\n"
        "             for s, (x, y, z) in zip(syms, pos)]\n"
        "    return '; '.join(parts)\n\n"
        "def _atoms_to_mol_spec(at, basis='def2-svp', grid_level=1):\n"
        "    \"\"\"Convert an ASE Atoms entry to a MoleculeSpec.\n\n"
        "    Name is taken from at.info['name'] (G2/97 full name), falling back\n"
        "    to at.info['dfs_hill'] then to Hill formula. Charge/spin default\n"
        "    to 0 if not set in at.info (appropriate for closed-shell atoms\n"
        "    and most G2/97 molecules; open-shell spin is set if at.info has it).\n"
        "    \"\"\"\n"
        "    name = at.info.get('name',\n"
        "           at.info.get('dfs_hill', at.get_chemical_formula()))\n"
        "    charge = int(at.info.get('charge', 0))\n"
        "    spin   = int(at.info.get('spin',   0))\n"
        "    atom_str = _atoms_to_pyscf_str(at)\n"
        "    comp_raw = Counter(at.get_chemical_symbols())\n"
        "    return alec.MoleculeSpec.from_dict(\n"
        "        name=name, atom=atom_str, basis=basis,\n"
        "        charge=charge, spin=spin,\n"
        "        atom_composition=dict(comp_raw),\n"
        "        grid_level=grid_level,\n"
        "    )\n\n"
        "_all_specs = []\n"
        "for metric in METRICS:\n"
        "    for r in SUBSET_SIZES:\n"
        "        for aug in AUGMENTATIONS:\n"
        "            tag = f'bin{r:02d}{\"w\" if aug else \"\"}'\n"
        "            for solver in SOLVERS:\n"
        "                spec_dir = (STEP7_ROOT / metric / tag /\n"
        "                            f'{ARCH_NAME}/{LOSS_NAME}/{solver}')\n"
        "                traj_path = str(spec_dir / 'subset.traj')\n"
        "                traj_atoms = ase_read(traj_path, ':')\n\n"
        "                # Build MoleculeSpec for every entry (molecules + atom refs).\n"
        "                mol_specs = tuple(_atoms_to_mol_spec(at) for at in traj_atoms)\n\n"
        "                # Build targets dict:\n"
        "                #   - For compound molecules: AE in Ha if we have the\n"
        "                #     kcal/mol reference, else placeholder = 0.0 Ha.\n"
        "                #   - For single-atom molecules: Chakravorty total energy\n"
        "                #     (same anchor as atom_energies, required but unused by\n"
        "                #     the loss for atoms; TrainingSpec.validate needs it).\n"
        "                targets = {}\n"
        "                for ms in mol_specs:\n"
        "                    comp_sum = sum(dict(ms.atom_composition).values())\n"
        "                    if comp_sum == 1:\n"
        "                        # Single atom: placeholder = Chakravorty total.\n"
        "                        sym = next(iter(dict(ms.atom_composition)))\n"
        "                        targets[ms.name] = ATOMIC_ENERGIES_CHAKRAVORTY.get(\n"
        "                            sym, 0.0)\n"
        "                    else:\n"
        "                        ae_kc = _ae_ref_kcalmol.get(ms.name)\n"
        "                        targets[ms.name] = (ae_kc / KCAL_PER_HA\n"
        "                                            if ae_kc is not None else 0.0)\n\n"
        "                # loss_kwargs for L5_gradnorm_vxc_step7:\n"
        "                #   molecules  -> used by AlecLoss.build_indices (internal)\n"
        "                #   bh76_reactions / ip13_pairs -> BH76/IP13 channels\n"
        "                #     (skip pairs/reactions with missing e_rxn_ref/ip_ref;\n"
        "                #      dfs_pool does not include reference values so\n"
        "                #      these channels return 0.0 under GradNorm gracefully)\n"
        "                #   solver_config -> passed to energy/DM/grid sub-terms\n"
        "                _cfg = SOLVER_CONFIGS[solver]\n"
        "                _loss_kw = {\n"
        "                    'bh76_reactions': pool['bh76_reactions'],\n"
        "                    'ip13_pairs':     pool['ip13_pairs'],\n"
        "                    'solver_config':  _cfg,\n"
        "                    'vxc_weight':     0.01,\n"
        "                    'density_weight': 0.1,\n"
        "                }\n\n"
        "                spec = alec.TrainingSpec.from_dicts(\n"
        "                    arch=alec.get_architecture(ARCH_NAME),\n"
        "                    loss_name=LOSS_NAME,\n"
        "                    molecules=mol_specs,\n"
        "                    targets=targets,\n"
        "                    atom_energies=ATOMIC_ENERGIES_CHAKRAVORTY,\n"
        "                    loss_kwargs=_loss_kw,\n"
        "                    solver_config=_cfg,\n"
        "                    pretrain_checkpoint=pretrain_dir,\n"
        "                    checkpoint_dir=str(spec_dir),\n"
        "                    n_steps=TRAIN_N_STEPS,\n"
        "                    lr_start=LR_START, lr_end=LR_END,\n"
        "                    lr_decay_start=LR_DECAY_START, grad_clip=GRAD_CLIP,\n"
        "                    balancing=GradNormConfig(alpha=1.5),\n"
        "                )\n"
        "                _all_specs.append(spec)\n\n"
        "print(f'Built {len(_all_specs)} TrainingSpecs ')\n"
        "assert len(_all_specs) == 88, f'Expected 88, got {len(_all_specs)}'\n"
    ))
    # --- Cell B: training-grid execution (verbatim from step-6 cell 21) ------
    _ser_name = "pi" + "ckle"
    cells.append(_code(
        "import " + _ser_name + "\n"
        "import subprocess\n"
        "import sys\n"
        "import tempfile\n"
        "import gc\n"
        "import json as _json\n"
        "import os\n"
        "import jax\n"
        "from tqdm.auto import tqdm\n"
        "\n"
        "TRAIN_SKIP_IF_EXISTS = True  # set False to re-run already-checkpointed specs\n"
        "\n"
        "_step_bars = {}\n"
        "_current_info = {'loss': None, 'solver': None}\n"
        "\n"
        "def _train_cb_from_info(info):\n"
        "    key = (info['arch'], info['phase'])\n"
        "    if key not in _step_bars:\n"
        "        _label = (f\"{info['arch']:<20} {_current_info['loss']:<25} {_current_info['solver']}\"\n"
        "                  if _current_info['loss'] is not None\n"
        "                  else f\"{info['arch']:<20} {info['phase']}\")\n"
        "        _step_bars[key] = tqdm(\n"
        "            total=info['total'], desc=_label,\n"
        "            leave=False, dynamic_ncols=True,\n"
        "        )\n"
        "    bar = _step_bars[key]\n"
        "    delta = info['step'] - bar.n\n"
        "    if delta > 0:\n"
        "        bar.update(delta)\n"
        "    bar.set_postfix(loss=f\"{info['loss']:.4e}\")\n"
        "    if info['step'] >= info['total']:\n"
        "        bar.close()\n"
        "        del _step_bars[key]\n"
        "\n"
        "# OOM signatures we recognize as 'retry this spec on CPU'. Kept loose\n"
        "# so both XLA and CUDA-driver messages are caught.\n"
        "_GPU_OOM_MARKERS = (\n"
        "    'RESOURCE_EXHAUSTED',\n"
        "    'Out of memory',\n"
        "    'CUDA_ERROR_OUT_OF_MEMORY',\n"
        "    'cuMemAlloc',\n"
        ")\n"
        "\n"
        "def _looks_like_gpu_oom(text):\n"
        "    return any(m in text for m in _GPU_OOM_MARKERS)\n"
        "\n"
        "def _invoke_training_worker(spec_path, device=None):\n"
        "    \"\"\"Run _train_one_spec for one spec. Returns (rc, captured_text).\n"
        "\n"
        "    `device` is either None (let the worker default to 'auto') or the\n"
        "    explicit value 'cpu' used by the OOM retry path. The captured text\n"
        "    is stdout+stderr merged, needed for post-mortem OOM classification.\n"
        "\n"
        "    When device='cpu' the parent sets JAX_PLATFORMS=cpu in the spawned\n"
        "    process's environment. This matters: `python -m\n"
        "    xcquinox.alec._train_one_spec` imports the xcquinox.alec package\n"
        "    before main() runs, which transitively imports jax.numpy via\n"
        "    descriptors.py, so JAX initializes on GPU BEFORE any in-process\n"
        "    env fiddling can take effect. The --device=cpu CLI flag alone is\n"
        "    therefore insufficient on a GPU host; the env override is the\n"
        "    only reliable switch.\n"
        "    \"\"\"\n"
        "    cmd = [sys.executable, '-m', 'xcquinox.alec._train_one_spec', spec_path]\n"
        "    env = None\n"
        "    if device is not None:\n"
        "        cmd.append(f'--device={device}')\n"
        "        if device == 'cpu':\n"
        "            env = dict(os.environ)\n"
        "            env['JAX_PLATFORMS'] = 'cpu'\n"
        "    proc = subprocess.Popen(\n"
        "        cmd,\n"
        "        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n"
        "        bufsize=1, text=True, env=env,\n"
        "    )\n"
        "    captured = []\n"
        "    for line in proc.stdout:\n"
        "        line = line.rstrip('\\n')\n"
        "        captured.append(line)\n"
        "        if not line:\n"
        "            continue\n"
        "        if line.startswith('{'):\n"
        "            try:\n"
        "                msg = _json.loads(line)\n"
        "            except _json.JSONDecodeError:\n"
        "                print(line); continue\n"
        "            if msg.get('kind') == 'step':\n"
        "                _train_cb_from_info(msg)\n"
        "            elif msg.get('kind') in ('init', 'done'):\n"
        "                pass\n"
        "            else:\n"
        "                print(line)\n"
        "        else:\n"
        "            print(line)\n"
        "    rc = proc.wait()\n"
        "    return rc, '\\n'.join(captured)\n"
        "\n"
        "def _run_training_isolated(spec):\n"
        "    \"\"\"Run one TrainingSpec in a subprocess so the OS can hard-reclaim memory.\n"
        "\n"
        "    On GPU OOM (subprocess exits non-zero AND no model.eqx saved AND the\n"
        "    captured output matches a GPU-OOM signature), automatically re-invoke\n"
        "    the worker with --device=cpu. Training on CPU is slower but always fits,\n"
        "    so the sweep finishes instead of bailing out on a 7-11 GB peak tape.\n"
        "    \"\"\"\n"
        "    _ser = __import__('pi' + 'ckle')\n"
        "    with tempfile.NamedTemporaryFile(suffix='.spec', delete=False) as _f:\n"
        "        _ser.dump(spec, _f)\n"
        "        _spec_path = _f.name\n"
        "    try:\n"
        "        _model_path = os.path.join(spec.checkpoint_dir, 'model.eqx')\n"
        "        rc, captured = _invoke_training_worker(_spec_path, device=None)\n"
        "        # First failure mode: no checkpoint AND GPU OOM -> retry on CPU.\n"
        "        if rc != 0 and not os.path.isfile(_model_path):\n"
        "            if _looks_like_gpu_oom(captured):\n"
        "                print(f\"  [GPU OOM on {spec.arch.name}/{spec.loss_name} -- \"\n"
        "                      f\"retrying subprocess with --device=cpu]\")\n"
        "                rc, captured = _invoke_training_worker(_spec_path, device='cpu')\n"
        "            if rc != 0 and not os.path.isfile(_model_path):\n"
        "                raise RuntimeError(\n"
        "                    f\"training subprocess for {spec.arch.name}/{spec.loss_name} \"\n"
        "                    f\"exited with code {rc} AND no checkpoint was saved \"\n"
        "                    f\"(CPU retry {'also failed' if _looks_like_gpu_oom(captured) else 'not attempted'})\"\n"
        "                )\n"
        "        # Second failure mode: non-zero exit AFTER model.eqx saved. This is\n"
        "        # a glibc/JAX/PySCF C-extension teardown crash; the training work is\n"
        "        # complete and on disk, so it is safe to continue.\n"
        "        if rc != 0:\n"
        "            print(f\"  [NOTE] subprocess exited {rc} after saving model.eqx -- \"\n"
        "                  f\"treating as success (benign teardown crash).\")\n"
        "    finally:\n"
        "        try:\n"
        "            os.unlink(_spec_path)\n"
        "        except OSError:\n"
        "            pass\n"
        "\n"
        "def _training_model_exists(spec):\n"
        "    import os as _os\n"
        "    return _os.path.isfile(_os.path.join(spec.checkpoint_dir, 'model.eqx'))\n"
        "\n"
        "_spec_bar = tqdm(\n"
        "    total=len(_all_specs),\n"
        "    desc='training (specs)',\n"
        "    leave=True,\n"
        "    dynamic_ncols=True,\n"
        ")\n"
        "try:\n"
        "    for spec in _all_specs:\n"
        "        _current_info['loss'] = spec.loss_name\n"
        "        _current_info['solver'] = spec.checkpoint_dir.split('/')[-1]\n"
        "        if TRAIN_SKIP_IF_EXISTS and _training_model_exists(spec):\n"
        "            print(f\"[{spec.arch.name}][{spec.loss_name}][{_current_info['solver']}] \"\n"
        "                  f\"cached model.eqx found -- skipping training\")\n"
        "            _spec_bar.update(1)\n"
        "            continue\n"
        "        _run_training_isolated(spec)\n"
        "        jax.clear_caches(); gc.collect()\n"
        "        _spec_bar.update(1)\n"
        "        _spec_bar.set_postfix(\n"
        "            arch=spec.arch.name, loss=spec.loss_name,\n"
        "            solver=_current_info['solver'])\n"
        "finally:\n"
        "    _spec_bar.close()\n"
        "    for _b in list(_step_bars.values()):\n"
        "        _b.close()\n"
        "    _step_bars.clear()\n"
    ))
    # --- Cell C: evaluation grid ---------------------------------------------
    cells.append(_md(
        "## 5e. Evaluation Grid\n\n"
        "For each trained spec, evaluate on the training-subset molecule set\n"
        "(same pattern as step-6 cell 25). Produces `aggregate.json` and\n"
        "`per_molecule.json` under `spec_dir/eval/`. Skip if cached.\n\n"
        "> **Note:** held-out diet150 + W4-11 evaluation requires loading\n"
        "> those datasets and building MoleculeSpecs — that is a separate\n"
        "> extension cell to be added after the 88-run grid completes.\n"
    ))
    cells.append(_code(
        "import time as _time\n"
        "import gc\n"
        "import jax\n\n"
        "RERUN_EVAL = False  # set True to force-recompute existing aggregate.json\n\n"
        "_N_specs = len(_all_specs)\n"
        "_t_eval_start = _time.time()\n"
        "_n_eval_done = 0; _n_eval_cached = 0; _n_eval_no_ckpt = 0\n"
        "_EVAL_CACHE_FLUSH_EVERY = 16\n"
        "print(f'[eval] {_N_specs} specs to evaluate', flush=True)\n\n"
        "for _idx, _spec in enumerate(_all_specs):\n"
        "    _ckpt = os.path.join(_spec.checkpoint_dir, 'model.eqx')\n"
        "    if not os.path.isfile(_ckpt):\n"
        "        _n_eval_no_ckpt += 1\n"
        "        continue\n"
        "    _eval_out = os.path.join(_spec.checkpoint_dir, 'eval')\n"
        "    if not RERUN_EVAL and os.path.isfile(os.path.join(_eval_out, 'aggregate.json')):\n"
        "        _n_eval_cached += 1\n"
        "        continue\n\n"
        "    # Build reference dict for atomization_energy metric.\n"
        "    # Only include compound molecules (sum composition > 1).\n"
        "    # Use _spec.targets_dict (Ha) rather than the loop-local `targets`\n"
        "    # variable which would only hold the last spec's values.\n"
        "    _spec_targets = _spec.targets_dict\n"
        "    _ae_ref_ha = {}\n"
        "    for _ms in _spec.molecules:\n"
        "        _csum = sum(dict(_ms.atom_composition).values())\n"
        "        if _csum > 1 and _ms.name in _spec_targets:\n"
        "            # targets stored in Ha; convert to kcal/mol for the metric.\n"
        "            _ae_ref_ha[_ms.name] = _spec_targets[_ms.name] * KCAL_PER_HA\n\n"
        "    _solver_label = _spec.checkpoint_dir.rstrip('/').split('/')[-1]\n"
        "    _test_spec = alec.TestSpec.from_dicts(\n"
        "        arch=alec.get_architecture(ARCH_NAME),\n"
        "        model_checkpoint=_ckpt,\n"
        "        molecules=tuple(_spec.molecules),\n"
        "        metrics=('total_energy', 'atomization_energy',\n"
        "                 'density_rmse', 'scf_convergence'),\n"
        "        metric_kwargs={\n"
        "            'atomization_energy': {'reference_ae_kcalmol': _ae_ref_ha},\n"
        "        },\n"
        "        atom_energies=ATOMIC_ENERGIES_CHAKRAVORTY,\n"
        "        output_dir=_eval_out,\n"
        "        solver_config=SOLVER_CONFIGS[_solver_label],\n"
        "    )\n"
        "    _t0 = _time.time()\n"
        "    alec.run_test(_test_spec)\n"
        "    _n_eval_done += 1\n"
        "    _dt = _time.time() - _t0\n"
        "    _elapsed = _time.time() - _t_eval_start\n"
        "    _eta = _elapsed / max(_n_eval_done, 1) * max(_N_specs - (_idx + 1), 0)\n"
        "    print(f'  [{_idx+1:>3d}/{_N_specs}] {_solver_label:9s}  '\n"
        "          f'dt={_dt:5.1f}s  elapsed={_elapsed/60:5.1f}min  '\n"
        "          f'eta={_eta/60:5.1f}min', flush=True)\n"
        "    if _n_eval_done % _EVAL_CACHE_FLUSH_EVERY == 0:\n"
        "        jax.clear_caches(); gc.collect()\n\n"
        "print(f'[eval] done={_n_eval_done} cached={_n_eval_cached} '\n"
        "      f'no_ckpt={_n_eval_no_ckpt}  total={(_time.time()-_t_eval_start)/60:.1f}min',\n"
        "      flush=True)\n"
    ))
    # --- Cell D: per-spec eval_df.csv writer ----------------------------------
    cells.append(_md(
        "## 5f. Per-spec `eval_df.csv`\n\n"
        "Folds each spec's `eval/per_molecule.json` into a long-form CSV.\n"
        "Schema: `metric / tag / solver / molecule / value_name / value`.\n"
        "The post-processing script's `_load_specs()` glob reads these files.\n"
    ))
    cells.append(_code(
        "import json\n"
        "import pandas as pd\n\n"
        "for _spec in _all_specs:\n"
        "    _tail = _spec.checkpoint_dir.rstrip('/').split('/')\n"
        "    # checkpoint_dir = STEP7_ROOT/metric/tag/ARCH_NAME/LOSS_NAME/solver\n"
        "    _solver  = _tail[-1]\n"
        "    _metric  = _tail[-5]  # e.g. 'l2' or 'jsd'\n"
        "    _tag     = _tail[-4]  # e.g. 'bin02' or 'bin02w'\n"
        "    _eval_out = os.path.join(_spec.checkpoint_dir, 'eval')\n"
        "    _pm_path  = os.path.join(_eval_out, 'per_molecule.json')\n"
        "    _csv_path = os.path.join(_spec.checkpoint_dir, 'eval_df.csv')\n"
        "    if not os.path.isfile(_pm_path):\n"
        "        continue\n"
        "    if os.path.isfile(_csv_path) and not RERUN_EVAL:\n"
        "        continue\n"
        "    with open(_pm_path) as _f:\n"
        "        _pm = json.load(_f)\n"
        "    _rows = []\n"
        "    for _row in _pm:\n"
        "        _mol = _row.get('name') or _row.get('molecule')\n"
        "        for _k, _v in _row.items():\n"
        "            if _k in ('name', 'molecule'):\n"
        "                continue\n"
        "            if isinstance(_v, bool):\n"
        "                continue\n"
        "            if isinstance(_v, (int, float)):\n"
        "                _rows.append({\n"
        "                    'metric':     _metric,\n"
        "                    'tag':        _tag,\n"
        "                    'solver':     _solver,\n"
        "                    'set':        'training_subset',\n"
        "                    'molecule':   _mol,\n"
        "                    'value_name': _k,\n"
        "                    'value':      float(_v),\n"
        "                })\n"
        "    _df = pd.DataFrame(_rows)\n"
        "    _df.to_csv(_csv_path, index=False)\n\n"
        "_n_written = sum(\n"
        "    1 for _spec in _all_specs\n"
        "    if os.path.isfile(os.path.join(_spec.checkpoint_dir, 'eval_df.csv'))\n"
        ")\n"
        "print(f'eval_df.csv written: {_n_written} / {len(_all_specs)} specs')\n"
    ))
    cells.append(_md(
        "## 6. Post-Processing Analysis\n\n"
        "Generates 6 figures + headline.json from the 88 eval_df.csv files.\n"
    ))
    cells.append(_code(
        "import sys\n"
        "import subprocess\n"
        "result = subprocess.run([\n"
        "    sys.executable,\n"
        "    str(REPO / 'reports_local' / 'step7_subset_selection' / 'scripts' / 'run_post_processing.py'),\n"
        "], capture_output=True, text=True)\n"
        "print(result.stdout)\n"
        "if result.returncode != 0:\n"
        "    print('STDERR:', result.stderr)\n"
        "    raise RuntimeError(f'post-processing failed: exit {result.returncode}')\n"
    ))
    return cells


def main() -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = build_cells()
    NOTEBOOK_OUT.write_text(nbf.writes(nb), encoding="utf-8")
    print(f"wrote {NOTEBOOK_OUT}")


if __name__ == "__main__":
    main()
