#!/bin/bash
#SBATCH --job-name=ptscan_mgga
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=joshua.franklin@stonybrook.edu
#SBATCH --output=mgga.txt
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --time=168:00:00
#SBATCH -p extended-40core

cd $HOME
source .bashrc

source /gpfs/projects/FernandezGroup/Alec/miniconda3/etc/profile.d/conda.sh

conda init bash

conda activate pyscfad

WORKDIR=/gpfs/scratch/jofranklin/xcquinox/scan4
cd $WORKDIR

# Process MGGA directories
for dir in *_mgga/
do
    cd $dir
    bash ./run_script.sh 2>&1 | tee output.out
    cd ../
done

