"""Hygiene of the tracked tree: no training snapshot is tracked, no tracked file is large
enough to be a result blob, the data directories and the results directory hold exactly what
their lists name, no test-named module sits outside a tests directory, and every architecture
diagram is a source with its render beside it.

The index tests read ``git ls-files``, so a staged addition is seen before its commit; the rule
tests exercise each predicate on names that must fire it and names that must not. The size cap
is 16 MiB: the largest file the tree keeps is the results summary PDF (12.4 MB). A document that
grows past the cap is a decision to take here, not an accident to let through. Sizes are read
from the working tree, so the size test runs on a full checkout. What the tests do not catch is
a result tree added under a new directory name with every file under the cap and no numbered
snapshot: the cap bounds each file such a tree can carry.
"""
from __future__ import annotations

import os
import re
import subprocess
import tomllib
from pathlib import Path
from typing import Iterable

import pytest

_ROOT = Path(__file__).resolve().parents[1]

#: the periodic ``<name>.eqx.<step>`` snapshots a training run writes
_NUMBERED_SNAPSHOT = re.compile(r"\.eqx\.\d+$")

SIZE_CAP_BYTES = 16 * 1024 * 1024

#: the v7 reports directory: the summary, the deck with its frames and code appendix, the
#: excerpts and the five figure sets the documents cite, and nothing else
REPORTS_V7 = "reports/v7/"
REPORTS_V7_CONTENTS = (
    "SUMMARY_v7_2026-09-15.md",
    "SUMMARY_v7_2026-09-15.tex",
    "SUMMARY_v7_2026-09-15.pdf",
    "SLIDES_v7_2026-09-15.tex",
    "SLIDES_v7_2026-09-15.pdf",
    "SLIDES_v7_2026-09-15_frames.tex",
    "SLIDES_v7_2026-09-15_code_appendix.tex",
    "slides_code/",
    "figures_dfs_step7_v7_family/",
    "figures_dfs_step7_v7_family_pretrain/",
    "figures_dfs_step7_v7_family_val_best/",
    "figures_dfs_step7_v7_family_val_best_excl_tail/",
    "figures_dfs_step7_v7_subsets/",
)

#: the architecture diagrams: every tracked ``.dot`` has its ``.svg`` render beside it and
#: nothing else
DIAGRAMS_ROOT = "docs/architecture/diagrams/"
_GRAPHVIZ_VERSION = re.compile(rb"Generated by graphviz version (\S+)")
_SVG_LABEL = re.compile(rb"<(title|text)\b[^>]*>([^<]*)</\1>")

#: the repository data of the campaign and the package data of the G2/97 set, listed both
#: ways: every entry is tracked, and nothing else is tracked under the two roots; a trailing
#: slash marks a directory that holds at least one tracked file
DATA_ROOTS = ("data/", "xcquinox/data/")
DATA_CONTENTS = (
    "data/README.md",
    "data/gmtkn55/PROVENANCE.md",
    "data/dietgmtkn55-150/AllElements-150.yaml",
    "data/dietgmtkn55-150/SubsetGMTKN55_150.yaml",
    "data/dietgmtkn55-150/diet150.traj",
    "data/dietgmtkn55-50/AllElements_050.yaml",
    "data/dietgmtkn55-50/diet50.traj",
    "data/slim/PROVENANCE.md",
    "data/slim/Slim100M_05_composition.txt",
    "data/slim/Slim100M_16_composition.txt",
    "data/slim/Slim100M_20_composition.txt",
    "data/training_subsets/",
    "data/oep_tune/2026-05-06/",
    "xcquinox/data/README.md",
    "xcquinox/data/haunschild_g2/G297I.traj",
    "xcquinox/data/haunschild_g2/g2_97.csv",
    "xcquinox/data/haunschild_g2/g2_97.traj",
    "xcquinox/data/haunschild_g2/g2_97.xyz",
    "xcquinox/data/haunschild_g2/haunshild_coords.xyz",
    "xcquinox/data/haunschild_g2/haunshild_parsing.ipynb",
    "xcquinox/data/haunschild_g2/single_atoms.traj",
)


def _tracked() -> list[str]:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=_ROOT, capture_output=True,
                         check=True).stdout.decode("utf-8", errors="replace")
    return [p for p in out.split("\0") if p]


def numbered_snapshots(paths: Iterable[str]) -> list[str]:
    """The paths of the form ``<name>.eqx.<integer>``."""
    return [p for p in paths if _NUMBERED_SNAPSHOT.search(p)]


def test_snapshot_rule_fires_on_numbered_snapshots_only():
    """``xc.eqx.12`` and ``xc.eqx.0`` fire; the plain and the named network files and a
    non-numeric suffix do not, and neither does a ``.chkpt`` reference file."""
    flagged = numbered_snapshots([
        "run/xc.eqx.12",
        "run/xc.eqx.0",
        "run/xc.eqx",
        "run/model_val_best.eqx",
        "run/xc.eqx.bak",
        "refs/0_O3.chkpt",
    ])
    assert flagged == ["run/xc.eqx.12", "run/xc.eqx.0"]


def test_no_numbered_snapshot_is_tracked():
    """No tracked path is a periodic training snapshot, under any directory."""
    offenders = numbered_snapshots(_tracked())
    assert offenders == [], (
        f"{len(offenders)} tracked training snapshots, for example {offenders[:3]}: a run's "
        f"periodic <name>.eqx.<step> files are outputs, never source")


def reports_v7_offences(paths: Iterable[str]) -> tuple[list[str], list[str]]:
    """``(missing, strays)``: the listed contents with no tracked file, and the tracked files
    under the reports directory that the list does not cover."""
    rel = sorted(p[len(REPORTS_V7):] for p in paths if p.startswith(REPORTS_V7))
    dirs = tuple(c for c in REPORTS_V7_CONTENTS if c.endswith("/"))
    files = [c for c in REPORTS_V7_CONTENTS if not c.endswith("/")]
    missing = ([f for f in files if f not in rel]
               + [d for d in dirs if not any(r.startswith(d) for r in rel)])
    strays = [r for r in rel if r not in files and not r.startswith(dirs)]
    return missing, strays


def test_reports_rule_fires_on_fixtures():
    """The reports rule reports a missing document and a stray file, and accepts the complete
    listing."""
    complete = [REPORTS_V7 + c for c in REPORTS_V7_CONTENTS if not c.endswith("/")]
    complete += [REPORTS_V7 + c + "x" for c in REPORTS_V7_CONTENTS if c.endswith("/")]
    assert reports_v7_offences(complete) == ([], [])
    missing, strays = reports_v7_offences(complete[1:] + [REPORTS_V7 + "stray.txt"])
    assert missing == ["SUMMARY_v7_2026-09-15.md"] and strays == ["stray.txt"]


def test_reports_v7_holds_the_documents_and_the_cited_figure_sets():
    """reports/v7 carries the summary, the deck, the excerpts and the five cited figure sets,
    and nothing the list does not name."""
    missing, strays = reports_v7_offences(_tracked())
    assert missing == [], f"reports/v7 lacks {missing}"
    assert strays == [], f"reports/v7 carries files the list does not name: {strays[:5]}"


def test_no_tracked_file_above_the_size_cap():
    """Every tracked file present in the working tree is at most the cap."""
    large = []
    for path in _tracked():
        full = _ROOT / path
        if full.is_file():
            size = os.stat(full).st_size
            if size > SIZE_CAP_BYTES:
                large.append((size, path))
    large.sort(reverse=True)
    assert large == [], (
        f"{len(large)} tracked files above {SIZE_CAP_BYTES} bytes, the largest "
        f"{large[:3]}")


def data_offences(paths: Iterable[str]) -> tuple[list[str], list[str]]:
    """``(missing, strays)``: the listed data contents with no tracked file, and the tracked
    files under the data roots that the list does not cover."""
    tracked = [p for p in paths if p.startswith(DATA_ROOTS)]
    dirs = tuple(c for c in DATA_CONTENTS if c.endswith("/"))
    files = [c for c in DATA_CONTENTS if not c.endswith("/")]
    missing = ([f for f in files if f not in tracked]
               + [d for d in dirs if not any(t.startswith(d) for t in tracked)])
    strays = [t for t in tracked if t not in files and not t.startswith(dirs)]
    return missing, strays


def misnamed_as_tests(paths: Iterable[str]) -> list[str]:
    """The tracked ``test_*.py`` files under the package that do not sit in a ``tests``
    directory: pytest collects them as test modules, so a worker or a script named that way
    is misnamed. The helper itself must not start with ``test_``, or pytest collects it and
    reports an error for its parameter."""
    out = []
    for p in paths:
        if not p.startswith("xcquinox/") or not p.endswith(".py"):
            continue
        parts = p.split("/")
        if parts[-1].startswith("test_") and "tests" not in parts[:-1]:
            out.append(p)
    return out


def diagram_strays(paths: Iterable[str]) -> tuple[list[str], list[str]]:
    """``(unrendered, strays)`` under the diagrams directory: the ``.dot`` sources without a
    tracked ``.svg`` beside them, and the tracked files that are neither a source nor the
    render of a source."""
    under = [p for p in paths if p.startswith(DIAGRAMS_ROOT)]
    sources = {p[:-4] for p in under if p.endswith(".dot")}
    unrendered = sorted(s + ".dot" for s in sources if s + ".svg" not in under)
    strays = sorted(p for p in under
                    if not (p.endswith(".dot") or (p.endswith(".svg") and p[:-4] in sources)))
    return unrendered, strays


def render_difference(fresh: bytes, tracked: bytes) -> str | None:
    """How a tracked SVG differs from the render of its source by the installed graphviz,
    or None: under the same graphviz version the two must be equal byte for byte (a label
    edited in the SVG without a new layout, or a source edited without a new render, differs
    there); under another version the layout is not comparable, and the labels and titles
    of the two, in order, must agree."""
    if fresh == tracked:
        return None
    versions = [_GRAPHVIZ_VERSION.search(b) for b in (fresh, tracked)]
    if all(versions) and versions[0].group(1) == versions[1].group(1):
        return (f"the render by graphviz {versions[0].group(1).decode()} differs from the "
                f"tracked file, which names the same version")
    if [m.group(2) for m in _SVG_LABEL.finditer(fresh)] != [
            m.group(2) for m in _SVG_LABEL.finditer(tracked)]:
        return "the labels or titles differ from the source's render"
    return None


def stale_renders(root: Path, sources: Iterable[str]) -> list[tuple[str, str]]:
    """``(svg path, difference)`` for every source under ``root`` whose tracked render
    differs from the installed graphviz's render of it, by :func:`render_difference`."""
    out = []
    for source in sources:
        svg = source[:-4] + ".svg"
        fresh = subprocess.run(["dot", "-Tsvg", str(root / source)], capture_output=True,
                               check=True).stdout
        difference = render_difference(fresh, (root / svg).read_bytes())
        if difference is not None:
            out.append((svg, difference))
    return out


def test_data_and_naming_rules_fire_on_fixtures():
    """The data list reports a missing entry and a stray file and accepts the complete
    listing; the naming rule fires on a test-named worker and not on a test under a tests
    directory, a tools test, a worker with a plain name or a data file."""
    complete = [c for c in DATA_CONTENTS if not c.endswith("/")]
    complete += [c + "x" for c in DATA_CONTENTS if c.endswith("/")]
    assert data_offences(complete) == ([], [])
    missing, strays = data_offences(complete[1:] + ["data/stray.txt"])
    assert missing == ["data/README.md"] and strays == ["data/stray.txt"]
    assert misnamed_as_tests([
        "xcquinox/pipeline/workers/test_worker.py", "xcquinox/pipeline/tests/test_a.py",
        "xcquinox/tests/test_b.py", "tools/test_repository_hygiene.py",
        "xcquinox/pipeline/workers/evaluation_worker.py",
        "xcquinox/pipeline/tests/fixtures/test_data.json",
    ]) == ["xcquinox/pipeline/workers/test_worker.py"]


def test_data_trees_hold_their_contents():
    """data/ and xcquinox/data/ carry the listed contents and nothing the list does not
    name."""
    missing, strays = data_offences(_tracked())
    assert missing == [], f"the data trees lack {missing[:5]}"
    assert strays == [], f"the data trees carry files the list does not name: {strays[:5]}"


def test_no_test_named_file_outside_a_tests_directory_under_the_package():
    """No tracked ``test_*.py`` under the package sits outside a tests directory."""
    offenders = misnamed_as_tests(_tracked())
    assert offenders == [], (
        f"{len(offenders)} test-named files outside a tests directory: {offenders[:3]}")


def test_diagram_rules_fire_on_fixtures():
    """The diagrams list reports a source without its render and a stray file; the render
    rule reports a same-version difference and a label difference across versions, and
    accepts equal bytes or a layout difference across versions with the labels equal."""
    unrendered, strays = diagram_strays([
        "docs/architecture/diagrams/a.dot", "docs/architecture/diagrams/a.svg",
        "docs/architecture/diagrams/b.dot", "docs/architecture/diagrams/a.png",
        "docs/architecture/diagrams/c.svg", "docs/architecture/x.md",
    ])
    assert unrendered == ["docs/architecture/diagrams/b.dot"]
    assert strays == ["docs/architecture/diagrams/a.png", "docs/architecture/diagrams/c.svg"]
    fresh = (b"<!-- Generated by graphviz version 2.44.0 (0) -->\n"
             b'<g><title>run</title><polygon points="1,2"/><text x="1">python -m '
             b"xcquinox.pipeline.cluster</text></g>")
    assert render_difference(fresh, fresh) is None
    substituted = fresh.replace(b"xcquinox.pipeline.cluster", b"xcquinox.other.cluster")
    assert "2.44.0" in render_difference(fresh, substituted)
    older = fresh.replace(b"2.44.0", b"2.43.0").replace(b'points="1,2"', b'points="1,3"')
    assert render_difference(fresh, older) is None
    older_substituted = substituted.replace(b"2.44.0", b"2.43.0")
    assert render_difference(fresh, older_substituted) == (
        "the labels or titles differ from the source's render")


def test_diagrams_are_sources_with_their_renders():
    """Every tracked source under the diagrams directory has its render beside it, nothing
    else is tracked there, and each render is the installed graphviz's render of its
    source (skipped where graphviz is not installed)."""
    import shutil
    unrendered, strays = diagram_strays(_tracked())
    assert unrendered == [], f"sources without a tracked render: {unrendered}"
    assert strays == [], f"files under the diagrams directory beyond the pairs: {strays}"
    if shutil.which("dot") is None:
        pytest.skip("graphviz is not installed")
    sources = [p for p in _tracked() if p.startswith(DIAGRAMS_ROOT) and p.endswith(".dot")]
    stale = stale_renders(_ROOT, sources)
    assert stale == [], f"renders that differ from their sources: {stale}"


def test_package_data_declares_the_g2_set():
    """The package data the loaders read is declared, so a wheel carries it."""
    with open(_ROOT / "pyproject.toml", "rb") as fh:
        cfg = tomllib.load(fh)
    patterns = cfg["tool"]["setuptools"]["package-data"]["xcquinox"]
    assert "data/haunschild_g2/*" in patterns, patterns
