# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

# The source tree, for a build that runs without an install.
import os
import sys
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = 'xcquinox'
copyright = '2024-2026, Alec Wills'
author = 'Alec Wills'

# The version is the package's own, read from the installed metadata and, where the site is
# built from a tree that is not installed, from the generated version module.
try:
    from importlib.metadata import version as _installed_version

    release = _installed_version('xcquinox')
except Exception:  # pragma: no cover - a tree without an install
    try:
        from xcquinox._version import __version__ as release
    except Exception:
        release = '0+unknown'
# the public part, without the local segment the version control adds (the distance and the
# commit, which do not belong in every page's title)
version = release.split('+')[0]
html_title = f'{project} {version} documentation'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosummary',
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.extlinks',
    'sphinx.ext.todo',
    # the site's pages are markdown; the API pages are reStructuredText
    'myst_parser',
    # the flow diagrams are written inline as mermaid beside their rendered images
    'sphinxcontrib.mermaid',
]

# the notes and the runbook use dollar math and link to their own headings
myst_enable_extensions = ['dollarmath']
# the flow diagrams are written as mermaid fences, which the extension renders
myst_fence_as_directive = ['mermaid']
myst_heading_anchors = 3

autosummary_generate = True
# both styles are in the tree: the reST field lists of the package and the Google-style
# Args/Returns/Raises sections of the harness modules
napoleon_google_docstring = True
napoleon_use_param = False
napoleon_use_ivar = True

# The API pages import the package, so the site is built with the package installed (the
# read-the-docs configuration installs it with the documentation extra). Nothing is mocked:
# a mocked base class cannot be subclassed, and every descriptor and network of the pipeline
# is defined that way.
autodoc_mock_imports = []
autodoc_default_options = {
    'member-order': 'bysource',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.md',
                    'superpowers', 'reviews',
                    '_static/README.md', '_templates/README.md']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'xcquinoxdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'xcquinox.tex', 'xcquinox Documentation',
     'xcquinox', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'xcquinox', 'xcquinox Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'xcquinox', 'xcquinox Documentation',
     author, 'xcquinox', 'A machine learning framework using the equinox library for learning XC functionals with JAX.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------
